### ISSUE TITLE
Marathon sometimes fixates on launching a specific app to the exclusion of others, ignoring dependencies

### ISSUE THREAD

**Issue by mforsyth** [mesosphere/marathon#1024]
I have a group which contains dependencies.

For example, "babyservice" depends on "parentservice".

Often, I will deploy the group, and "babyservice" will repeatedly get started over and over again.  Each time, it fails, because it tries to connect to "parentservice",  which isn't there because marathon has never even created a Mesos task for "parentservice".  Recently I saw "babyservice" start and fail 77 times in a row (without any attempts for "parentservice").

I know this may not be enough detail to go on - if there's a specific log file or something that you'd like me to include, let me know and I'll try to grab it next time this happens.

**Comment by drexin** [comment]
What does your json for the apps look like? Do you model the dependency there? If so, it should deploy the services in the correct order.

**Comment by sttts** [comment]
Are you sure that the parent service was NOT successfully started before? I.e. are you sure that the StartApplication step of "babyservice" is step 1 in the deployment?

I have seen often a health checked service like "parentservice" somehow passing the StartApplication step of the deployment with its health checked being completely ignored. Then in the next deployment step the "babyservice" fails due to missing "parentservice".

Hence, I think there is a bug that sometimes the StartApplication code will succeed although the app is down.

**Comment by mforsyth** [comment]
@drexin Yes, the dependencies are formally specified in the json of the apps.   @sttts When this happens, there may be be some trace (in zookeeper?) of the parentservice having been started before... but Mesos doesn't show any record of the parentservice having ever been launched (no running task, no finished task).  

I have just upgraded both Mesos & Marathon this morning to new version (0.7.6 of marathon) so I will close this issue if I don't see it pop up again soon.

**Comment by aquamatthias** [comment]
Hey @mforsyth I will close this issue. Please reopen, if this problem still exists.
