### ISSUE TITLE
more helpful error when /groups are POSTed to /apps

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1067]
Here's a common first-time user error:

1. User POSTs a new app to `/v2/apps` and gets it working. Hurray.
1. User creates an **app group** in JSON and POSTs it to `/v2/apps`. An error is returned saying that the `AppDefinition` is wrong.
1. User spends 1hr examining JSON before rereading the docs and realising you're meant to switch over to `/v2/groups` for this.

## Actions

1. In the `/v2/apps` endpoint, if the POSTed JSON looks like a `groups` definition, then add to the error message some guidance: `JSON contains a 'groups' element - maybe you meant /v2/groups?` or similar.
1. Add a note in [the doc](http://mesosphere.github.io/marathon/docs/application-groups.html) to point out that /groups and /apps are separate.

Example of groups definition:

```
{
  "id": "/bananas",
  "groups": [
  ...
```

**Comment by kolloch** [comment]
Generally, I like the idea of providing useful error message. So thanks for your suggestion.

Yet, the consequence would be that we check for every requests that contains a malformed body if that body would be suitable for another endpoint. We should not burden our code with this complexity for a class of user error for which we even do not know how often it is a problem.

Since I do not see discussion of this issue, I will close it for now.  If anyone disagrees, please reopen with an explanation.
