### ISSUE TITLE
Task launch delay too jittery

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1111]
Investigate smoothing out the task launch delay by modulating with some or all of the following data:
- Health of launched tasks
- Age of running tasks
- Age of failed tasks
- Ratio of failures / launches among recently launched tasks

```
14:44 sttts: which makes me wonder: I have an app which restarts every few seconds. marathon receives TASK_RUNNING, but the task just crashes immediately. I don't see the backoff
14:44 sttts: I guess the TASK_RUNNING will reset the task launch delay
14:45 ConnorDoyle: yes, that's right.
14:45 sttts: I collected >4000 stopped containers on one hosts this way, making mesos-slave refuse to start again
14:49 ConnorDoyle: We could make sure the app becomes healthy (if health checks are defined) before resetting the delay.  Otherwise maybe the delay should cool down somehow so that one TASK_RUNNING doesn't reset the delay.
14:53 sttts: imagine a situation where 10% of the tasks receive TASK_RUNNING, 90% fail immediately. there a cool down mechanism might help
14:53 sttts: backoffCooldownFactor :)
```

cc @sttts

**Comment by aquamatthias** [comment]
@ConnorDoyle Is that still a problem?

**Comment by ConnorDoyle** [comment]
Yes, and it's highly related to #1504 which is a customer priority.

**Comment by kolloch** [comment]
#1470 is also related.

The current strategy with `backoffSeconds/backoffFactor` does not work so well with many tasks because it does not consider the data mentioned above. I could imagine that different strategies are necessary but one that I like would work quite differently.

Imagine the following configuration:

```json
{
  "id": "/myapp",
   ...,
   "instances": 100,
   "taskStartStrategy": {
     "type": "exponential",
     "initialTasks": 1,
     "startFactor": 5
   }
}
```

I would propose following rules:

* If we have no running healthy tasks at all, have at most `"initialTasks"` number of tasks starting up.
* If we have h running healthy tasks, have at most h*`"startFactor"` tasks starting up.

Happy path for initial start up:

* Launch one (= `"initialTasks"`) task and wait for it to become healthy. We have one running tasks after that.
* Launch five (= healthyRunningTasks * `"startFactor"`) more tasks and wait for all of them to become healthy. We have 6 running tasks after that.
* Launch 30 (= healthyRunningTasks * `"startFactor"`) more tasks  and wait for all of them to become healthy. We have 36 running tasks after that.
* ...

So the start up begins carefully but gains traction quickly if we are successful in launching tasks.

In addition, one could still use the `backoffSeconds/backoffFactor` but only for trying to start the initial seed tasks.

The "viability problem" (#1504) might or might not be solved by only considering healthy tasks.

What do you think? @ConnorDoyle @solarkennedy

**Comment by BenWhitehead** [comment]
follow

**Comment by ConnorDoyle** [comment]
Following up with details from an off-line meeting @kolloch and I had yesterday...

1. Retain the current exponential backoff mechanism.
1. Add a per-app minimum "viability" duration for which a task must remain in the TASK_RUNNING state in order for the task launch to be considered successful.
1. For apps with health checks defined, use that as an indicator that a successful launch has occurred instead of the TASK_RUNNING status.
1. In addition to the initial task launch backoff duration and factor, add an initial task launch parallelism and factor.  The task launch parallelism must be reset to the initial value at the same time as the exponential backoff factor is reset.  This change is to avoid the problem where a large number of tasks all fail to launch, quickly increasing the backoff factor to its maximum limit.
1. _Optional._ Introduce a rate limit for increasing the task launch backoff as an additional /alternative way to mitigate the problem mentioned in (4) above.

**Comment by FlorentFlament** [comment]
This issue is also related to this bug: https://github.com/mesosphere/marathon/issues/3059

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4276. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
