### ISSUE TITLE
$HOME is not the same as $MESOS_SANDBOX

### ISSUE THREAD

**Issue by iven** [mesosphere/marathon#1128]
The document says that when using Docker:

```
The $HOME environment variable is set by default to the same value as $MESOS_SANDBOX.
```

But it's not true. I get:

```
MESOS_SANDBOX=/mnt/mesos/sandbox
HOME=/root
```

when running `env` in Docker container.

**Comment by drexin** [comment]
Mesos sets these variables, see: http://mesos.apache.org/documentation/latest/docker-containerizer/

Here's the code that sets `HOME`: https://github.com/apache/mesos/blob/master/src/docker/docker.cpp#L471

I'm closing this, because it is not a Marathon related issue. Could you please create a ticket on the Apache Jira? https://issues.apache.org/jira/secure/Dashboard.jspa

**Comment by drexin** [comment]
Oh, I just read the comment there. `HOME` is only set to `MESOS_SANDBOX`, when there's a `.dockercfg` in the URIs.
