### ISSUE TITLE
MARATHON_ env variables cause Marathon to fail to launch

### ISSUE THREAD

**Issue by stevendborrelli** [mesosphere/marathon#1143]
We've seen this bug when using marathon to launch more marathon processes. 

If you are running a process in marathon, the following environment variables are set:

```
MARATHON_APP_ID=/env
MARATHON_APP_VERSION=2015-02-04T19:39:03.629Z
```
However, the marathon start script interprets this as a request to set the flag --app-id, which causes it to fail on launch.

```
MESOS_NATIVE_JAVA_LIBRARY is not set. Searching in /usr/lib /usr/local/lib.
Registered executor on nodeXX
Starting task marathon_marathon.a0b96e12-ac9c-11e4-92e3-663d7e673b12
/bin/sh -c exit `docker wait mesos-a4ced3fd-b6d7-41ce-ba44-edde2e3476d4` 
Forked command at 18123
MESOS_NATIVE_LIBRARY, MESOS_NATIVE_JAVA_LIBRARY set to '/usr/lib/libmesos.so'
[2015-02-04 18:35:46,609] INFO Starting Marathon 0.7.5 (mesosphere.marathon.Main$:20)
[scallop] Error: Unknown option 'app_id'
Command exited with status 1 (pid: 18123)
```

**Comment by everpeace** [comment]
start scripts cannot determine which env var should be converted to option by themselves because valid option names are defined in source codes.

For resolving this issue in better way, I might propose to refactor how to read option values in marathon and chaos.  I think it would add reading env vars in `opt` like:

```scala
import scala.util.Properties.envOrNone
lazy val highlyAvailable = opt[Boolean]("ha", noshort = true, 
    default = envOrNone("MARATHON_HA").map(_.toBoolean).orElse(Some(true)))
```

Just for quick and temporal fix, I will make a PR which start scripts ignore `MARATHON_APP_*` env vars.  For now, env var names used in today's source codes are `MARATHON_APP_ID`, `MARATHON_APP_VERSION` and `MESOS_TASK_ID`(all are in `TaskBuilder`).  So, I think this fix will work.

**Comment by everpeace** [comment]
sorry for dirty referenced commits.  it's because I force pushed on my branch... 
6598e4e is valid commit for this. Please see the pull request.

**Comment by aquamatthias** [comment]
This should be fixed. If this is still a problem, please reopen.

**Comment by pyronicide** [comment]
This is still a problem in 0.9.0-RC2.

**Comment by ConnorDoyle** [comment]
@aquamatthias, should this have the 0.9.0 milestone instead?  It seems reasonable to me to cut a new RC with a fix for this bug.

**Comment by aquamatthias** [comment]
@ConnorDoyle Good point.
