### ISSUE TITLE
Marathon UI Ignores API Errors

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#116]
In case of an unexpected response (e.g. `500: Internal Server Error`), the web client should give some feedback indicating that something has gone wrong.

**Comment by pierlo-upitup** [comment]
In order to make progress here we need to identify all possible error scenarios. In general there are 2 possibilities:

– whenever a non-2xx response is received the UI should display errors (let's just alert() for now)
– for "async" actions, we need to imagine ad-hoc design solutions (e.g. showing an alert 5 seconds after a button was pushed is not a good idea) 

I will use this post to keep track of the specific ACs for this issue.

**Comment by pierlo-upitup** [comment]
New App Modal - submit form
----------------
- [x] Show validation errors to the user
- [x] Show message upon server failures (`Server error, could not create app.` displayed as inline error)

App list page
----------------
- [x] Show error upon "Scale" action errors (alerts `Not scaling: App is locked by one or more deployments.`)
- [x] Show error upon "Suspend" action errors (alerts `Not scaling: App is locked by one or more deployments.`)
- [x] Show error upon "Restart App" aciton errors (alerts `Error restarting app: App is locked by one or more deployments.`)
- [x] Show error upon "Destroy App" action errors (alerts `Error destroying app: ...`)

Deployments 
----------------
- [x] Show error upon "Rollback" action errors (alerts `Can't revert deployment: ...`)
- [x] Show error upon "Stop" action errors (alerts `Can't stop deployment: ...`)

What errors are we not covering? @philipnrmn can you lend your :eyes: on this one?

**Comment by pierlo-upitup** [comment]
@aldipower could you take a look at this?

**Comment by aldipower** [comment]
At my best knowledge we covering all errors, that are related to us. Also connection errors, while receiving the apps or something like that, an error is displayed. I remember that this was not the case in 0.7.0. So it seems to be fixed. I think this issue can be closed for now, otherwise please be more specific.

**Comment by mlunoe** [comment]
Could we get links to the specific PRs that handles these errors? I see https://github.com/mesosphere/marathon-ui/pull/99 as one, that can't be the only one.

**Comment by pierlo-upitup** [comment]
@mlunoe most of the handling I refer to has been introduced in the multi-part refactoring to Flux. I suggest taking a look at the individual `*Actions` (for ex. https://github.com/mesosphere/marathon-ui/blob/master/src/js/actions/AppsActions.js#L18, https://github.com/mesosphere/marathon-ui/blob/master/src/js/actions/AppVersionsActions.js#L19, https://github.com/mesosphere/marathon-ui/blob/master/src/js/actions/InfoActions.js#L18 etc... )

**Comment by mlunoe** [comment]
arh, ok!
