### ISSUE TITLE
Possible race condition on simultaneous application launch

### ISSUE THREAD

**Issue by cgbaker** [mesosphere/marathon#1215]
Hi Folks!

I'm running into a problem that appears at first glance to be a race condition on application launch. 

If I launch multiple (in my case, 4) apps at the same time by POSTing to /v2/apps, I notice two things: 
1. They are all four assigned the same (formerly available) port (e.g., port 10000)
2. I can only delete one of them via the UI or the REST API; the others have to be scaled down to zero before I can successfully delete them.

The outcome of the first symptom is sort of humorous, actually... the haproxy bridge configures port 10000 (in this example) against all four worker tasks, so that as I refresh, the proxy switches between the different apps. In the short term, I'm calling this RAaaS (Random Application as a Service) ;)

I modified my launcher to protect app creation, with a 500ms delay between them. The symptoms that I'm seeing go away.

I know I haven't given any actionable details: logs, payloads, etc, but I wanted to throw this out and see what folks think. If it seems like it may be an issue in Marathon and/or Mesos, let me know and I'll try to come up with a bash script or something to reproduce it.

I'm running on Marathon 0.7.6, as built by Mesosphere; against Mesos 0.21.1, also built by Mesosphere. 

Many thanks,
--cb

**Comment by cgbaker** [comment]
The following bash script illustrates the symptoms that I'm seeing: 

```bash
#!/bin/bash

genapp() {
read -r -d '' APP <<- EOM
{
  "id": "bridged-webapp-$1",
  "cmd": "python3 -m http.server 8080",
  "cpus": 0.5,
  "mem": 64.0,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "python:3",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 8080, "hostPort": 0, "servicePort": 0, "protocol": "tcp" }
      ]
    }
  }
}
EOM
echo $APP
}

APP1=$(genapp 1)
APP2=$(genapp 2)
APP3=$(genapp 3)
APP4=$(genapp 4)

echo $APP1 | curl -s -X POST -H "Content-Type:application/json" -d@- http://master-0:8080/v2/apps &
echo $APP2 | curl -s -X POST -H "Content-Type:application/json" -d@- http://master-0:8080/v2/apps &
echo $APP3 | curl -s -X POST -H "Content-Type:application/json" -d@- http://master-0:8080/v2/apps &
echo $APP4 | curl -s -X POST -H "Content-Type:application/json" -d@- http://master-0:8080/v2/apps &
```

**Comment by drexin** [comment]
Thanks for reporting this and the script, we'll have a look.

**Comment by kolloch** [comment]
Concurrent updates to the Group state are not handled properly in the GroupManager.upgrade method.

At the beginning of the method the current Group state is retrieved (look at the definition of the rootGroup val). This Group state contains AppDefinitions with the current port assignments and is used to compute unused ports by the assignDynamicAppPort method. The Group state is updated with the new port assignments and written back to the storage at the end of the method (groupRepo.store).

There is no logic to prevent inconsistent updates to the Group state if the update method is called concurrently. If the Group state is read in concurrent invocations of the method before any update, all invocations base their computations on the same group state. If we, for example, add AppDefinitions in these concurrent updates, the last udpate wins and we only see one of the AppDefinitions added to the Group state.

The UI still displays all applications, since not the group endpoint but the app endpoint is used to retrieve the list of applications. These are stored correctly except the incorrectly computed port mappings.

The original author of the upgrade method seems to have attempted to prevent concurrent updates by wrapping the whole method definition in a synchronized block. Yet the method returns a Future and most computations are performed asynchronously. Therefore, these computations are not covered by the lock.

**Comment by cgbaker** [comment]
Just tested against the 0.8.2-RC2 (d0ecfbc), saw that this is good along with a related issue on DELETE. Thanks a bunch!

**Comment by kolloch** [comment]
@cgbaker :+1: thanks for the thanks! We appreciate this.
