### ISSUE TITLE
Expose all /v2 App attributes in UI

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#124]
The Marathon web client should expose the following attributes when creating, viewing or modifying an application:

- [x] ports
- [x] constraints
- [x] container options
- [x] environment variables

**Comment by aatumanova** [comment]
@mlunoe @ConnorDoyle hey guys! Below is a stab at integrating docker container settings in our app config form, let me know what you think. Here's a summary of the changes:

- Tweak to form layout to help it feel simple: grouping form inputs and hiding optional and docker settings.
- Move command out of optional settings, because it's not completely optional (must have command and/or docker)
- Add docker container settings after optional settings.

Please check my copywriting for the docker privileges, not 100% if I communicated that setting correctly!

PSD: https://drive.google.com/open?id=0B6i94AxJ4LMQY01JbnpjVnpaWFU&authuser=0

![image](https://cloud.githubusercontent.com/assets/1326416/6154625/e8ab0d76-b1e1-11e4-9630-e2d7d5eceb27.png)

**Comment by ConnorDoyle** [comment]
Looking snazzy!

Anastasia, could we put this on invision to make commenting easier?

Thanks,
--
Connor

**Comment by aatumanova** [comment]
@ConnorDoyle good call, here you go http://invis.io/3A27E9VME!

**Comment by ssorallen** [comment]
:fireworks: :tada: :tada: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :tada:  :fireworks:

**Comment by mlunoe** [comment]
Thank you @aatumanova ! Looks great! :)

**Comment by drexin** [comment]
This is great, @mlunoe @aldipower when can I expect a PR for this? ;-)

**Comment by mlunoe** [comment]
This is supposed to be a workday assignment :)

**Comment by aldipower** [comment]
@aatumanova Look's really cool! :)
@mlunoe Yeah, good workday task.

**Comment by aatumanova** [comment]
@mlunoe I remember that Phil worked on this issue during his workday. Do you remember what happened with it?

**Comment by mlunoe** [comment]
Should we check off the checkboxes? Did the PR cover all issues?

**Comment by philipnrmn** [comment]
I think we can check off container settings and constraints, but not EVs. 

There's a further piece of work that needs to be done, which is making sure that [all available app fields](http://mesosphere.github.io/marathon/docs/rest-api.html#post-/v2/apps) are supported in this modal. For the moment we've implemented the design relatively faithfully in order to end up with something functional, but we need to consider how to represent things like dependencies.

**Comment by mlunoe** [comment]
In that case I think we should re-open this issue until it is implemented
