### ISSUE TITLE
Formalize adherence to semantic versioning

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1332]
In the past, Marathon releases have included unexpected breaking API changes, even in "patch" versions (e.g. `X.Y.Z` => `X.Y.{Z + 1}`).  We should formalize the distinction between patch and minor releases in terms of the allowed level of API breakage.

As a quick example, version `0.8.1` changed POST /v2/apps from an idempotent operation to return an error if  the supplied app id already exists.  This change arguably should have been signified in the release version.

**Comment by ConnorDoyle** [comment]
cc @cmaloney

**Comment by BenWhitehead** [comment]
0.8.1 also changed the default `Content-Type` for `GET /v2/apps/<task_id>/tasks` to `text/plain` from `application/json`.

**Comment by kolloch** [comment]
I like the intention of your proposal: Make breaking changes more obvious. Its execution is not always trivial, though.

Example 1: I guess the APP POST semantic was changed deliberately in #1180 and was mentioned in the change log. With a commitment to [semantic versioning](http://semver.org/), we would have bumped up the first number of the version triple: 1.0.0. I do not really like that because 1.0.0 usually signifies a major release and the change was rather minor. But of course, that would be consistent. Alternatively, we could have deferred a change what @ConnorDoyle and @drexin obviously perceived as an improvement of the API.

Example 2: The `Content-Type` change was probably done without thinking about clients that do not specify the `Content-Type` (which you should always do if you expect a specific one but that's a different issue). If you do not realize that you are breaking clients, it is hard to bump up the version.

We should make a serious effort to avoid breaking any _documented_ behavior. That includes good testing coverage of the documented behavior. Of course, that shouldn't be an encouragement to document less ;)

Yet, how should we handle, for example, further validation? In #1195 some invalid app definition is rejected that was accepted before. I argue that should be allowed without changing the second part of the version triple. Or what about #1329? In it very unlikely to break existing app definitions but in theory it could.

Every bug fix is a change in behavior and [breaks someones workflow](https://xkcd.com/1172/).

**Comment by bacoboy** [comment]
I got bit by this too.  The patch version lulled me into an expectation the change was backward compatible -- until my python marathon library freaked out.

I can understand not wanting to signify this as 1.0 ready by using 1.0.0 this time around, but perhaps until it goes 1.0 we use the minor version when API changes are happening just to warn folks (more than looking at the release notes that is).  A patch version should always be a 'I don't have to think about it' upgrade IMHO.

**Comment by kolloch** [comment]
I welcome your feedback for the pull request.
