### ISSUE TITLE
Why marathon throw an exception while occur a mistake of http event POST?

### ISSUE THREAD

**Issue by hyper-carrot** [mesosphere/marathon#1362]
As it said in title, when the http event POST has failed, this process will be stopped, and any callback url will not receive the event. Why not record the failure and continue to send the event to other callback url?

Look at the code: https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala#L52

May be I can change that. Do you have any suggestion?

**Comment by hyper-carrot** [comment]
My PR: https://github.com/mesosphere/marathon/issues/1362

**Comment by hyper-carrot** [comment]
The issue talked about this: https://github.com/mesosphere/marathon/issues/1362

**Comment by kolloch** [comment]
Hi @hyper-carrot ,

Thanks for your suggestion.

The POSTs to the different endpoints are performed asynchronously in Futures. Thus, any failures are not propagated to the caller of post. Actually, other than logging, the errors are not captured at all.

Throwing in onComplete does not make any sense, as far as I know since onComplete doesn't return a new Future which would be affected by the throw.

I will close this for now. Tell me if I misunderstood something or you have something to add.

**Comment by hyper-carrot** [comment]
OK, I see. Thanks. I'm eager to see the feature about the asynchronous POST.

**Comment by kolloch** [comment]
Hi @hyper-carrot ,

what do you mean with the feature of asynchronous POSTs? They look somewhat asynchronous to me ;)

Do you have a production issue you could describe that needs solving?

Thanks.

**Comment by hyper-carrot** [comment]
Hi @kolloch,

Production issue? OK, I think that I can describe the problem again. :)

The current code for the http event sending(for example, sending http event to Bamboo) is NOT fault-tolerant. Once it finds a wrong callback URL(for example, wrong formatted or inaccessible), it will throws a exception & interrupts the sending process. I wanted something else.

The one of the benefits of asynchronous sending is the fault will not be spread. This is my focus. Sure, I am also very happy to see the performance improvement.

Do my words convey my meaning to you?

**Comment by kolloch** [comment]
Hi @hyper-carrot ,

the current code is asynchronous -- even if the code might not look like that. Errors are logged but otherwise the code continues calling all callbacks.

I tested the following with the current master:

* started Marathon with callbacks enabled on port 8080
* started `python -m SimpleHTTPServer 9000`
* Registered various callbacks
  * `http POST http://localhost:8080/v2/eventSubscriptions?callbackUrl=http://localhost:9000/callback`(will get 501 from SimpleHTTPServer)
  * `http POST http://localhost:8080/v2/eventSubscriptions?callbackUrl=http://localhost:123/callback` (intentionally unreachable)
  * `http POST http://localhost:8080/v2/eventSubscriptions?callbackUrl=http://localhost:9000/callback2` (will also get 501 from SimpleHTTPServer)
  * and more
* Create an app

Result: I see errors in the Marathon log (expected) but I see all the POST invocations in the console of the SimpleHTTPServer.

So, if you have a setup that doesn't work, please let me know.

**Comment by hyper-carrot** [comment]
Hi, @kolloch 

I do the case again. But it's alright. I thought that the problem is about the order of callback url list. But I think wrong. Thank you for your patience. :+1 : )
