### ISSUE TITLE
Remove user credentials from Marathon command line

### ISSUE THREAD

**Issue by nborod** [mesosphere/marathon#1428]
Problem:
Currently Marathon allows to add HTTP user credentials (ID & password) via --http-credentials command line parameter. When the process is running anyone can easily see these credentials in the "ps" command output.

Proposed solutions:
1. Modify --http-credentials parameter once the process is started so it does not display in the "ps" output.
2. Read credentials from a file (preferred). This way more than one user can be defined.
3. Authenticate users against LDAP (even better).

Thanks
Nikolay

**Comment by WalterDalton** [comment]
I would vote for including number 2 here as a short term solution.  3 would be awesome, but I believe Marathon is going the route of plugins to do auth, so doing work on Marathon itself to provide this doesn't make sense.  However, #2 here, would make Marathon inline with how Mesos handles credential files and I would be very interested in this for the sake of short term usability of the http_credential field. (it's unusable at this time if you consider security at all as part of your platform)

**Comment by WalterDalton** [comment]
After exploring a bit more, I need to update my previous post.  In my testing if I supplied --http_credentials then it showed up in the command line (bad).  If I followed https://mesosphere.github.io/marathon/docs/command-line-flags.html  and did a ENV variable of MARATHON_HTTP_CREDENTIALS that still showed up on the command line.  As I reading the section on the website flags.  I noticed the docs recommended MESOSPHERE_HTTP_CREDENTIALS  I thought this was an error, but then I looked into the scripts that start Marathon and realized the way the MARATHON_ variables are parsed, they are put on the command line, but not MESOSPHERE_ variables, so I tried only the MESOSPHERE_ and it worked in such a way that the password did not show up on the command line, and still challenged the user.  

So a few points: 

1. This needs to be much more clear in the docs. Basically there needs to be a blurb specifically about the the need to MESOSPHERE_ rather than MARATHON_ in order to keep the contents of the variable off the command line.  

2.  I still recommend as I did above to use a path to secret file like mesos does. Marathon already uses the secret file TO authenticate to Mesos, why not do it here as well. 

3.  More work on the auth plugins!!! Stuff is coming along, but to be enterprise friendly, both the work and documentation needs to be flushed out here.
