### ISSUE TITLE
Limit number of revisions to store

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1464]
Currently, we store an infinite number of old versions for apps, groups and deployments. While it can be useful to keep some history (for example for rollbacks), this leads to problems.

In #1458 a user complains that the request to get all group versions always runs to a timeout error. In addition, we storage requirements for Marathon would just keep growing, especially if the app/group definitions change frequently.

I propose to limit the number of versions we keep and make that configurable with a default of 100.

**Comment by aquamatthias** [comment]
The marathon default is to not limit the number of versions to store.
It is highly recommended to limit the number of versions, since the current implementation accesses all the versions when there is an update. Use the command line option --zk_max_versions to limit the number of versions stored per entity.

**Comment by bobrik** [comment]
@aquamatthias what about sensible defaults?

**Comment by aquamatthias** [comment]
As the flag was introduced, we wanted to make that in a backward compatible manner - and that was/is unbounded. But it really leads to problems, so I agree, there should be a sensible default. I will make a ticket for this.
