### ISSUE TITLE
Marathon About page presents a confusing 'Name' which is not the framework name

### ISSUE THREAD

**Issue by lingmann** [mesosphere/marathon#1469]
On the Marathon about page a **Name** field is shown, which is the project BuildInfo.name (see InfoResource.scala and not the --framework_name. It is probably a good idea to either change or add a Framework Name to the Marathon about page. For example, here is a Marathon instance started with `--framework_name` set to `marathon-public`

![screen shot 2015-05-05 at 1 30 28 pm](https://cloud.githubusercontent.com/assets/33731/7482284/281b5e5e-f32b-11e4-82ec-69e47e4d8ec7.png)

**Comment by kolloch** [comment]
Probably still needs work in the UI (not verified).

**Comment by pierlo-upitup** [comment]
The newly introduced `framework_name` value is automatically shown within the **Marathon Config** fieldset. As this is part of the marathon-config list I would argue that it shouldn't be shown instead of the top-level "name" field. 
![screen shot 2015-06-29 at 18 27 18](https://cloud.githubusercontent.com/assets/1078545/8412786/817456a4-1e8c-11e5-8efe-f2de5203ce0c.png)

What do you suggest, @kolloch ?

**Comment by kolloch** [comment]
Maybe we should rename/remove "name" from the UI? It comes from the build info and is always "marathon". What do you think? @aquamatthias

**Comment by aquamatthias** [comment]
Yes. remove the static name.
