### ISSUE TITLE
Default Marathon UI colour scheme is not usable for colour-blind individuals

### ISSUE THREAD

**Issue by daniel-bryant-uk** [mesosphere/marathon#1499]
Hi,

During a demonstration of Marathon one of the audience members commented that the default colour scheme is not usable for colour blind individuals, as the green text/progress bars blend in to the grey background.

Can the default colour scheme be changed?

Best wishes,

Daniel

**Comment by kolloch** [comment]
Hi @aldipower / @philipnrmn , is that easy to do? What do you think?

**Comment by aldipower** [comment]
On the sunny side of code this is easy to do. Other question is what @ashenden or @aatumanova is thinking about this?

**Comment by aldipower** [comment]
AS @philipnrmn mentioned there shouldn't be any problem with the color blindness, we have enough contrasts.
So I've made some simulations with http://www.color-blindness.com/coblis-color-blindness-simulator/ .
And I can't detect any problem.
Maybe on a pretty bad beamer projection?

Normal:
![marathon-normal](https://cloud.githubusercontent.com/assets/859154/7583366/eb22317a-f894-11e4-80da-5f97fa7883c7.png)

Green blindness:
![marathon-normal_deuteranopia](https://cloud.githubusercontent.com/assets/859154/7583377/fd0acdde-f894-11e4-8406-1aa6e18ea17b.jpg)

Red blindness:
![marathon-normal_protanopia](https://cloud.githubusercontent.com/assets/859154/7583386/0ed5283e-f895-11e4-841d-037a586b008f.jpg)

Blue blindness:
![marathon-normal_tritanopia](https://cloud.githubusercontent.com/assets/859154/7583392/18847420-f895-11e4-8bb7-31aa10f6fbae.jpg)

Complete color blindness:
![marathon-normal_achromatopsia](https://cloud.githubusercontent.com/assets/859154/7583379/062c4564-f895-11e4-9b9b-7cd1e56c7515.jpg)


Normal with green text:
![marathon-text](https://cloud.githubusercontent.com/assets/859154/7583370/ef2aa9d2-f894-11e4-8540-80f278d96c74.png)

Text with green weakness:
![marathon-text_deuteranomaly](https://cloud.githubusercontent.com/assets/859154/7583397/2418d9e8-f895-11e4-91a3-1145b9780580.jpg)

Text with green blindness:
![marathon-text_deuteranopia](https://cloud.githubusercontent.com/assets/859154/7583402/2d7565a6-f895-11e4-9169-10ce51e19936.jpg)

**Comment by daniel-bryant-uk** [comment]
Thanks to all for the comprehensive responses. I'll ping this thread to the person who made the comment (who may not be around for a couple of days), and ask for further feedback. 

We were presenting on a large TV screen, which may have contributed to the feedback on the colour scheme?

**Comment by philipnrmn** [comment]
Thanks, we'd really appreciate their input. It might be useful in any case to offer a higher contrast mode, so we'll definitely have a think about what we can do here.

**Comment by AgentAntelope** [comment]
Hello, I'm the person in question. Viewing the interface in a better environment (iMac, rather than a tv screen across a room) I can indeed differentiate between the green and the grey. (For information, I have monochromatic vision, or complete colour blindness).

There are some issues with contrast as a differentiator. This works well when there are only two states, and those two states are known (in your examples, running and healthy.)

However I believe that health can be: healthy, unhealthy, running, staged, over capacity, or unscheduled, looking at the styling. I find it very difficult to believe that on a large project using many apps with varied states that contrast would be adequate to distinguish between all possible states. 

Here is an example: One build is healthy, one is staged, and one is over capacity. I would find it very difficult to discover this information without inspecting the styling, as the contrasts of the builds to one another is entirely relative.
![screen shot 2015-05-13 at 10 52 51](https://cloud.githubusercontent.com/assets/1962412/7608056/45d94170-f95e-11e4-8400-d794625c91f2.png) ![screen shot 2015-05-13 at 10 52 51](https://cloud.githubusercontent.com/assets/1962412/7608145/ca676cd2-f95e-11e4-8eb5-ef94d5db8dca.png)

**Comment by philipnrmn** [comment]
Hello, I see the problem. Thanks very much for taking the time to explain in such, this sort of feedback is really valuable to us. 

We'll feed this back to the design team. May I also ask what your preferred solution would be? Hatching on unhealthy progress bars, additional text, tooltips, or something else?

**Comment by AgentAntelope** [comment]
Text based solutions are always good; There's no risk of misinterpretation or need for a key. I'd prefer additional text over tooltips, so that it's possible to see an overview without needing additional action.

**Comment by philipnrmn** [comment]
OK, that makes sense. I'll give you a shout directly when we've got a solution ready. Thanks again :)

**Comment by pierlo-upitup** [comment]
@AgentAntelope thanks a lot for your valuable input. 

We have settled on a solution involving tooltips for each status segment for the moment – you can take look here: https://github.com/mesosphere/marathon/issues/1137#issuecomment-121544625

**Comment by AgentAntelope** [comment]
Looks good to me! Thanks for this :)
