### ISSUE TITLE
Marathon kills tasks before MinimumHealthCapacity is met

### ISSUE THREAD

**Issue by chriskite** [mesosphere/marathon#1570]
I have a 2 instance task with the following upgradeStrategy and healthChecks:

```
"upgradeStrategy": {
  "minimumHealthCapacity": 1
},
"healthChecks": [
  {
    "protocol": "HTTP",
    "path": "/",
    "portIndex": 0,
    "intervalSeconds": 10,
    "gracePeriodSeconds": 15,
    "timeoutSeconds": 10,
    "maxConsecutiveFailures": 3
  }
]
```

When I update this task to a new version (changing only the tag on the Docker image), Marathon launches 2 new tasks as expected. However, as soon as the new tasks are started, and before they have passed a health check, the old healthy tasks are killed. This leaves me with 0 healthy tasks even though my threshold indicates that I should always have 2 healthy tasks.

**Comment by chriskite** [comment]
Realized I wasn't testing this on the current version (0.8.1). Will try that release.

**Comment by chriskite** [comment]
I have confirmed that this issue still exists on 0.8.1. Even though I have requested 4 instances with a minimumHealthCapacity of 1, Marathon will replace healthy tasks with failing tasks when I deploy a new version, leaving me with just 1 healthy instance.

I don't have a good way to test this on the current master branch or the latest RC. Can anyone confirm this behavior or point me towards a good test environment?

**Comment by DustinChaloupka** [comment]
This seems to still be a problem on 1.2.0-RC6. We have an app that has 6 instances, minimum health capacity is set to 0.83 (keep 5 healthy instances) and maximum over capacity set to 0. ie Roll one app instance at a time and keep the cluster healthy (it's an elasticsearch cluster). The idea behind this was to follow ES's rolling strategy (because Marathon should wait on deploying the next one until the cluster is healthy) but this is pretty much impossible.

That was a specific example but being able to properly define upgrade strategies and have them work that way would be nice.

**Comment by jeschkies** [comment]
Could you please retry with Mesos 1.1 and Marathon 1.3 if that is possible.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2693. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
