### ISSUE TITLE
Marathon UI health check graphic "resets" infrequently during large rolling restart

### ISSUE THREAD

**Issue by dontrebootme** [mesosphere/marathon#1668]
When doing a rolling restart (1000 containers), the UI for app health clears all the green and turns grey for a short period of time. This happens infrequently but I've observed it multiple times today in testing.

If I click through to the app tasks list, I see many pages of healthy, but the summarized view seems to reset.
![UI1](https://cloud.githubusercontent.com/assets/1504683/8191815/301a9222-141f-11e5-9a9a-90673a7e19a3.png)
![UI2](https://cloud.githubusercontent.com/assets/1504683/8191816/327c7eae-141f-11e5-9e95-046bd5a52753.png)

**Comment by aldipower** [comment]
I've started 2000 tasks to check this.
I couldn't detect any anomalies also a review of the according UI code for the HealthBar didn't show up any failures.
It seems that there was no health information on the _application object_ for some reasons. The health informations for the tasks are bound to the different _tasks objects_. So this could reflect your recognized behavior.
We have some health properties on the application object we receive from the API:
```
tasksHealthy: 0
tasksUnhealthy: 0
tasksStaged: 100
tasksRunning: 900
...
```
It seems that ```app.tasksHealthy``` was 0, so the grey bar is a results of an unknown application health status.
@aquamatthias Do you have any ideas?

**Comment by aquamatthias** [comment]
Looks like a service problem: the task has the health status, but the aggregated app data does not reflect that.

**Comment by aquamatthias** [comment]
Hey @dontrebootme I tried to reproduce the problem, but was not able to do that.
Some background information:
- during a rolling restart, all tasks of an application get restarted
- the health check have to be performed for every new task
- until then the status is unknown --> grey
- if you have a lot of tasks (1000 in your case) this can take some time

In your screenshot I see the progress bar with a small amount of green and some tasks which are reported green as well. Hard to judge, if this is a problem.

Can you be more precise what exactly the problem is and how to reproduce? 
Thanks!

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2902. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
