### ISSUE TITLE
The size of state in Zookeeper is too large and continuously growing up

### ISSUE THREAD

**Issue by mingqi** [mesosphere/marathon#1683]
We are using Marathon 0.8.1 and Mesos 0.21. There are currently around 400 apps running in Marathon. We found Zookeeper's heap memory is as large as 2GB and keep growing. After investigation by  Zookeeper tool zkCli.sh, we think most of data is from Marathon. Below is the detail information:

*  path /marathon/state has 20903 child nodes. We have only 400 apps but why 20903 nodes in /marathon/state. I suspect that Marathon didn't remove deleted application data.
```
[zk: localhost:2181(CONNECTED) 0] ls /marathon
[state, leader]
[zk: localhost:2181(CONNECTED) 2] stat /marathon/state
cZxid = 0x100000023
ctime = Fri Mar 27 04:15:46 UTC 2015
mZxid = 0x100000023
mtime = Fri Mar 27 04:15:46 UTC 2015
pZxid = 0xc000004fae
cversion = 1054479
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 0
numChildren = 20903
``` 
* two types of node under /marathon/state: app:xxxx and group:xxxxx.
* the size of app:xxx node usually is around 500 bytes
```
[zk: localhost:2181(CONNECTED) 4] stat /marathon/state/app:47ab1ce5-cebd-48e5-bcf4-7f3d05f1f7b3:2015-06-12T02:07:02.417Z
cZxid = 0xbd0004c068
ctime = Fri Jun 12 02:07:08 UTC 2015
mZxid = 0xbd0004c06a
mtime = Fri Jun 12 02:07:08 UTC 2015
pZxid = 0xbd0004c068
cversion = 0
dataVersion = 1
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 462
numChildren = 0
```
* the size of app:xxx node usually is 250 KB
```
[zk: localhost:2181(CONNECTED) 5] stat /marathon/state/group:root:2015-06-11T06:51:08.275Z
cZxid = 0xbd0004933a
ctime = Thu Jun 11 06:51:11 UTC 2015
mZxid = 0xbd0004933a
mtime = Thu Jun 11 06:51:11 UTC 2015
pZxid = 0xbd0004933a
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 252923
numChildren = 0
```
* group:xxxx nodes looking majority

I have questions for this issue:

* does Marathon remove data from zookeeper when application was deleted? Do Marathon have a options to control it?
* Does Marathon support other state other than Zookeeper? I remember a document said Marathon can store data in Mesos native storage, is that true?
* what's the group:xxx data?

thanks

**Comment by aquamatthias** [comment]
Hey @mingqi 
A lot of questions - I try to answer:

> does Marathon remove data from zookeeper when application was deleted? Do Marathon have a options to control it?

If you delete an application from Marathon, it also gets deleted from zookeeper. Please note, that every change to every application creates 2 new objects in zk: the version of the app and group at that point in time. There is an option to control how many versions are allowed `--zk_max_versions`. The default in 0.8.1 is no restriction. You should definitively set this to a reasonable size, depending how many versions you want to keep (e.g. 3). Note: setting this property will not delete anything until you change the related entity.

> Does Marathon support other state other than Zookeeper? I remember a document said Marathon can store data in Mesos native storage, is that true?

Until version 0.9.0 Marathon used the Mesos State abstraction (http://mesos.apache.org/api/latest/c++/interfaceorg_1_1apache_1_1mesos_1_1state_1_1State.html)
That is a native interface with different storage provider. One of them (the default) is zookeeper. There is also a LevelDB and an InMemory engine. Since the state abstraction caused a lot of trouble, we decided to move away and use native java/scala bindings. It is on our roadmap to provide different storage solutions and make this configurable. Feel free to open an issue for that.

> what's the group:xxx data?

The stored group. group:root is the current group. group:root:TIMESTAMP is the versioned group.
You can remove all versions of the group if you like - they are there to go back in time to that version.
the same applies for app:APPNAME:TIMESTAMP.

If you have 400 applications and more then 20k zk objects, you have a lot of versions. As suggested use the `--zk_max_versions` flag to control and remove the unnecessary versions. I will close this ticket. Feel free to reopen, if there is a point missing.

**Comment by mingqi** [comment]
Yesterday I tried to add --zk_max_versions flag and restart Marathon, but Marathon failed to start up. Finally I removed --zk_max_versions flags and restart again. I'm not sure whether is related to --zk_max_versions.  Another wired things was we found some application (not application versions) was deleted from Marathon. The child nodes number of /marathon/state decrease to 19626 today.
