### ISSUE TITLE
Add --hostname-detection, Mesos IP detection

### ISSUE THREAD

**Issue by cmaloney** [mesosphere/marathon#1800]
This parallels https://issues.apache.org/jira/browse/MESOS-2902 and is motivated by the same case.

Any code we run on every host has a chance to go wrong on every host. We also like calling things directly rather than through wrapper scripts (Makes it more obvious what is going on, easier to debug).

As such we don't want to
1. add a wrapper script
2. Use bash substitution to do the same sort of thing (this is really ugly to do in systemd, and is effectively the same as writing a wrapper script, although a really simple one).
3. Write another script which stores the value into a magic location than have marathon pull it back out. That makes it so that it is impossible to track where the value came from.

**Comment by aquamatthias** [comment]
@cmaloney: Can you provide an example script showing the usage?
For simplicity I would recommend something like:
```
$> ./hostnamescript.sh 
IP=1.2.3.4
HOST_NAME=foo.bla.com
```
that can be parsed easily or to use json for this.

We have multiple options, where you can set hostnames:
```
--hostname - The advertised hostname stored in ZooKeeper so another standby host can redirect to this elected leader
--http_address - The address to listen on for HTTP requests
--https_address - The address to listen on for HTTPS requests.
```

For backwards compatibility I would not change the behavior of this settings.

**Comment by rasputnik** [comment]
I don't understand what's hard about passing in an --ip flag explicitly? 

It's nice and explicit and trivial to template with any CM system you're likely already using to deploy Mesos itself.

Conversely,  auto-detection seems a bit opaque.

**Comment by cmaloney** [comment]
We can't reliably pass it in a large portion of the environments we run in. We can almost always in those environments ask something what the IP is once a machine is up (The AWS Metadata service, Chef/Puppet/Salt/Ansible, etc). That script is very environment-specific, and provided as a requirement for installing "DCOS" on that particular cluster / network setup. In no case do we want to auto-detect, too many unique features of setup (IPs not attached to machines directly, Many NICs on a machine, virtual bridge devices). Having marathon run the script makes it really easy to trace how the value is captured and passed along rather than assuming it lives in a magic file created before we start marathon. A wrapper script which does the same thing but isn't coded into Marathon is feasible, but then we're basically just making a proprietary extension of our standard Marathon init.

**Comment by cmaloney** [comment]
@aquamatthias: Note we can't reliably get hostnames which are resolvable /  shareable in a number of the environments we need to ship. We only have IP addresses. At least one of the environments we are running in have no DNS (outside the cluster mesos-dns) whatsoever.

What I currently have been doing / building as the Mesos `--ip-detection` is:
```
$>/opt/mesosphere/bin/detect_ip
10.0.0.1
```
The guarantee is that the script only outputs the IP (Although in practice IPv4 or IPv6, and may have leading / trailing whitespace which should be stripped).

There is also a:
```
$>/opt/mesosphere/bin/detect_hostname
vm1
```
The hostname should only be used to display to users, not have machines find each other. It is not globally routable / resolvable in the majority of the environments at this point in time.

The exact path / location of the scripts in our environment I'm still working out.

**Comment by discordianfish** [comment]
@cmaloney Maybe I miss something but I don't understand why having all those services run some scripts to get hostname/IPs is better than write env files from the script. I already read https://issues.apache.org/jira/browse/MESOS-2902 after being surprised that mesos itself runs the script.
I think both a wrapper file or writing a env file dynamically are better options. Have services like marathon execute some scripts isn't only added complexity but also a potential attack vector (what if the script is doing evil things? what happens if it returns unexpected values) and is less obvious/explicit from a ops perspective.

A shell wrapper script would use exec after getting the IP, so no problem with process management. Looking at the script makes it obvious how it gets the IPs etc (vs having to look into marathon code).
But I would probably just have the IP detect script write a EnvironmentFile for marathon: The ip detect script could be triggered by network changes so it also catches that and simply update one global env file which can be used by all services that need to know the hosts IPs etc or it could update a env file in the ExecStartPre script.

**Comment by cmaloney** [comment]
@discordianfish: @lingmann and I just spent most of a day debugging a cluster because we wanted to use the ip detect stuff, the script was broken, and output a empty IP address.

For some programs which we wrote wrappers for, it passed in a empty --hostname flag, which means the program would try to start than quickly fail because of an error parsing command line flags.

For others (marathon) it didn't see the environment variable, tried guessing it's IP, and got it _sort_ of right. So things _sort_ of sometime worked.

For Mesos, mesos didn't see the environment variable, so it tried guessing it's own IP, guesssed horribly wrong, and we could only tell why things werent' communicating by digging wayyy into the logs and noticing that things are trying to connect to 127.0.0.1 instead of the IP address that we want.

The whole goal here is that we want the IP address to be pluggable. If I don't specify it correctly, I want a hard error. If I don't specify it at all, I want a hard error. Setting environment variables and then having a program scoop them up and fallback if it doesn't see them isn't going to do that. Calling a function, and asserting it's output matches exactly what you want is going to do that, and gives us a nice testable (both the script, and the integration) unit.

I don't want to write the IP detection scripts over and over again in every language of every componenet, so instead we use a very standardized easy to call ABI boundary of exec / running a program,  (you call this script, it outputs a binary string in a very particular format). That is a stable API, which is callable from every language I know of, and much easier to work with and maintain than "here's the bash version, here's the python version, here's the java version, here's the C++ version, ...". It's also much simpler than loading any sort of .so in terms of programming.

**Comment by discordianfish** [comment]
> @discordianfish: @lingmann and I just spent most of a day debugging a cluster because we wanted to use the ip detect stuff, the script was broken, and output a empty IP address.

Maybe marathon should error out instead of trying to be smart if you set non/empty IP?
But I don't see how it matters if the empty IP comes from a env var, config option or command it calls.

> For some programs which we wrote wrappers for, it passed in a empty --hostname flag, which means the program would try to start than quickly fail because of an error parsing command line flags.

Sounds reasonable but I don't see how it's different with a script it would try to call which fails.

> For others (marathon) it didn't see the environment variable, tried guessing it's IP, and got it sort of right. So things sort of sometime worked.

Can we agree that guessing it's IP is bad? I think it should either require the operator to specify an IP or have one very clear way to determine it.

> For Mesos, mesos didn't see the environment variable, so it tried guessing it's own IP, guesssed horribly wrong, and we could only tell why things werent' communicating by digging wayyy into the logs and noticing that things are trying to connect to 127.0.0.1 instead of the IP address that we want.

If troubleshooting took so long for such obvious issue, we should IMO rather improve that. We should have an easy way to see what in a cluster works and what doesn't, starting with a easy way to get a list of servers and their IPs.

> The whole goal here is that we want the IP address to be pluggable. If I don't specify it correctly, I want a hard error. If I don't specify it at all, I want a hard error. Setting environment variables and then having a program scoop them up and fallback if it doesn't see them isn't going to do that. Calling a function, and asserting it's output matches exactly what you want is going to do that, and gives us a nice testable (both the script, and the integration) unit.

I think we completely agree on the goals here, just not on the implementation. I still don't see how it's harder to test / debug if the IP is passed to the mesosphere services externally. All you're arguments are valid but concern the general error handling. The ExecPre approach I used for now isn't a good option either, I agree. But IMO we should take a step back to figure out what 'runtime configuration' we need and how we handle it. I could imaging having a dedicated systemd unit running a script to gather such config and write it to a env file. All services that require such configuration can depend on the services and read the env file. To address you concerns regarding debugging, I would simplify/remove the guessing logic from the mesos services.

> I don't want to write the IP detection scripts over and over again in every language of every componenet, so instead we use a very standardized easy to call ABI boundary of exec / running a program, (you call this script, it outputs a binary string in a very particular format). That is a stable API, which is callable from every language I know of, and much easier to work with and maintain than "here's the bash version, here's the python version, here's the java version, here's the C++ version, ...". It's also much simpler than loading any sort of .so in terms of programming.

I don't see why we would need those scripts in all languages. On contrary, you're proposing to adding the functionality of executing external commands to read this one config option into various services written in various languages where in each case it introduces a new failure mode and doesn't support further possible configuration options that might be required.

**Comment by cmaloney** [comment]
I would note at this point the lifetime effort to implement and maintain this feature is probably less than what we've spent arguing about it. A --hostname-detection flag which runs a script has two (three if you care about malicious hostname detection programs) possible error cases. Writing a service file which writes the value to a file, then starts marathon telling marathon to start that file has a lot more. Writing custom wrapper scripts around marathon which are proprietary means we are effectively extending and forking the init system of Marathon. Over time the custom wrapper scripts learn all the quirks of operating / managing Marathon since that is easier to update and change than Marathon. Anyone seeking to run Marathon in production re-writes it. A little bit of extra code in marathon to prevent every team using marathon from writing the equivalent code in a wrapper bash seems like a large net code saving to me... The notion of "You ask something" what the right value is seems to be a very standard approach, and solves the case both of "We want to read the values from a standard common file" and "we want to compute it / ask the config management tool / etc".

Making the error messages better in the current case is really, really hard and actually impossible in some of the current cases (The code can't detect two services were writing to the same file and overwrote eachother but write out some slightly different variables). We can't use systemd dependencies to make something happen "before" all the other things because of http://unix.stackexchange.com/questions/213185/restarting-systemd-service-on-dependency-failure. We could write into every unit "don't start until this file exists" checking logic... With the current approach I can't tell if I got something write without running it end to end "Did I get the bash escaping right on this line so the heredoc that writes the service unit file fills in these variables but not those ones, then the  two layers of quotation do their right thing after getting parsed by bash vs. systemd substituting the variables?". We can't remove the guessing logic for Mesos or Marathon for compatibility reasons. Making another completely seperate flag to disable it is much harder than just making a simple way to detect it which is easy to tell if it goes wrong.

We could work on defining a standard interface where we say "here is the IP to use". The ip detection script in that case just uses our custom code to read the value from the standard location. We aren't forcing our idea of canonical configuration onto every user of Marathon. Every system adminsitrator has a different idea of what ideal is and where the canonical config should live becuase of their operating constraints. Running a bit of code to load or generate it from wherever you want is about as agnostic as it gets I think...

**Comment by discordianfish** [comment]
Every administrator can write config files and I think this is the most common way to configure which IPs something should use. You said 'The notion of "You ask something" what the right value is seems to be a very standard approach', I can't think of any service every that shells out to determine it's IP address.
However this gets solved, I still believe that having a config option (flag/file) is most common, straight forward and easy to understand. If we have trouble to reliable manage such config in DCOS (I believe you if you say it's hard with systemd, you have more experience with that), than this is a issue we need to address.

**Comment by cmaloney** [comment]
IP addresses of a machine are attributes of the machine you are running on, not the configuration of the machine itself. They are generally attached via DHCP or a host inventory database. When the physical machine is unplugged and moved, or connected / disconnected from different networks we aren't changing the machine's core configuration. The software shouldn't need to be deeply reconfigured to handle that IP addresses are attached to machines. 

moves 

They change when the physical machine moves or connects / disconnects from different networks. Configuration tells us how to 

I see as an attribute of the host we're running on. Whether the canonical store of that attribute

**Comment by kolloch** [comment]
Hey,

forking processes from a Java VM under Linux traditionally is not without problems. I don't know if that improved in recent years. e.g. look at:

* https://gist.github.com/pmahoney/1970815
* http://www.oracle.com/technetwork/server-storage/solaris10/subprocess-136439.html

What is more, the IP autodetect script has its problems as well. I just ran a problem with dcos-mesos-master using the detect_up script in the DCOS image under vagrant: https://mesosphere.atlassian.net/browse/DCOS-3209

Part of the problem is that we do not only need to set the IP we are binding to but also some other related parameters. I really feel that we should provide a startup script that deals with setting all these options if they an autodetect script is provided.

**Comment by cmaloney** [comment]
I'm familiar with the fork()/clone() system call problems, Joris can talk
about them at length (When you are writing a database which intentionally
is using all the RAM in the machine to cache data for quick access...).
We're talking about one fork at application startup before very much is
initialized which means the application shouldn't have a ton of state at
that point...

The Vagrant being broken is a separate bug. In that I updated the
configuration of the various cloud providers to not have our legacy
config + the new config for mesos having added the flag. It wasn't caught
when the rest of the changes went in because we don't currently have an
integration test for that vagrant to make sure basic functionality is
working (https://mesosphere.atlassian.net/browse/DCOS-3213). At least it
gave a nice clean error message about why it didn't work, rather than
failing with no sane error message in some use cases (It fails every time).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3207. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
