### ISSUE TITLE
We need to better document behaviour of PUT /v2/apps/{appid}

### ISSUE THREAD

**Issue by surdy** [mesosphere/marathon#1822]
The documentation for PUT /v2/apps/{appid} (https://mesosphere.github.io/marathon/docs/rest-api.html#put-/v2/apps/{appid}) mentions that "Currently running tasks are restarted" but according to my understanding that is not always true because its smarter than always restarting the current tasks. Exceptions being(as per my understanding):
1) When scaling up the app without changing anything else
2) When doing a PUT with exact same add definition

It would be useful to document the exceptions in the documentation

**Comment by srikanth-viswanathan** [comment]
Currently, the API returns 200 in both cases. Should it be changed to return something else given the request didn't actually do anything? Currently, the caller is none the wiser considering 200 is also returned after a successful upgrade.

**Comment by dkesler** [comment]
I believe that there are cases where effectively identical app definitions can in fact cause restarts (at least in 0.8.1), but I also think they don't always work due to a race condition. Specifically, I've been trying to track down the cause of stalled deployments in our environment and one possibility was these weird empty deploy plans that I was seeing.

Sample (abbreviated) log traces:
```
Jul 20 16:57:02 qa3-mesos-master3 marathon[5462]: [2015-07-20 16:57:02,688] INFO Compute DeploymentPlan from 
...
Group(/,Set(AppDefinition(/<app name>,None,Some(Vector()),None,Map(), ..., 2015-07-15T18:29:14.000Z)),Set(),Set(),2015-07-20T20:49:45.000Z), 
...
to
...
Group(/,Set(AppDefinition(/<app name>,None,None,None,Map(), ..., 2015-07-20T20:57:01.000Z)),Set(),Set(),2015-07-20T20:57:01.000Z), 


Jul 20 16:57:02 qa3-mesos-master3 marathon[5462]: [2015-07-20 16:57:02,947] INFO Deploy plan:DeploymentPlan(2015-07-20T20:57:01.000Z, (Step(List(Restart(App(/<app name>, None))))))) with force:false (mesosphere.marathon.MarathonSchedulerService:92)
Jul 20 16:57:03 qa3-mesos-master3 marathon[5462]: [2015-07-20 16:57:03,862] INFO Deployment acknowledged. Waiting to get processed: DeploymentPlan(2015-07-20T20:57:01.000Z, (Step(List(Restart(App(/<app name, None))))))) (mesosphere.marathon.state.GroupManager:142)

Jul 20 16:57:03 qa3-mesos-master3 marathon[5462]: [2015-07-20 16:57:03,912] INFO Compute DeploymentPlan from 
...
Group(/,Set(AppDefinition(/<app name>,None,Some(Vector()),None,Map(), ..., 2015-07-15T18:29:14.000Z)),Set(),Set(),2015-07-20T20:49:45.000Z), 
to
...
Group(/,Set(AppDefinition(/<app name>,None,Some(Vector()),None,Map(), ..., 2015-07-20T20:57:01.000Z)),Set(),Set(),2015-07-20T20:57:01.000Z)

Jul 20 16:57:04 qa3-mesos-master3 marathon[5462]: [2015-07-20 16:57:04,308] INFO Computed new deployment plan: DeploymentPlan(2015-07-20T20:57:01.000Z, ()) (mesosphere.marathon.upgrade.DeploymentPlan$:246)
```

You can see that the initial computation of the deployment plan schedules the app for a redeployment because the definitions are different.  It seems like it's due to the Some(Vector()) instead of None in the definition.  (There are some other minor differences like Vector instead of List that I cut out).  When it recaculates the deployment plan (I don't understand why it does, but it recalculates it 3 or 4 times for every deployment apparently), the None has been replaces with an empty vector in both the from and the to, which apparently causes them to be equal.  

Sometimes the app seems to restart successfully when this happens.  Other times it results in a deployment plan with no steps, no tasks ever created, and no further entries in the logs about it.  However the UI will show the deployment ongoing, /v2/deployments shows the deployment plan with the original restart step, and further deployments of the app are blocked until you stop/rollback the deployment.

**Comment by dkesler** [comment]
Regarding my above comment, the behavior I was seeing is apparently because we were using POSTs instead of PUTs.  Oops.

**Comment by Raffo** [comment]
Documentation for PUT definitely need improvements, +1. To me, it's not immediately clear what can be used with POST. Also, a swagger (http://swagger.io/) representation of the API would be nice.

**Comment by kolloch** [comment]
Hey @Raffo, +1 to your comments. If you have spare cycles, please coordinate with us and help us out!

https://mesosphere.github.io/marathon/docs/contributing.html

**Comment by Raffo** [comment]
@kolloch It might be a good idea, I was already planning to contribute some piece of code, but the current documentation needs help too. Should I open an issue to request for a swagger representation of the API? kubernetes has a very good one and I think that marathon's API is not too big to succeed on doing this.

**Comment by solarkennedy** [comment]
Re: swagger, there are now RAML descriptions of the API: https://github.com/mesosphere/marathon/tree/master/docs/docs/rest-api/public/api/v2/

**Comment by rrichardson** [comment]
What might also be nice to have in the documentation is how to achieve the update behavior when the app.json hasn't changed.   I am attempting to implement continuous deployment with drone, so I have generated a new docker image with the latest code, but when I PUT.. force=true,  Marathon opts to do nothing with a deployment plan of NO STEPS.  What is the way to achieve my intended behavior?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3104. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
