### ISSUE TITLE
DELETE /v2/groups removes everything

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1823]
I think it should at least require `/v2/groups/` (notice `/` at the end).

**Comment by ashishgandhi** [comment]
Also this behavior seem to not be documented on https://mesosphere.github.io/marathon/docs/rest-api.html.

**Comment by kolloch** [comment]
@ashishgandhi we welcome PRs that improve our documentation!

@bobrik Why is it important? What did you think it would do?

**Comment by bobrik** [comment]
@kolloch elasticsearch folks were thinking that removing all data can be useful too. It turned out that people do stupid things from time to time (like forgetting to set group to delete) and removing everything is somewhere at the end of list of things people want to do. Let's at least require `/` at the end of path. I can't see a reason not to require it.

https://www.elastic.co/guide/en/elasticsearch/reference/1.6/indices-delete-index.html

**Comment by air** [comment]
1. All API functions must be documented, especially nuclear ones like this. Our inline UI docs are a little better - they acknowledge that you can DELETE the endpoint /v2/groups - but don't explicitly mention that a root delete will destroy all content.
1. There's apps/groups asymmetry in that [DELETE /v2/groups deletes all groups](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/v2/GroupsResource.scala#L168), but [DELETE /2/apps isn't supported](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala#L167).

Actions
1. Document the API behaviour
2. It still seems risky to expose an endpoint this destructive without a guard. What if the `DELETE /` required a `confirm` variable to be passed before it took action?

**Comment by schneidexe** [comment]
I would suggest to actually block this call at all the same way like ```DELETE``` on ```/v2/apps/``` or ```/v2/apps```. It happened already 2-3 times that people here undeployed the whole dev cluster with all apps. There is little use case in deleting everything from marathon intentionally as @bobrik pointed out but the risk of doing it accidentally is quite high:
* copy & paste from POST command and testing script to early ;)
* happened to me yesterday: prepared ```curl``` command on console til the point of .../v2/groups then copy & paste group path from GUI, but due to HTML formatting it had a newline in front... well, you can guess what happened
* I guess there a more stories and confessions like this

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3395. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
