### ISSUE TITLE
UI Enhancement: Add column for number of times an app failed in its current form

### ISSUE THREAD

**Issue by srikanth-viswanathan** [mesosphere/marathon#1842]
When an app crashes on mesos, marathon re-launches it. It would be useful to have the number of past app failures as a column on the marathon UI so we could tell immediately if there was a problem.  Currently, one has to go to the mesos UI and check for KILLED tasks.

**Comment by gkleiman** [comment]
Our latest release candidate (v0.10.0-RC3) contains changes to the UI that allow you to see whether an App is delayed because of recent failures and to even reset that back-off delay.

You might find this helpful, even though it is not exactly what you describe - if you disable the back-off delay, you still can't easily find out whether an app is failing or not.

**Comment by pierlo-upitup** [comment]
cc @air @aquamatthias

**Comment by air** [comment]
Could we please post a quick screenshot when referring to UI changes? Would help get reviews/comments in quicker. Thanks

**Comment by kolloch** [comment]
In #1951, we propose to deal with this problem by showing information about the mean/median task life time and the duration since the last manual application restart.

A simple absolute task failure counter since the last manual application restart is good, too, but always has to be seen relative to the last manual application restart and the number of tasks running. If our app is 10 minutes old and has a target of 10 instances and there are already 50 task failures, we most probably have a problem.

If the app was last restarted two weeks ago and it has 10,000 instances as its target, 50 task failures are most likely not a problem.

**Comment by pierlo-upitup** [comment]
From the  `0.11.0` [release notes](https://github.com/mesosphere/marathon/releases/tag/v0.11.0):

> A new tab is available in the application detail view. It displays the most recent changes to the application configuration, the most recent task failure, and the relevant statistics.

Closing this issue as it's at least partially addressed by `0.11.0`.
