### ISSUE TITLE
Marathon deploy the wrong docker version to slave

### ISSUE THREAD

**Issue by huangyg11** [mesosphere/marathon#1884]
I deploy my app with jenkins - mesos(marathon) - docker. 

Recently, I find marathon deploy the wrong docker version to slave from time to time. 

Say I build docker version 50, and post json to marathon.  The configuration on the marathon web UI is correct which indicate the version of deployed docker is 50.

But when I login into every slave to check the version, I find some slave are running the version of 45. When I make some trivial change to the app code and build, deploy again, it behave normal again, with the version of 51.

And the problem may appear in the version of 54.

It has been running normally for one month until recently.

How can I locate the problem?

The version of marathon is  0.8.1.

**Comment by xiaods** [comment]
Based on intuition, we need capture the slave's log to inspect the docker run process.

**Comment by kolloch** [comment]
Hi @huangyg11,

if you say "docker version", do you mean the version of the docker image that you deploy? It sounds like you are actually hitting the docker cache which gives you old versions for your image.

E.g. are you explicitly specifying the image version in your app definition like this?

```javascript
{
  /* ... */
  "container": {
    "type": "DOCKER",
    "docker": {
      /** you should specify your version explicitly after the colon */
      "image": "myregistry/myimage:myversion", 
      /* ... */
    },
    /* ... */
  },
  /* ... */
}
```

Otherwise you can also forcing docker to retrieve the latest version with [force pull](https://mesosphere.github.io/marathon/docs/native-docker.html#forcing-a-docker-pull) and then manually trigger a redeploy in Marathon when a new version is available.

Generally, specifying your version explicitly is much preferred, though.

Does that solve your problem? Please reopen and provide more information if it doesn't.
