### ISSUE TITLE
Marathon should have a finite bound on how long to wait for offers before invoking reviveOffers

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1935]
There could be a case where the `reviveOffers` message is not received, in which case Marathon should not wait forever to get offers (because they will never come). See #1933.

**Comment by ConnorDoyle** [comment]
CC @benh

**Comment by kolloch** [comment]
Good thinking! Thanks.

So, basically, if we invoke reviveOffers and do not receive any offer in a configurable time span, we invoke it again?

**Comment by kolloch** [comment]
This should be made available for 0.9.* to 0.11.*

**Comment by kolloch** [comment]
I think it is impossible to implement this correctly: If we receive offers after we send the `reviveOffers` message, we cannot know if that is a consequence of `reviveOffers` or a coincidence.

Furthermore, @rukletsov cannot think of any case where the `reviveOffers` message gets lost and the filters remain:

* When the Mesos master fails over, all filters are dropped AND Marathon issues a `reviveOffers` as part of the reregistration callback.
* When the connection to the Mesos master fails and is reestablished, we get a reregistration callback.
* When we get a rate limiter error, the Marathon process is killed by the driver.

Just in case, that there are still some other cases where the `reviveOffers` message is lost, they are hopefully rare. Thus, it might be acceptable to use a value for `--reject_offer_duration` that prevents  resource starvation but still is low enough for the rare case. E.g. 120s if you have 60 frameworks.

@ConnorDoyle & @benh Am I missing something crucial? Otherwise, I would close this issue.

**Comment by kolloch** [comment]
@benh, please reopen with more information if you disagree.

**Comment by ConnorDoyle** [comment]
I'll bite!  There's no ack sent from the master for the `reviveOffers` message.  For this reason, when Marathon revives, it should remember that it needs to revive again _until it observes that the `resourceOffers` callback is invoked_.  Essentially, a resource offer can be used as confirmation that `reviveOffers` was received.

This would give clearer semantics than what was originally proposed (bound offer inter-arrival time before we spuriously revive).  @benh and @jsancio might have additional opinions.

**Comment by kolloch** [comment]
In my opinion, your suggestion could lead to a situation where a `reviveOffers` message gets lost and not be resent. Thus, it doesn't solve the problem.

@ConnorDoyle As I wrote above:

"I think it is impossible to implement this correctly: If we receive offers after we send the reviveOffers message, we cannot know if that is a consequence of reviveOffers or a coincidence."

Maybe I should have been more clear: If we call `reviveOffers`, we do not control about how it takes to handle that message by the master. Therefore, if the `resourceOffers` callback is called directly after the `reviveOffers` call, it might not be a reaction to the `reviveOffers` call. In fact, the master might not even have seen the `reviveOffers` message yet.

We cannot establish a causal relationship between our `reviveOffers` call and any offers we receive. (Or at least I do not know any way to do that). Thus, we cannot implement this.

Let's talk directly about that if you think that I am missing something crucial.

**Comment by rukletsov** [comment]
@ConnorDoyle: we can still receive offers if we previously set filters. In order to use `resourceOffers` as an implicit ack for `reviveOffers`, you will have to implement a pretty complex logics: check the `slaveID`, compare the size of the offer with filter you set previously and so on. I agree with @kolloch that it's not a very reliable mechanism.

There is however one more thing. What are the cases when the `reviveOffers` does not reach the Master, given there are no failovers? Doesn't the TCP stack guarantee the message delivery or fail? @sambatyon suggests that in current implementation we silently close the socket on a network blip. Moreover, he pointed out that this behaviour should change once we move to the new HTTP API, where for every request we will get a response.

**Comment by kolloch** [comment]
@rukletsov diskussed this with @benh and there concluded:

* with the new HTTP API there is explicit message acknowledgement and messages should not get lost anymore (at least not without a reregistration callback)
* with the old protocol, lost messages are possible but this should be exceedingly rare

Their proposed work around would be to `reviveOffers` periodically as long as we need to schedule tasks. This, again, could lead to resource starvation for other frameworks if the interval is too short. Therefore, it should probably be configurable.

To avoid introducing yet another knob we have to tune, I would rather implement my suggestion above, that you decline offers with a filter in the order of minutes and not days. According to @rukletsov this would also solve the problem.

Closing...
