### ISSUE TITLE
Problem with concurrent application deployment 

### ISSUE THREAD

**Issue by dlyub** [mesosphere/marathon#1994]
Components:
Marathon 0.9.1
Mesos 0.23.0
Docker 1.7.1

Config:
3 masters + 3 slaves

Issue:
When deploying 10 applications in parallel most of them appear to get stuck in the "Deploying" state. If one of the applications get destroyed all the other ones immediately switch to "Running" state, but some of the containers still end up not getting deployed properly.

Workarounds we had found so far are deploying applications ~30 sec apart or pre-fetching docker images to the slave machines. When that's done all the apps start reliably. 

Each of the slaves has enough resources to run all of the containers, so hardware should not be an issue. 

I'd appreciate any leads and ideas.

Thank you!

**Comment by aquamatthias** [comment]
Hey @dlyub thanks for reporting this.
I see several issues here:
1) Apps are stuck in deployment. What means stuck? How long did you wait? What does the mesos console says?
2) If you kill one deployment (do you mean that by destroying an application?) the other deployments are finished immediately but the deployment has not been finished. Correct?
3) If you pre-fetch resources, everything works - so that looks like a docker related problem

Can you provide the logs (Marathon logs, mesos slave logs) for this situation?

**Comment by dlyub** [comment]
@aquamatthias I noticed yesterday that there were newer versions of Marathon and Docker and decided to try them. Newer Marathon has not made a difference but changing Docker to 1.8.1 resolved the problem.
