### ISSUE TITLE
Marathon UI keeps complaining about invalid constraint even after the constraint has been removed

### ISSUE THREAD

**Issue by surdy** [mesosphere/marathon#2057]
Observed in DCOS CE on AWS (Marathon version 0.8.2-SNAPSHOT)

Steps to reproduce : 
1. Click `+ New App`
2. Fill in the details for the app, except enter invalid constraints
3 Press `Create App`

You would now see an error like 
```
Comma-separated list of valid constraints. Valid constraint format is "field:operator[:value]".
Invalid constraints format or operator. Supported operators are `unique`, `like`, `unlike`, `cluster`, `group_by`. See https://mesosphere.github.io/marathon/docs/constraints.html.
```

4. Now clear the constraints field and press `Create App` again

You would still see this error unless you put a valid constraint in there or Cancel and start over

**Comment by meichstedt** [comment]
hey surdy,

thanks for the bug report and the well written description! This behaviour seems to be specific to 0.8.x and is fixed in newer versions. Since this is not a serious issue, this will most likely not be fixed for the 0.8.x release.

However, the constraints field seems buggy in a different way in the latest build. I created #2079 to further track that issue.
