### ISSUE TITLE
Marathon REST API documentation should be able to be viewed by version.

### ISSUE THREAD

**Issue by ikinsey** [mesosphere/marathon#2069]
0.8.2 marathon returns 

 {Code:201 Apps:[] App:<nil> Versions:[] Tasks:[] DeploymentId:a2deb836-cf20-4217-a527-37a86c4ed208}

on a successful POST /v2/apps, but the documentation shows

{
    "args": null,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "maxLaunchDelaySeconds": 3600,
    "cmd": "env && python3 -m http.server $PORT0",
    "constraints": [
        [
            "hostname",
            "UNIQUE"
        ]
    ],
    "container": {
        "docker": {
            "image": "python:3"
        },
        "type": "DOCKER",
        "volumes": []
    },
    "cpus": 0.25,
    "dependencies": [],
    "deployments": [
        {
            "id": "f44fd4fc-4330-4600-a68b-99c7bd33014a"
        }
    ],
    "disk": 0.0,
    "env": {},
    "executor": "",
    "healthChecks": [
        {
            "command": null,
            "gracePeriodSeconds": 3,
            "intervalSeconds": 10,
            "maxConsecutiveFailures": 3,
            "path": "/",
            "portIndex": 0,
            "protocol": "HTTP",
            "timeoutSeconds": 5
        }
    ],
    "id": "/my-app",
    "instances": 2,
    "mem": 50.0,
    "ports": [
        0
    ],
    "requirePorts": false,
    "storeUrls": [],
    "upgradeStrategy": {
        "minimumHealthCapacity": 0.5,
        "maximumOverCapacity": 0.5
    },
    "uris": [],
    "user": null,
    "version": "2014-08-18T22:36:41.451Z"
}

It would be nice to be able to see the documentation for different versions of the API

**Comment by kolloch** [comment]
Hi @ikinsey, 

we agree about the versioning of the docs, therefore we opened #1855. Any chance you can help us out with that?

In addition, I think that response is incorrectly documented for all Marathon versions since 0.8.2. It would be nice to have that corrected. Could you open a separate issue for that or even provide updated documentation? That would be appreciated.

https://mesosphere.github.io/marathon/docs/contributing.html

I will close that issue now, since at least the title refers to the same issue as #1855.
