### ISSUE TITLE
Marathon can't do anything after master failover

### ISSUE THREAD

**Issue by sample** [mesosphere/marathon#2207]
I have HA setup with 3 marathon and mesos masters. When I stop active marathon master (or sending DELETE to /v2/leader), next marathon instance becomes active master, I can't perform any operations(restart/destoy app, deploy, etc). When the old master becomes leader again, everything starts to work properly, but marathon loosing all active deployment tasks.

zk and master options on all servers:
master: `zk://10.37.129.11:2181,10.37.129.12:2181,10.37.129.13:2181/mesos`
zk: `zk://10.37.129.11:2181,10.37.129.12:2181,10.37.129.13:2181/marathon`

Logs from initial marathon master and mesos-master: https://gist.github.com/sample/6d2e9b837b1681fcd0c5

Logs from stanby marathon master: 
https://gist.github.com/sample/37764b5cde544c28b31a

in new mararthon master logs i see:

```Sep  7 23:26:27 master1 marathon[21977]: [INFO] [09/07/2015 20:26:27.641] [marathon-akka.actor.default-dispatcher-16] [akka://marathon/user/MarathonScheduler/$a/DeploymentManager/f571be97-f97c-4fc7-a5d7-726c79ab9663/$a] Message [mesosphere.marathon.upgrade.StartingBehavior$Sync$] from Actor[akka://marathon/user/MarathonScheduler/$a/DeploymentManager/f571be97-f97c-4fc7-a5d7-726c79ab9663/$a#-699587477] to Actor[akka://marathon/user/MarathonScheduler/$a/DeploymentManager/f571be97-f97c-4fc7-a5d7-726c79ab9663/$a#-699587477] was not delivered. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.```

**Comment by dkesler** [comment]
This log snippet from the mesos leader:

```
master.cpp:1910] Received re-registration request from framework 20150904-204953-209790218-5050-1838-0001 (marathon) at scheduler-d17968ed-ffcd-4aae-b5a3-22612604fd7a@127.0.1.1:60466
```

makes it sound like the marathon frameworks are registering with mesos as 127.0.1.1, which won't work unless the marathon leader and mesos leader are on the same box.  This would be consistent with marathon not working until the original marathon leader became leader again, assuming the original leader was on the same box as the mesos leader.  I believe you can work around this by setting the --hostname command line arg to the box's externally available ip address.  

As for losing tasks, it might be caused by https://github.com/mesosphere/marathon/issues/1553, but that's just a guess.

**Comment by sample** [comment]
>registering with mesos as 127.0.1.1
This is it. Thanks!
