### ISSUE TITLE
Ports documentation

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/marathon#2236]
The ports documentation is nonsensical: https://mesosphere.github.io/marathon/docs/rest-api.html and https://mesosphere.github.io/marathon/docs/service-discovery-load-balancing.html

> This port is used to ensure no two applications can be run using Marathon with overlapping port assignments (i.e. that the ports are globally unique).

I can run apps on different hosts with the same port, so what does "globally unique" mean here?

> However, this is not the port that each instance of that application is assigned when running on slave nodes within the Mesos cluster.

Then what is it?

> Since multiple instances may run on the same node, each instance (or task) is assigned a random port.

Isn't this only if I specify "0".  What if I specify multiple "0"s?  Do I get multiple random ports?  How do I access them?

The list goes on...

**Comment by air** [comment]
Short term we should absolutely make the docs make sense.

**Comment by edude03** [comment]
I'm not sure where best to put this, but something that stumped me for awhile was how servicePorts and containerPorts worked together. 

I have an app (ported from Heroku) that uses the PORT env var to set its listening port, and I thought setting containerPort to 3000 would set PORT to 3000 and my app would work, but it turns out it sets up a proxy that forwards the random hostPort to port 3000 in the container AND set the PORT variable to $hostPORT

therefore host port 31245-> container 3000 but container app is actually listening on 312345. I'm not sure if that's a bug or just port documentation however.

**Comment by ssk2** [comment]
@edude03 - if you set `containerPort` to 0, it will use the same value as the `hostPort` and using `$PORT0` will work as intended!
