### ISSUE TITLE
Ability to scale an application forcefully if there is a deployment running

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2244]
If there is already a deployment running for an application I want to scale, I should be asked if I want to scale the application forcefully.

**Comment by aldipower** [comment]
https://github.com/mesosphere/marathon-ui/pull/202

**Comment by kolloch** [comment]
Please also do the same for suspend (which is only a specialized scaling operation).

**Comment by Raffo** [comment]
The code I provided works also for suspend given that they use the same code that is used for scaling. Maybe the error message could be slightly misleading, because after if fails it will propose exactly the same message as with scaling ("Failed to scale..."), but I see no problem with this from the user perspective since a previous dialog asked to "scale to 0 instances".

**Comment by pierlo-upitup** [comment]
Closed by mesosphere/marathon-ui#202

**Comment by aldipower** [comment]
Good point.
