### ISSUE TITLE
Scaling check ignores task versions

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#2280]
Task configuration is saved before deployment ends.

__Scenario:__

1. Deploy application in version X with configuration A 
2. Deploy same application (same id) in version Y with configuration B (same number of instances as in configuration A). Let's assume that this application has some problem with start, so it respond on health check with 500 code. Because of that marathon continuously try to launch it.
3. Application in version X and configuration A are still working. Developer stop running deployment of version Y.
4. When developer want deploy version Y again with configuration B marathon do noting because it's see this configuration is already deployed and desired number of instances is achieved while only previous version is running.

**Comment by kolloch** [comment]
Hi @janisz, thanks for reporting this!

Even though this might be confusing, PART of this is actually (at least at first) expected behavior. If you "stop" a deployment, you forcefully say to Marathon that it should NOT revert the configuration of the app, it should just stop bother trying for the moment. Reverting (instead of stopping it) the deployment should actually switch back to the old app configuration and then redeploying the new config should work.

After that, Marathon should check periodically whether enough tasks are running and initiates a scaling operation when necessary. (It also does that when a task failed) You can configure that with `--scale_apps_initial_delay` and `--scale_apps_interval`.

Unfortunately, that periodic check doesn't consider the version of the deployed tasks.

Can I change the title to "Scaling check ignores task versions"? Or do you want to address another issue?

**Comment by janisz** [comment]
@kolloch 
Thanks for explanation. My problem was caused by improper use of _Stop_ button while _Rollback_ should be used. _Scaling check ignores task versions_ sounds good.

**Comment by aquamatthias** [comment]
With the fix for #2441 we wait for all old versions of an app to die as part of the deployment. The scaleApp operation is not applied to apps in deployment. There should be no app with different task versions, that are not controlled by a deployment.
