### ISSUE TITLE
Different apps on different hosts

### ISSUE THREAD

**Issue by 208rishabh** [mesosphere/marathon#2330]
I am running two different apps on a Mesos-cluster using Marathon. I want these apps to be launched on different slaves always (even while scaling up). Can someone help?

**Comment by Poogles** [comment]
You need to use constraints as per; https://mesosphere.github.io/marathon/docs/constraints.html.

`"constraints": [["hostname", "UNIQUE"]]`

Should be what you require.

**Comment by 208rishabh** [comment]
I suppose constraints would only make sure different tasks/instances of the same app are on unique host. I want different apps to be on unique hosts.

**Comment by meichstedt** [comment]
Hey Rishabh,
You could also tag your slave nodes and add constraints to your app definitions that only accept a certain rack, for example. This might need more administration than you like, though. In order to help us understand your concern, please specify the exact use case.

This seems to be more of a general question – for discussions and questions around marathon, the [marathon-framework google group](https://groups.google.com/forum/#!forum/marathon-framework) is better suited than a GitHub issue. I'll close this for now. If you consider this as a feature request, please add more context and a use case. Feel free to re-open.

Best regards
Matthias

**Comment by 208rishabh** [comment]
Thanks.

My use case: I want to launch Spark-Master and Spark-Slave through Marathon so that if any of those fails, it is restarted (fault tolerance). To avoid performance issues, I want both of these (and their multiple instances) to be launched on different nodes.

I think tagging might help, although I will have to fix a particular group of nodes for Master and a different group for slaves.
