### ISSUE TITLE
Parameters in the Docker container settings are not taken into account

### ISSUE THREAD

**Issue by heyMcFly** [mesosphere/marathon#2338]
![marathon-new-app](https://cloud.githubusercontent.com/assets/4841389/10243146/d7d9e2d4-68f6-11e5-95c7-da0554f9d6f5.png)

Simple docker app created as shown above

![marathon-app-configuration](https://cloud.githubusercontent.com/assets/4841389/10243147/db562c42-68f6-11e5-9881-2f93a98c1400.png)

Parameters are not serialized in the container's configuration, whereas volumes and ports behave as expected.

Tested on Marathon 0.11.0, Mesos 0.24.1, bento/centos-7.1 bare image with vagrant.

**Comment by philipnrmn** [comment]
This is fixed by the recent UI modal refactor (https://github.com/mesosphere/marathon-ui/pull/209)

It is an existing bug in Marathon 0.11.0

**Comment by philipnrmn** [comment]
Hi @heyMcFly, thanks for your detailed bug report! We have fixed in an extensive refactoring exercise recently. We just tagged a [new release](https://github.com/mesosphere/marathon-ui/releases/tag/v0.12.0) of the UI so we hope to have that out for our users soon. 

This bug only seems to affect cases where a Docker application is used. You can work around this limitation by using the edit button to add environment variables. 

In the meantime I'll close this ticket as a known issue.

**Comment by heyMcFly** [comment]
You're welcome, and thanks for the heads up.

Cheers

**Comment by philipnrmn** [comment]
We're able to supply a fix to this in the forthcoming 0.11.1, so reopening on that basis.

**Comment by philipnrmn** [comment]
Fixed in mesosphere/marathon-ui#290

**Comment by aquamatthias** [comment]
Hey @heyMcFly we fixed that issue. There is an RC version 0.11.1-RC1 which includes the fix. Would be cool, if you could try that version. If everything goes well, we will do the 0.11.1 release tomorrow.
