### ISSUE TITLE
Migration of ZK State to 0.13/0.14 does not work

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2405]
Started some tasks in 0.11 and restarted on master. Got following stack trace:

marathon [2015-10-12 16:19:56,348] ERROR Migration failed! (mesosphere.marathon.state.Migration:97)
marathon java.lang.RuntimeException: while migrating storage to 0.13
marathon 	at mesosphere.marathon.state.Migration$$anonfun$migrations$4$$anonfun$apply$2.applyOrElse(Migration.scala:62)
marathon 	at mesosphere.marathon.state.Migration$$anonfun$migrations$4$$anonfun$apply$2.applyOrElse(Migration.scala:61)
marathon 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
marathon 	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
marathon 	at scala.util.Try$.apply(Try.scala:192)
marathon 	at scala.util.Failure.recover(Try.scala:216)
marathon 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
marathon 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
marathon 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
marathon 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
marathon 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
marathon 	at java.lang.Thread.run(Thread.java:745)
marathon Caused by: mesosphere.marathon.StoreCommandFailedException: Could not fetch MarathonTaskState with key: app:app.8f61d32e-70e6-11e5-a216-7a090c3edc79
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$mesosphere$marathon$state$MarathonStore$$exceptionTransform$1.applyOrElse(MarathonStore.scala:75)
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$mesosphere$marathon$state$MarathonStore$$exceptionTransform$1.applyOrElse(MarathonStore.scala:74)
marathon 	... 10 more
marathon Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
marathon 	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:94)
marathon 	at com.google.protobuf.CodedInputStream.checkLastTagWas(CodedInputStream.java:124)
marathon 	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:143)
marathon 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:176)
marathon 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:188)
marathon 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:193)
marathon 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
marathon 	at mesosphere.marathon.Protos$MarathonTask.parseFrom(Protos.java:8377)
marathon 	at mesosphere.marathon.state.MarathonTaskState.mergeFromProto(MarathonTaskState.scala:15)
marathon 	at mesosphere.marathon.state.MarathonTaskState.mergeFromProto(MarathonTaskState.scala:9)
marathon 	at mesosphere.marathon.state.MarathonStore.mesosphere$marathon$state$MarathonStore$$stateFromBytes(MarathonStore.scala:79)
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1$$anonfun$apply$2.apply(MarathonStore.scala:35)
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1$$anonfun$apply$2.apply(MarathonStore.scala:33)
marathon 	at scala.Option.map(Option.scala:146)
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1.apply(MarathonStore.scala:33)
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1.apply(MarathonStore.scala:33)
marathon 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
marathon 	at scala.util.Try$.apply(Try.scala:192)
marathon 	at scala.util.Success.map(Try.scala:237)
marathon 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
marathon 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
marathon 	... 4 more

**Comment by Riptawr** [comment]
Just tested an upgrade from 0.11 to 0.13 on a three node setup - got a similar issue right away.
Had to delete the data in zookeepers datadir to get it running, here is the stack.
Please let me know if you need anything else.

[2015-12-18 15:00:26,230] ERROR Failed to take over leadership (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$9834703f:pool-1-thread-4)
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]: mesosphere.marathon.MigrationFailedException: while migrating storage to 0.13
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at mesosphere.marathon.state.Migration$$anonfun$migrations$4$$anonfun$apply$2.applyOrElse(Migration.scala:61) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at mesosphere.marathon.state.Migration$$anonfun$migrations$4$$anonfun$apply$2.applyOrElse(Migration.scala:60) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.util.Try$.apply(Try.scala:192) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.util.Failure.recover(Try.scala:216) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]: Caused by: java.io.StreamCorruptedException: invalid stream header: 0A286E73
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806) ~[na:1.8.0_65]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299) ~[na:1.8.0_65]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at mesosphere.marathon.state.MigrationTo0_13$$anonfun$fetchLegacyTask$1$$anonfun$apply$35.apply(Migration.scala:317) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at mesosphere.marathon.state.MigrationTo0_13$$anonfun$fetchLegacyTask$1$$anonfun$apply$35.apply(Migration.scala:316) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.Option.flatMap(Option.scala:171) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at mesosphere.marathon.state.MigrationTo0_13$$anonfun$fetchLegacyTask$1.apply(Migration.scala:316) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at mesosphere.marathon.state.MigrationTo0_13$$anonfun$fetchLegacyTask$1.apply(Migration.scala:316) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.util.Try$.apply(Try.scala:192) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.util.Success.map(Try.scala:237) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon:0.13.0]
Dec 18 15:00:26 mon01.hq.droidcraft.org marathon[2120]:         ... 4 common frames omitted

**Comment by rikwasmus** [comment]
Can confirm that (using the APT packages from mesosphere), upgrade 0.11 -> 0.13 fails indeed with the _" java.io.StreamCorruptedException: invalid stream header"_ / _"while migrating storage to 0.13"_

**Comment by aquamatthias** [comment]
@meichstedt can you retest with the linux packages?

**Comment by jolexa** [comment]
@aquamatthias I can confirm this issue as well, willing to test, but can you clarify what the "linux packages" are (vs deb from http://repos.mesosphere.com/ubuntu ?)

**Comment by christianparpart** [comment]
i can confirm that this problem exists in docker hubs mesosphere/marathon:latest (I assume 0.13), too. ;-(

**Comment by meichstedt** [comment]
@Riptawr @rikwasmus @jolexa @christianparpart Can you please share your Marathon configurations and used versions/artifacts? In general, migration seems to work from 0.11.1 to 0.13.0, but I have seen failures with migrating to 0.14.0-RC1 and possibly in combination with zk compression.

**Comment by jolexa** [comment]
Here is the version that I'm trying to upgrade FROM:

```
# dpkg -s marathon
Package: marathon
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 64801
Maintainer: Mesosphere Package Builder <support@mesosphere.io>
Architecture: amd64
Version: 0.11.1-1.0.432.ubuntu1404
Depends: java8-runtime-headless, lsb-release
Conffiles:
 /etc/init.d/marathon 466223be042271607b2144c48c5b9360
 /etc/init/marathon.conf e3514d292298ee11990fb6297c54a204
Description: Cluster-wide init and control system for services running on Apache Mesos
License: Apache-2.0
Vendor: Mesosphere, Inc.
Homepage: https://github.com/mesosphere/marathon
```
upgrading to:
```
# dpkg -s marathon
Package: marathon
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 69905
Maintainer: Mesosphere Package Builder <support@mesosphere.io>
Architecture: amd64
Version: 0.13.0-1.0.440.ubuntu1404
Depends: java8-runtime-headless, lsb-release
Conffiles:
 /etc/init.d/marathon 466223be042271607b2144c48c5b9360
 /etc/init/marathon.conf e3514d292298ee11990fb6297c54a204
Description: Cluster-wide init and control system for services running on Apache Mesos
License: Apache-2.0
Vendor: Mesosphere, Inc.
Homepage: https://github.com/mesosphere/marathon
```

With a 3 node cluster and pretty vanilla startup parameters: ha, checkpoint, webui_url, hostname.

**Comment by rikwasmus** [comment]
Mesossphere build: 

    Package: marathon
    Status: install ok installed
    Priority: extra
    Section: default
    Installed-Size: 69904
    Maintainer: Mesosphere Package Builder <support@mesosphere.io>
    Architecture: amd64
    Version: 0.13.0-1.0.440.debian81
    Depends: java8-runtime-headless, lsb-release
    Conffiles:
     /lib/systemd/system/marathon.service 4514844f6205ec7fede53e330b17c85f
    Description: Cluster-wide init and control system for services running on Apache Mesos
    License: Apache-2.0
    Vendor: Mesosphere, Inc.
    Homepage: https://github.com/mesosphere/marathon


Config:

    ./conf/zk:
    zk://10.69.6.56:2181,10.69.6.57:2181,10.69.6.58:2181/marathon
    ./conf/https_port:
    8443
    ./conf/http_credentials:
    <redacted>
    ./conf/ssl_keystore_path:
    /etc/marathon.jks
    ./conf/?disable_http:
    
    ./conf/ssl_keystore_password:
    <redacted>
    ./conf/http_port:
    8080
    ./conf/master:
    zk://10.69.6.56:2181,10.69.6.57:2181,10.69.6.58:2181/mesos

FWIW, zookeepeer:

    Package: zookeeper
    Status: install ok installed
    Priority: optional
    Section: java
    Installed-Size: 243
    Maintainer: Debian Java Maintainers <pkg-java-maintainers@lists.alioth.debian.org>
    Architecture: all
    Version: 3.4.5+dfsg-2

And config:

    tickTime=2000
    initLimit=10
    syncLimit=5
    dataDir=/var/lib/zookeeper
    clientPort=2181
    server.1=10.69.6.56:2888:3888
    server.2=10.69.6.57:2888:3888
    server.3=10.69.6.58:2888:3888
    snapCount=10000
    leaderServes=yes
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=10

**Comment by rikwasmus** [comment]
Oh, and upgrading from: 0.11.1-1.0.432.debian81

In the end, I just exported my full config, removed the zookeeper key, started the marathon cluster with a clean state, and reapplied the configuration. Not ideal when running production on it.

**Comment by meichstedt** [comment]
Tanks for the info, @rikwasmus and @jolexa. I've spent some time testing an debugging this. I can reproduce the error, but only if I sabotage the frameworkId migration part of the 0.13 migration logic. In that case, the 0.13 migration fails and leaves the system in a state where the tasks are already migrated, but the version number is not updated. In the following step, the migration fails because the new tasks have a different binary format and cannot be loaded. In this case I see a `INFO Completed 0.13 migration` log message, followed by a new attempt and the error described above. Tasks keys in zk are then already in format `task:appId.uuid` instead of `task:appId:appId.uuid`. 

Does someone have complete logs of a failed migration?

**Comment by gkleiman** [comment]
Hi all!

We just released v0.14.0-RC3, which includes an improved tasks migration process. The process will now migrate task state in Zookeeper sequentially and skip tasks that have already been migrated. This allows the migration process to be retried/resumed in case of transient errors.

The migration process will not complete until all nodes are successfully migrated. If a Zookeeper node is broken or something else during migration breaks, the whole process will still fail as we cannot automagically heal a broken state. In case of persistent errors, please report with full logs.

Can you please try the new version and report back if it solved your migration problems? If it didn't, please provide the full logs, as they should now have more information.

Thanks!

**Comment by jolexa** [comment]
@gkleiman @meichstedt Hello, some feedback for this issue. I've successfully migrated my task state by using 0.14.0-RC4 on the existing cluster that I was mentioning. Thanks!

**Comment by meichstedt** [comment]
Thanks for the info, @jolexa!

**Comment by rikwasmus** [comment]
Sorry for the late reply: original setup was gone, but upgrading another setup from 0.11 to 0.14 has worked flawlessly (which much the same zookeeper & master configuration).
