### ISSUE TITLE
 mem NOT SATISFIED

### ISSUE THREAD

**Issue by VFT** [mesosphere/marathon#2492]
there is 2G memory in my mesos slave node,but when i push a app who's memory was set to 512M,the app was still deploying status.

i found the key word `mem NOT SATISFIED (512.0 > 401.0)`

memory of slave is:
```bash
              total        used        free      shared  buff/cache   available
Mem:           1.8G        239M        398M         24M        1.2G        1.2G
Swap:          2.0G         76K        2.0G
```
i thought that marathon use the infomation of memory is from 'free' but not `available`

is it a bug?

**Comment by meichstedt** [comment]
Marathon does not query the slaves/agents resource availability at all. Marathon reacts to resource offers it gets from the mesos master, which are based on offers the master gets from connected agents. If Marathon receives an offer for 401M, but needs 512M to launch your task, then the log message you posted totally makes sense. The question is: Why does mesos only offer 401M, and most probably this is because other tasks are already running on that agent (or the mesos-slave process has a different understanding of the node's resources than you do).

_In general, please provide information on your setup – marathon version, mesos version, as well as logs and app config. Otherwise, it's hard to see what's going on, like how many tasks have been started already on that agent._
