### ISSUE TITLE
could i use marathon api get the cluster information, such as mem,cpu,network usage on every node/cluster?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#2576]
thanks!

**Comment by meichstedt** [comment]
@junneyang You can use mesos' `/state.json` endpoint to retrieve information about the nodes in your cluster. Alternatively, you can use the [DCOS CLI](https://github.com/mesosphere/dcos-cli)'s `dcos node --json` command to retrieve that information.

HTH!

**Comment by junneyang** [comment]
ok, i see, thanks
i propose that marathon could provide the API, which get the cluster mem,cpu,network info, 
and this colud be very useful to decide whether to scale in/out the slave node or not.

**Comment by meichstedt** [comment]
Not sure if I got your point here. There might be a ton of other frameworks using a cluster. The question `do I need to scale out?` should be based on Information provided by Mesos – a framework should not have, gather or expose specific information about the current state of nodes in the cluster. Otherwise you could argue that each framework should expose that API, and I don't think that's a good idea. That would be like having a web browser exposing information about the hardware that the OS is running on.

**Comment by junneyang** [comment]
you got it, ^--^
i think this is marathon's responsibility.

**Comment by meichstedt** [comment]
Why?

**Comment by junneyang** [comment]
well, my understanding is not deep enough
thanks for your help!
