### ISSUE TITLE
how to make host port  remain unchanged when app restart or move to other node ?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#2578]
1. let host port is randomed at the first time start
2. how to make host port remain unchanged when app restart or move to other node ?

i think this will be very useful

**Comment by rasputnik** [comment]
@junneyang how would that work if you already have things on that port?

**Comment by junneyang** [comment]
what I mean is this :
1. i create an app with shell like this:
"ports": [
                        0
                    ],
![Uploading image.png…]()


or docker like this:

"portMappings": [
                                {
                                    "containerPort": 80,
                                    "hostPort": 0,
                                    "servicePort": 0,
                                    "protocol": "tcp"
                                },


2. the app will start with a random host port , eg : 31234

3. when the app migrate to other node or restart,
how to make host port remain unchanged: 31234


thanks!

**Comment by rasputnik** [comment]
I understand what you want to do i think, what I'm asking is how would marathon
be able to provide you that feature? the only way to do that would be to reserve that
port somehow on all slaves (or any that might be created in the future) in case you ever
need to fail over to it.

**Comment by junneyang** [comment]
ok , i see
in other words, is there any way to access the app host-port dynamic, like  DNS?

**Comment by junneyang** [comment]
or is there any way to access the depend app's env?

**Comment by junneyang** [comment]
1. i create a mysql app, the host-port is random, eg: 31234
2. when mysql app migrate to other node or restart(host-port may change, eg: 31235), how the web app dynamic adjust

Looking forward to your reply , very thanks !

**Comment by junneyang** [comment]
is this possible to achieve?

**Comment by hotstepper13** [comment]
@junneyang 
You have to rethink your approach. Think of your whole infrastructure as a big box. Instead of making some apps static, Just let them deploy as they are and come up dynamically.

For mysql this might not be the best option but if you have an application that comes with a service registry, you dont need to worry about that. Simply install HAProxy on your infrastrukcture server and use a little script to update the rules. A very cool approach can be found @ https://mesosphere.github.io/marathon/docs/service-discovery-load-balancing.html

In your case you could use the provided script or (as i did) take this to write your own. Define that every container/Application that has a name "MySQL" is put into a rule that is available to the outside by port 3306.  

Because mysql didnt support loadbalancing that way this only helps you in case that your infrastructure host goes down and your mysql is moved to another box and getting a new port.

You can simply enter many urls for your haproxy servers and be sure that if one fails, another one will come up. But you have to take case of your datafiles. Maybe this link can help you to archive your goal: https://www.digitalocean.com/community/tutorials/how-to-use-haproxy-to-set-up-mysql-load-balancing--3

**Comment by junneyang** [comment]
＠hotstepper13 thanks very much for your help and direct
