### ISSUE TITLE
Prevent users from submitting trailing slash as appIDs

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2611]
This is a spin off issue of the discussion started at https://github.com/mesosphere/marathon-ui/pull/380#issuecomment-155419768

If a user supplies an app ID with a trailing slash, e.g. "/testing/" and POST this to the `v2/apps` then Marathon will proactively "fix" this by interpreting it as an appId rather than a group. 
In my opinion Marathon should simply reject the appId as invalid, because if the user actually meant to create a group with that pathname, they will have to kill the app first. See my comment: https://github.com/mesosphere/marathon-ui/pull/380#issuecomment-155422860 and the following.

I suggest to prevent users from supplying an app id with a trailing slash from the "New Application" dialog to avoid confusion. Also, as mentioned in https://github.com/mesosphere/marathon/issues/2609, there currently is no clear error message to be shown to the user otherwise. 

cc'ing @leemunroe  for UX and @kolloch for supervision

**Comment by aldipower** [comment]
I am not sure, if I could follow this idea.
To create (empty) groups you do a request on the groups-endpoint, which isn't implement in the UI right now.

Right now, we only deviate the groups from the appId in the UI and the only endpoint we are accessing is the apps-endpoint.

So I don't see any problem to create an app with an trailing slash like "/testapp/", which is then automatically converted to "/testapp".
At this point the user is in the _app_ creation dialog, which is intentional to create an app and not a group. I don't see the UX problem here.

**Comment by pierlo-upitup** [comment]
I'll simplify: if the user left a trailing slash, he did it accidentally. While Marathon "intelligently" fixes this (based on the assumption that the user tried posting a "group id" to the `/apps` endpoint) I believe it should simply reject it and notify the user.

**Comment by leemunroe** [comment]
Seems like a good preventative measure, rather than us making an assumption. Something like this?

![image](https://cloud.githubusercontent.com/assets/15963/11076844/e01ca0d8-87b1-11e5-87cb-0280f630f7de.png)

Or to even better prevent confusion

![image](https://cloud.githubusercontent.com/assets/15963/11076837/d1709d6e-87b1-11e5-9fe8-a08524ebc9e1.png)

**Comment by pierlo-upitup** [comment]
@leemunroe exactly what I had in mind, with a mild preference for your first suggestion.

**Comment by mwasn** [comment]
I would prefer #2 as I would have to think what exactly might be the reason that my app couldn´t be created.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3084. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
