### ISSUE TITLE
Config change does not update all fields (JSON Upload)

### ISSUE THREAD

**Issue by hotstepper13** [mesosphere/marathon#2642]
Using Marathin 0.11.1

Define a job with configuration containing:
    "constraints": [
        ["hostname", "UNIQUE"]
    ],
    "instances": <number_of_available_slaves>,

Deploy it. (your job will deployed across the available instances)

Now remove the contraint and update the configuration with
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1
    }

Now issue a restart.

Expected Behavior:
One additional Instance will be started without the UNIQUE contraint and after a restart of all instances, there should be no UNIQUE contraint anymore.

Seen Behavior:
In the current configuration the UNIQUE contraint is still set, preventing marathon from starting a single instance.

Additional Information:
This affects also health checks. If you define a healtch check and deploy your application everything is fine. If you remove the healthcheck and update the configuration, the healthcheck stay´s active.

**Comment by kolloch** [comment]
Hi @hotstepper13, thanks for your report.

What exactly did you do to "remove the constraint" or to remove the health checks? Using `PUT /v2/apps/myapp` and an empty `"constraints": []` list should work. Similarly with health checks. Just removing the `"constraints"` attribute from the JSON and putting the config again to the end-point will not change the existing constraints list. Our `PUT`s are more like patches.

See https://github.com/mesosphere/marathon/issues/1418

If the problem is something else, please reopen.
