### ISSUE TITLE
FeatureRequest: Show Resources

### ISSUE THREAD

**Issue by hotstepper13** [mesosphere/marathon#2643]
I am using Marathon 0.11.1 and I am missing a resource view.

The coolest/best resourceview I have seen in the past is the one from Kubernetes where each circle represents a host and stating cpu/memory consumptions (with fancy animations).

Within Marathin I can see how much memory and cpu is configured for the different services but i have no view of the current resources.

It would be great to at least a seperate tab which show the used and available resources from each slave. I think those circle visualisation would be great and could be perfectly integrated into the marathon ui. The needed date is available in mesos, therefore it should be easy to integrate into marathon.

If needed, I could provide some layout suggestions.

**Comment by meichstedt** [comment]
Hi @hotstepper13 
Marathon is a framework that runs in a cluster that is managed by Mesos. There might be a number of other frameworks scheduling tasks on Mesos offers, and there can be many instances of Marathon itself. That said, showing available, used or reserved resources in a cluster is within the responsibility of Mesos and not within that of a framework.

You can use the [DCOS UI](https://docs.mesosphere.com/overview/webinterface/) or the [DCOS CLI](https://docs.mesosphere.com/overview/introcli/), respectively, in order to retrieve that information, as well as the Mesos UI or Mesos' `state.json` endpoint.
