### ISSUE TITLE
Prototype: Show Logs (Error Logs and and Output Logs) in Task Detail View 

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2645]
As Administrator I want to access the Error and Output Logs of a single task so that I stay in Marathon UI for while debugging issues.

**Scenario 1: show download link for stdout**
GIVEN a deployed app with one or more tasks
WHEN a user opens the app detail view
THEN a download link stdout is shown for every task

**Scenario 2: show content of stdout file**
GIVEN a download link for stdout file
WHEN a user clicks on the link
THEN the content of the file is shown in a separate window

**Scenario 3: show download link for stderr**
GIVEN a deployed app with one or more tasks
WHEN a user opens the app detail view
THEN a download link stderr is shown for every task

**Scenario 4: show content of stderr file**
GIVEN a download link for stderr file
WHEN a user clicks on the link
THEN the content of the file is shown in a separate window

---
https://projects.invisionapp.com/share/9U3ZMXKD5#/screens/97718387

**Comment by mwasn** [comment]
@orlandohohmeier wrote: 

---
I had a look into this, today and would like to share my findings:

**Download link structure**
```
{MESOS_HOST}:{MESOS_PORT}/files/download?path={FILE_PATH}
```

**File path (stdout and stderr)**
```
/tmp/mesos/slaves/{SLAVE_ID}/frameworks/{FRAMEWORK_ID}/executors/{TASK_ID}/runs/{EXECUTOR_DIR}/stderr
/tmp/mesos/slaves/{SLAVE_ID}/frameworks/{FRAMEWORK_ID}/executors/{TASK_ID}/runs/{EXECUTOR_DIR}/stdout
```

**Endpoints**
```
FRAMEWORK_ID, MESOS_URI -> {MARATHON_URI}/v2/info
SLAVE_ID, SLAVE_HOST, SLAVE_PORT, TASK_ID  -> {MARATHON_URI}/v2/apps/cmd?embed=app.taskStats 
EXECUTOR_DIR -> {MESOS_URI}/state
```

**Notes**
Mesos does not provide an Access-Control-Allow-Origin but support JSONP therefor we should not have any same origin policy issues.

**Comment by kolloch** [comment]
Some notes: I think it is not necessarily the best design to show these files in a separate window. That is something I do not particularly enjoy in using the Mesos UI.

Since we are usually dealing with log files, it is an important feature what part of the file is shown. How can we scroll? How can we tail? It would be very good if we could easily download the log from the tailing view as well.

**Comment by pierlo-upitup** [comment]
@orlandohohmeier could you post the updates for this task? thanks!

**Comment by orlandohohmeier** [comment]
**Concluding notes:** In order to display the log files, as described, we need to do a few JSONP (`/state`) calls to retrieve the agent URI and executer directory before we can perform the actual browse files call to retrieve the logs. We need to be aware that these call are “expensive” (the core team is working on improving the state endpoint performance). I reached out to the for alternatives to the `/state` endpoint, but there is no real alternative yet. Thus we should "cache" the responses as long as possible and probably need some kind of a loading visualisation (@leemunroe  let's talk about a loader-some-thing) as it may take some time to get the logs.
We also need to be aware that the master/state endpoint doesn't necessarily have the executor directory for default command executors (MESOS-527). But this shouldn't be a problem.
