### ISSUE TITLE
0.11.1 -> 0.13.0-RC4 upgrade losing and then killing old tasks

### ISSUE THREAD

**Issue by drewrobb** [mesosphere/marathon#2681]
I was testing upgrade from 0.11.1 to 0.13.0-RC4. Every attempted upgrade results in the new 0.13 leader not recognizing existing tasks, and killing all old tasks at once upon the first reconciliation. I can fail over leaders without upgrading in both 0.11->0.11 or 0.13->0.13 without losing tasks, it is only the upgrade 0.11->0.13  that has this issue. By greatly increasing `--reconciliation_initial_delay` I can make it so that the new tasks are launched before the old tasks get killed, however this is far from ideal IMO. 

Attached is part of the logs from the new 0.13 master, running a single app hello with 3 healthy tasks before the upgrade. 3 more tasks are started and the old 3 tasks are killed. I would expect that the old 3 tasks would be recognized and continue running.

[log.txt](https://github.com/mesosphere/marathon/files/39754/log.txt)

**Comment by aquamatthias** [comment]
@kolloch according to the logs the Migration was successful. Since we now have the assumption, that a task is stored before launch - could that lead to that behavior? (But would only affect staged tasks, that were not reported running before upgrade)

**Comment by meichstedt** [comment]
Will try to reproduce.

**Comment by kolloch** [comment]
@aquamatthias We already assume that tasks are stored upon launch in 0.11.

**Comment by kolloch** [comment]
The error is most likely the following:
* The `EntityStoreCache` should only be used after `onElected` has been called -- since it assumes that it preloaded all entities. Otherwise `names` will return an empty sequence. (https://github.com/mesosphere/marathon/blob/releases/0.13/src/main/scala/mesosphere/marathon/state/EntityStoreCache.scala#L58)
* The migration for 0.13 runs before the `onElected` call. That is visible in the logs and also intended that way. (See https://github.com/mesosphere/marathon/blob/releases/0.13/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala#L268-L274)
* But the migration uses the `EntityStore` of the `TaskRepository` which is an `EntityStoreCache`
* Therefore no tasks will be migrated and no tasks will be loaded.

**Comment by kolloch** [comment]
@drewrobb Since we didn't mention this already: Thanks a lot for reporting this!
