### ISSUE TITLE
Allow configuration of "port" instead of "portIndex" for HTTP/TCP health checks

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2733]
In #2731 we introduce the option to specify the absolute port number for the health check instead of the portIndex. This is especially useful in the IP-per-container case.

Example, instead of:

```javascript
{
    "id": "...",
     // ...
     "healthChecks": [
        {
          "gracePeriodSeconds": 30,
          "ignoreHttp1xx": false,
          "intervalSeconds": 6,
          "maxConsecutiveFailures": 3,
          "portIndex": 0,
          "protocol": "TCP",
          "timeoutSeconds": 2
        }
      ]
}
```

You could write:

```javascript
{
    "id": "...",
     // ...
     "healthChecks": [
        {
          "gracePeriodSeconds": 30,
          "ignoreHttp1xx": false,
          "intervalSeconds": 6,
          "maxConsecutiveFailures": 3,
          "port": 9000,
          "protocol": "TCP",
          "timeoutSeconds": 2
        }
      ]
}
```

In the IP-per-container case, Marathon will (when implemented) automatically choose the IP address of the container and the specified port for the health check.

**Comment by pierlo-upitup** [comment]
@kolloch 

Sorry I'm not sure I can parse this correctly. Do you mean that the *Edit* modal dialog should allow setting the `port` field instead of the `portIndex` in case the service discovery info have been specified? 
As you know we postponed the IP per Container settings in the *Create* modal to "Phase 2".  Do you still see a big gain in only changing this inside the *Edit* modal?

Regarding the "displaying" of the `healthChecks` configuration: this info is already a JSON string of whatever is inside the `healthChecks` field, so if a `port` was specified **in lieu** of a `portIndex` the output will automatically reflect this.

**Comment by pierlo-upitup** [comment]
@mwasn @kolloch – hold on a second, is this even a `gui` issue?

**Comment by gkleiman** [comment]
@pierlo-upitup this is a `gui` issue, service support for this was added in #2731.

If we decide to move forward with this issue and add this to the UI, then the Edit modal dialog should allow to specify either the `port` field or the `portIndex`, but not both at same time. This should always be possible, not only if the app requests an IP-per-Task.

Otherwise I'd recommend closing this issue.
