### ISSUE TITLE
Firefox Memory Leak in Marathon UI

### ISSUE THREAD

**Issue by WalterDalton** [mesosphere/marathon#2755]
Basically, in using Firefox, I noticed that over time, my firefox would get to become unusable when I had Marathon and Mesos WebUIs up and running.  At first, I thought it was a function of my home (Mac) computer and firefox. But when I started a PoC for work, and my Windows install of firefox had the same issues, I started doing more investigation. 

First of all, both at home and at work, my Firefox is only dedicated to "cluster" related tasks. Thus, I don't have other tabs that are not Cluster UIs.  

My typical setup is to have MapR UI, Mesos UI, Marathon UI, Chronos UI, Myriad UI, and Yarn UI all up and running.  

After about 3-4 hours, my browser would get really slow, and non-responsive. I'd kill all and start again.  Rinse repeat.  

So I did some analysis, and basically found a plugin for Firefox that shows on each tab the amount of memory being used. I found that both Marathon and Mesos UI were the culprits, and things got really bad after just 2-3 hours.  With those setup, on Windows, I have the following memory usage:

MapR UI: 7.7mb
Myriad UI: 9.8mb
Yarn: 2.7 mb
Chronos 10.2 mb
Marathon: 163 mb
Mesos UI: 463 mb

Both Marathon and Mesos continually climb, slowly, up some, down a few, up some more, but obviously generally trending up.  I guess I wanted to toss it out here to see if it's something in my settings, or something that others are seeing.  It's a problem for me from a usability standpoint, and I am guessing that it's one of those things that while not a priority for a project, should be looked at. 

Note: I tried memory GC in firefox and it did not clear the memory for Mesos or Marathon. 

Thanks!

**Comment by orlandohohmeier** [comment]
Thanks again for reporting and investigating this!

Could you please tell me which Firefox and Marathon UI version (pressing `g v` should bring up the version dialog) you are running? I would also like to know if you have ever experienced the same using a different Browser?

*Corresponding Google Group thread: https://groups.google.com/d/msg/marathon-framework/lLImOD-Gbzg/UX72f2gxCAAJ*

**Comment by philipnrmn** [comment]
Details of what plugins and extensions you have installed in your browser would also be very much appreciated.

**Comment by pierlo-upitup** [comment]
I've run Chrome's profiler for 260 seconds as an initial measurement and the graph does indeed show interesting values for the Listeners:

![screen shot 2015-12-03 at 13 20 35](https://cloud.githubusercontent.com/assets/1078545/11560528/6f7bf14a-99c1-11e5-8e57-a1252ea03d73.png)

I'm going to dive deeper now.

**Comment by pierlo-upitup** [comment]
Additional proof of a longer run (~8 mins) showing similar results.

<img width="927" alt="screen shot 2015-12-03 at 14 36 50" src="https://cloud.githubusercontent.com/assets/1078545/11562008/6b0397da-99cb-11e5-9e8c-ef9ab0e1bbd2.png">

**Comment by philipnrmn** [comment]
Pretty clear then.

**Comment by pierlo-upitup** [comment]
Upon closer look, we isolated the issue to the Ajax library `qajax`. Our hunch is that even the successfully resolved promises are never being GCd. 

The screenshot illustrates how this changes when replacing `qajax` with `jQuery`:

<img width="954" alt="screen shot 2015-12-03 at 18 27 19" src="https://cloud.githubusercontent.com/assets/1078545/11568276/89715ec6-99eb-11e5-8e08-57dfa50e1bdc.png">

Additionally, we also made sure we could exclude that the problem was due the `qajaxWrapper`. 

Here is a [gist](https://gist.github.com/pierlo-upitup/4ab0a29a35a47144ac7b) that replaces Qajax with  jQuery for the 3 actions called by the `/apps` page. To try it out you will need to `npm install jquery` too.

**Possible solutions**

1. Ditch `qajax` and move to `jquery` for the ajax calls
2. Figure out what is causing the issue and hopefully provide a fix for Qajax upstream
3. Write our own, simple ajax library. 

cc @aldipower @philipnrmn @orlandohohmeier 

Thanks @WalterDalton for reporting this, it's really appreciated.

**Comment by aldipower** [comment]
Nicely approached!

**Comment by orlandohohmeier** [comment]
Talking about `quajax` alternatives we should consider using a lib thats able to fire JSONP (see this comment for details: https://github.com/mesosphere/marathon-ui/pull/449#issuecomment-160609965) calls. 
I suggest to invest about 2 hours to fix `qajax` and if that's not helping move on to an alternative.

**Comment by philipnrmn** [comment]
I note that the `qajax` developer recommends using [fetch](https://github.com/github/fetch) instead.

**Comment by philipnrmn** [comment]
I propose replacing `qajax` with [fetch](https://github.com/github/fetch), using [fetch-jsonp](https://www.npmjs.com/package/fetch-jsonp) to extend it with JSONP functionality for the functionality in #2721.
