### ISSUE TITLE
No way to assign servicePorts in the UI

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/marathon#2829]
There's no way to assign servicePorts in the edit UI for a marathon app.  There's "ports", but no "servicePorts".  If the UI is meant to be a complete interface, this is a bug.  If not, then maybe disregard this.  It would be nice though.

**Comment by aldipower** [comment]
Hey @mgummelt !

Marathon provides the ```ports```-field for mesos containers only, there is no other option.
In my understanding they are meant to be service ports.

From https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps:
```
The port array currently serves multiple roles:

    The number of items in the array determines how many dynamic ports are allocated for every task.
    For every port that is zero, a globally unique (cluster-wide) port is assigned and provided as part of the app definition to be used in load balancing definitions. See Service Discovery Load Balancing doc page for details.

Since this is confusing, we recommend to configure ports assignment for docker containers for BRIDGE networking in container.docker.portMappings instead, see Docker Containers doc page).

Alternatively or if you use the Mesos Containerizer, pass zeros as port values to generate one or more arbitrary free ports for each application instance. Each port value is exposed to the instance via environment variables $PORT0, $PORT1, etc. Ports assigned to running instances are also available via the task resource.
```

Of course you can define static ports there too.

Could I clearify this a little bit? 
Otherwise could be more specific?

Cheers

**Comment by philipnrmn** [comment]
Hey @mgummelt,

There's a lot of app config fields we haven't exposed them all in order to keep the modal reasonably approachable. Unfortunately this means we don't offer a couple of really useful fields like `servicePorts` and `forcePullImage`, and that effectively kicks users who want them out of the UI and back to curl. 

One option we're considering is exposing a JSON editor with the full application config in addition to the form, so that there's a reasonably painless way to get to them. Relevant ticket is #2049.

**Comment by aldipower** [comment]
Hey @philipnrmn 
Sorry, just to be complete, there is no field ```servicePorts``` in the API we could offer.
```forcePullImage``` is in the pipe:
https://github.com/mesosphere/marathon-ui/pull/498

**Comment by gkleiman** [comment]
@aldipower, @philipnrmn  there's a servicePort attribute for Docker port mappings, and the UI has a field for it:

![screen shot 2015-12-21 at 12 08 21](https://cloud.githubusercontent.com/assets/146374/11929477/9577ccc0-a7db-11e5-9507-82a6202cc361.png)

For non-Docker apps, the `ports` field is used to define service ports. That can also be set through the UI.
