### ISSUE TITLE
Convert alert, confirm and prompt dialogs to new design

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2831]
All dialogs (alert, confirm and prompt) should support the 3 states: "Info", "Warning", "Error" as shown in the designs:

https://mesosphere.invisionapp.com/share/6P56VR1XZ#/screens/119296369

**AC**
- [ ] implement new designs and all possible states for all kinds of modal
- [ ] provide "defaults" for missing values (ie titles etc.)

Additional copy work is to be  performed in https://github.com/mesosphere/marathon/issues/2909

cc @leemunroe @cleverroffey could you please send us the latest Sketch version for this?

**Comment by orlandohohmeier** [comment]
Do we really need all those states for every type of dialog? Isn't the alert dialog meant to inform about errors, the confirm dialog to confirm risky actions (warning) and prompt dialog to ask for informations?

/cc @philipnrmn @aldipower @Poltergeist

**Comment by orlandohohmeier** [comment]
Nevermind. There are cases, in which dialogs do need different states (e.g. marathon ui version dialog).

**Comment by orlandohohmeier** [comment]
The new design provides a dialog title as well as a state. As we don't have that content yet, we need to define a title and state for every dialog. You find a list of all dialogs including a title, state and message proposal in the following. Any feedback is highly appreciated.

### Application Scale Error (handler: AppPageComponent.jsx -> onScaleAppError)

#### confirm (current message: "There is a deployment in progress that changes ${appId}. If you want to stop this deployment and force a new one to scale it, press the 'Scale forcefully' button.")

**Title:** Danger: ${appId} Is Currently Deploying
**Message:** In order to scale to a new number of instances, the current deployment will have to be forcefully stopped, and a new one started. Please be cautious, as this could result in unwanted states.
**Button:** Stop Current Deployment and Scale
**State:** Danger
          
#### alert (current message: "Not scaling: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not scale application.
**State:** Danger

#### alert (current message: "Not scaling: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not scale application.
**State:** Danger

#### alert (current message: "Not scaling: ${errorMessage.message || errorMessage}")

**Title:** Error
**Message:** ${errorMessage.message || errorMessage} 
**State:** Danger

### Application Restart Error (handler: AppPageComponent.jsx -> onRestartAppError)

#### alert (current message: "Error restarting app: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not restart application.
**State:** Danger

#### alert (current message: "Error restarting app: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not restart application.
**State:** Danger

#### alert (current message: "Error restarting app: ${errorMessage.message || errorMessage}")

**Title:** Error
**Message:** ${errorMessage.message || errorMessage} 
**State:** Danger

### Application Delete Error (handler: AppPageComponent.jsx -> onDeleteAppError)

#### alert (current message:  "Error destroying app: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not delete application.
**State:** Danger

#### alert (current message: "Error destroying app: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not delete application.
**State:** Danger

#### alert (current message: "Error destroying app: ${errorMessage.message || errorMessage}")

**Title:** Error
**Message:** ${errorMessage.message || errorMessage}
**State:** Danger

### Kill Task Error (handler: AppPageComponent.jsx -> onKillTaskError)

#### alert (current message: "Error killing task: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not kill task.
**State:** Danger

#### alert (current message:  "Error killing task: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not kill task.
**State:** Danger

#### alert (current message: "Error killing task: ${errorMessage.message || errorMessage}")

**Title:** Error
**Message:** ${errorMessage.message || errorMessage}
**State:** Danger

### Delete Task Error (handler: AppPageComponent.jsx -> onDeleteTaskError)

#### confirm (current message: "Failed to kill task and scale ${appId}. If you want to stop any current deployment of the app and force a new one to kill the task and scale it, press the 'Kill and scale forcefully' button.")

**Title:** Danger: ${appId} Is Currently Deploying
**Message:** In order to kill the tasks and scale to a new number of instances, the current deployment will have to be forcefully stopped, and a new one started. Please be cautious, as this could result in unwanted states.
**Button:** Stop Current Deployment and Scale
**State:** Danger
        
#### alert (current message: "Not scaling: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not scale application.
**State:** Danger

#### alert (current message: "Not scaling: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not restart application.
**State:** Danger

#### alert (current message: "Not scaling: ${errorMessage.message || errorMessage")

**Title:** Error
**Message:** ${errorMessage.message || errorMessage}
**State:** Danger

### Reset Delay Success (handler: AppPageComponent.jsx -> onResetDelaySuccess)

#### alert (current message: "Delay reset successfully")

**Title:** Application Delay
**Message:** Reset successful.
**State:** Info    

### Reset Delay Error (handler: AppPageComponent.jsx -> onResetDelayError)

#### alert (current message: "Error resetting delay on app: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not scale application.
**State:** Danger

#### alert (current message: "Error resetting delay on app: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not restart application.
**State:** Danger

#### alert (current message: "Error resetting delay on app: ${errorMessage.message || errorMessage}")

**Title:** Error
**Message:** ${errorMessage.message || errorMessage}
**State:** Danger

### Scale Application (handler: AppPageControlsComponent.jsx -> handleScaleApp)

#### promt (current message: "Scale to how many instances?")

**Title:** Scale Application
**Message:** How many instances would you like to scale to?
**Button:** Scale Application
**State:** Info

### Suspend Application (handler: AppPageControlsComponent.jsx -> handleSuspendApp)

#### confirm (current message: "Suspend app by scaling to 0 instances?")

**Title:** Suspend Application
**Message:** Do you want to suspend ${appId} by scaling to 0 instances?
**Button:** Suspend Application
**State:** Info
  
### Restart Application (handler: AppPageControlsComponent.jsx -> handleRestartApp)

#### confirm (current message: "Restart app '${appId}'?")

**Title:** Restart Application
**Message:** Do you want to restart ${appId}?
**Button:** Restart Application
**State:** Info
		 
### Destroy Application (handler: AppPageControlsComponent.jsx -> handleDestroyApp)

#### confirm (current message: "Destroy app '${appId}'? This is irreversible."

**Title:** Danger: You're About To Destroy ${appId}
**Message:** Do you really want to destroy ${appId}? This is irreversible.
**Button:** Destroy Application
**State:** Danger		
		 
### Apply Application Settings (handler: AppVersionListComponent.jsx -> onAppApplySettingsError)

#### alert (current message: "Could not update to chosen version: ${errorMessage.message || errorMessage}")

**Title:** Error: Could Not Update Application Configuration
**Message:** Could not update to chosen version: ${errorMessage.message || errorMessage}
**State:** Danger

### Revert Deployment (handler: DeploymentComponent.jsx -> handleRevertDeployment)

#### confirm (current message: "Rollback deployment of applications: '${model.affectedAppsString}'? Destroying this deployment will create and start a new deployment to revert the affected app to its previous version.")

**Title:** Warning: You're About To Rollback The ${model.affectedAppsString} Deployment
**Message:** This will stop the current deployment and start a new deployment to revert the affected applications to its previous version.
**Button:** Rollback Deployment
**State:** Warning

### Stop Deployment (handler: DeploymentComponent.jsx -> handleStopDeployment)

#### confirm (current message: "Stop deployment of applications: '${model.affectedAppsString}'? This will stop the deployment immediately and leave it in the current state.")

**Title:** Warning: You're About To Stop The ${model.affectedAppsString} Deployment
**Message:** This will stop the deployment immediately and leave the applications in their current state.
**Button:** Stop Deployment
**State:** Warning

### Marathon UI Version Info (handler: Marathon.jsx ->  bindKeyboardShortcuts)

#### alert (current message: "The UI version is ${config.version}")

**Title:** Marathon UI
**Message:** You're running version ${config.version}.
**State:** Info

### Edit Application Error  (handler: EditAppModalComponent.jsx -> onRequestAppVersionError)

#### alert (current message: "Could not fetch app '${props.appId}' version for editing: ${props.appVersion}")

**Title:** Error: Could Not Fetch Requested ${props.appId} Configuration
**Message:** Could not fetch version ${props.appVersion}.
**State:** Danger

/cc @leemunroe @cleverroffey @philipnrmn @aldipower @Poltergeist @pierlo-upitup
