### ISSUE TITLE
Task info is broken in 0.14.0-RC2

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2973]
![image](https://cloud.githubusercontent.com/assets/89186/12292833/b9567ede-b9e7-11e5-9c85-f6bccad0f01e.png)

Something slipped here. IP address doesn't look good either.

**Comment by gkleiman** [comment]
@bobrik does that happen with every task or just that particular one? If it affects just one, the output of `GET /v2/apps` and `GET /v2/apps/{appId}/tasks` would be really useful.

**Comment by bobrik** [comment]
This app reproduces the issue:

![image](https://cloud.githubusercontent.com/assets/89186/12295855/dec92d2e-b9fb-11e5-99db-0ce636d604df.png)

Not all my apps have the issue, but this is pretty common.

**Comment by philipnrmn** [comment]
This was fixed in the UI in v0.14.1 (the relevant commit is [here](https://github.com/mesosphere/marathon-ui/commit/760d719e94657318282d58afc3195ba34d3fe34a))

I built the v0.14.1 version of the UI and tried running it against a job without an IP address. The bug seems to be fixed:
![screen shot 2016-01-13 at 15 53 18](https://cloud.githubusercontent.com/assets/2989362/12297587/3236601e-ba0e-11e5-887b-73924dae7852.png)

**Comment by philipnrmn** [comment]
Tested separately on Marathon v0.14.0-RC2 with the same result as above. I'm therefore closing this bug.

**Comment by bobrik** [comment]
Somehow this slipped into rc4 and 0.14.0 release. @philipnrmn, @gkleiman can you check?

![image](https://cloud.githubusercontent.com/assets/89186/12516112/9f583d7c-c123-11e5-8659-d65b344d4215.png)

**Comment by pierlo-upitup** [comment]
could you type `g v` in the browser? it should show a modal dialog with the Marathon UI version.

**Comment by bobrik** [comment]
![image](https://cloud.githubusercontent.com/assets/89186/12519134/d650a3b2-c134-11e5-890f-17f0f90f73e2.png)

**Comment by pierlo-upitup** [comment]
@bobrik thanks, we are going to look into this asap.
