### ISSUE TITLE
Add an ability to filter task list in the UI

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3000]
Sometimes I'm interested in some specific task on some specific host that is unhappy. With current task list I have an unordered sequence of tasks spanning multiple pages. I think we can improve by adding a filter. To make it nice, I think we should do fuzzy filtering when you filter on all fields (id, host, ports), just like mesos ui.
- If I want to find tasks on `myhost1`, I search for `myhost1`.
- If I want to find task on `myhost1:124`, I search for `myhost1:124`

Virtual list of tasks for filtering could contain the following elements divided by spaces:
- Task id
- Host:port pairs for all ports
- Health status (healthy / unhealthy)
- Task state (staging, running, etc.)

Adding an ability to sort by host would be nice too. It could work by adding a title for the ID column:

![image](https://cloud.githubusercontent.com/assets/89186/12354249/924b1d62-bb8c-11e5-96b4-16ddbe49738f.png)

**Comment by lhoss** [comment]
@bobrik I completely agree with you that this UI view  is way too limiting, and a filter like you propose would be nice addition 👍 
Unbelievable there was no progress on this since >1 year now :(
I created an issue (link -^)  to solve the most critical issue in our case, with the hope that this is less work and thus might be implemented faster.

ps: I think mesos, marathon... are quite nice frameworks , I'm just to grow more afraid that mesosphere(the community) cannot keep up with kubernetes.
And the UIs (marathon, mesos) are def. not getting 'enough love' . I'ld expect many more features going into the UI, that are exposed by the (REST) API's since long time.
For ex: Killing a mesos framework ..  (let me look up for an existing issue here)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2957. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
