### ISSUE TITLE
Document allocation algorithm

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3014]
I can't find any description in the docs. I think it'd be valuable for users to understand why tasks are placed on slaves the way they are placed. For instance, we have machines with fully allocated CPUs, but barely allocated memory and vice versa. Some machines get more tasks than others.

After having current algorithm documented we can start discussing possible improvements, I'm sure there are some low-hanging fruits out there :cherries: .

**Comment by meichstedt** [comment]
Hey @bobrik, there is actually not much to document as it's a randomized matching of offers to apps. Depending on the specific problems you face, you could try to solve this using constraints by placing cpu hungry tasks on agents with lots of cpus, and mem hungry tasks on others with more mem.

If you still think a documentation is worth the time, please reopen. Otherwise, feel free to open an issue and describe what you expect of the scheduling algorithm along with a few examples.

**Comment by bobrik** [comment]
I still thing that it worth to document that and I cannot reopen the issue.

> Depending on the specific problems you face, you could try to solve this using constraints by placing cpu hungry tasks on agents with lots of cpus, and mem hungry tasks on others with more mem.

I have lots of cpus and lots of memory on each box :)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3461. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
