### ISSUE TITLE
Task launch delay reset every 10 seconds

### ISSUE THREAD

**Issue by FlorentFlament** [mesosphere/marathon#3059]
TasksLaunchDelays are reset every 10 seconds by CleanupOverdueDelays
events scheduled there:

https://github.com/mesosphere/marathon/blob/v0.14.0/src/main/scala/mesosphere/marathon/core/launchqueue/impl/RateLimiterActor.scala#L50

This event triggers the cleanUpOverdueDelays method, which drops
current launchDelays information of every task, which deadline has
been reached:

https://github.com/mesosphere/marathon/blob/v0.14.0/src/main/scala/mesosphere/marathon/core/launchqueue/impl/RateLimiter.scala#L24

As a consequence, if the CleanupOverdueDelays event occurs between the
launch of a task and its failure, the task's launch delay is
reset.

The longer the task takes to fail, the higher the probability of its
TaskLaunchDelay to be reset. And if task takes more than 10 seconds to
fail, its TaskLaunchDelay is systematically reset.

This bug disables the Exponential Backoff mechanism.

**Comment by FlorentFlament** [comment]
IMO, the cleanup should only remove tasks that have been destroyed

**Comment by kolloch** [comment]
Hi @FlorentFlament,

hmmm, I am not getting it yet.

The RateLimiterActor maintains taskLaunchDelays per AppVersion: No tasks should launched before the given deadline. It then periodically removes entries which have deadlines that have been already reached. In effect, these entries should not been used.

I think the misunderstanding is how the exponential back off works. It multiplies the remaining delay with the back off factor. If there is no remaining delay, the initial delay configuration is used.

I do not like the design decision of designing it like this as you see in my comments in other issues. Our product management has not made a better task launch back-off strategy a priority, so we'll work on other important things.

Please reopen this issue if you think that my understanding is wrong.

**Comment by FlorentFlament** [comment]
Hi @kolloch,                                                                                                                                                                                                         

Thanks for your reply.                                                                                                                                                                                               

Indeed, the `taskLaunchDelays` map stores a `Delay` object per app                                                                                                                                                   
version (PathId, TimeStamp).                                                                                                                                                                                         

https://github.com/mesosphere/marathon/blob/v0.14.0/src/main/scala/mesosphere/marathon/core/launchqueue/impl/RateLimiter.scala#L20

However, the `Delay` object stores 2 things: a `deadline` and a `delay`

https://github.com/mesosphere/marathon/blob/v0.14.0/src/main/scala/mesosphere/marathon/core/launchqueue/impl/RateLimiter.scala#L79

As far as I understand, while the `deadline` becomes useless once it
has been reached (and can therefore be deleted), the `delay` is
updated by the `increased` method (at the heart of the backoff
mechanism) and needs to be kept as long as the task exists, unless a
`ResetDelay` event has been received.

https://github.com/mesosphere/marathon/blob/v0.14.0/src/main/scala/mesosphere/marathon/core/launchqueue/impl/RateLimiter.scala#L86

While the backoff mechanism may be improved (for instance by
introducing the notion of 'viability'), the current implementation
should IMO be working well enough, if the bug described in this issue
was fixed. The backoff mechanism is currently unpredictible, since the
delay is randomly reset depending on the time elapsed between the
start of a task and its crash.

I am currently working on a patch. I will try to propose an MR soon.

**Comment by FlorentFlament** [comment]
@kolloch, BTW I cannot reopen the issue. Could you please do it ?

**Comment by FlorentFlament** [comment]
@kolloch Hi,
Do you know why the `taskLaunchDelays` Map stores a `Delay` for each version of an App ? Can't we keep only one `Delay` per App ? What is the need of keeping the information for older versions, since Marathon deploys only one version of an app at the same time (except during deployment) ?

**Comment by kolloch** [comment]
# Deadline reset influences behavior

Now I get your point. Thanks for your insistence. Let me illustrate with a scenario:

(T1, T2, are points in time, one second apart)

app "/a" has backoffDuration 1 and backoffFactor 2

* T1: task for app "/a" fails => Delay(deadline = 2, delay =1)
* T2: cleanup task runs, deadline <=2 => delete delay
* T3: task for app "/a" fails => Delay(deadline = 2, delay =1)

vs

* T1: task for app "/a" fails => Delay(deadline = 2, delay =1)
* T3: task for app "/a" fails => Delay(deadline = 5, delay =2)

Basically, the cleanup code makes the incorrect assumption that delays for which the deadlines are reached have no effect anymore. I think that older code calculated the delay differently so that it was true.

We need to think about when to reset the backoff nevertheless (= when old delays have no effect anymore, not even on calculating new delays). Otherwise, we keep accumulating failures.

* T1: three tasks for app "/a" fails => Delay(deadline = 5, delay = 4)
* [no more task failures, lots of working task starts]
* T1000000: task for app "/a" fails => Delay(deadline = T1000008, delay = 8)

In the past, we used to reset the delay for one "TASK_RUNNING". That's not cool because if you have flipping tasks that run for a couple of seconds and then fail fast, you will relaunch them very fast.

# Versioned entries in RateLimiter

One of the reasons is the possibility to stop/revert deployments.

**Comment by FlorentFlament** [comment]
@kolloch Thanks for the clarification of the issue. I agree that it would be better to reset the backoff at some point to avoid falling in your 3rd scenario. We could do so by introducing of the notion of viability as described in tickets #1504 & #1111 .

A solution could be to update the periodic cleanup to remove from `taskLaunchDelays` entries corresponding to apps running for more than a fixed 'viability' duration.

I can try to implement this if you think this is the way to go.

**Comment by FlorentFlament** [comment]
The following merge request handles this issue:
https://github.com/mesosphere/marathon/pull/3099
