### ISSUE TITLE
Inactive Tasks still present in Marathon on hardware failure without healthcheck

### ISSUE THREAD

**Issue by Project0** [mesosphere/marathon#3080]
It seem marathon doesnt sync task status with mesos. I have seen this on apps without health checks which are in an unknown health status. They are still shown as running instance in marathon if the slave/master goes down and the tasks/instance are note alive anymore. Mesos recognise its, but marathon doesnt seem to know that the instance is destroyed and should be re deployed on other slaves.

Reproduce: 
- 3 Node Cluster each with Mesos master/slave ZK and marathon
- deploy app without health check
- Shut down master instance
- Instance on "failed" slave still shown as running (but unknown)

**Comment by kolloch** [comment]
If you say that you "Shut down the master instance", do you mean the Mesos master? If that's true, then the behavior is not very suprising. All communication to Mesos is channel via the Master. Marathon has no chance to know that the status of a task is updated if the Mesos master is down.

Furthermore, for clarification,

* What do you mean by "Mesos recognise[s] its [= this?]"?
* You write "slave/master goes down and the task/instance are not[e] alive anymore". What do you mean exactly?
* Which version of Mesos/Marathon are you using?

Please reopen with clarifications.

**Comment by Project0** [comment]
- What do you mean by "Mesos recognise[s] its [= this?]"?
I mean, master with slave (multi role) goes down and a new master has been elected, The tasks off this node are gone (I cant see them on the UI), but marathon does not redeploy the apps (Still shown as running). 

- "You write "slave/master goes down and the task/instance are not[e] alive anymore". What do you mean exactly?" 
They does not exists anymore for mesos

Running with Mesos 0.26.0 and marathon 0.14

**Comment by kolloch** [comment]
The problem is that in this setting the missing tasks are only detected by reconciliation. (http://mesos.apache.org/documentation/latest/reconciliation/)

As far as I know, Mesos will not report the task as `TASK_LOST` until it hit a timeout and does not wait for the slave to recover anymore. Up till then it doesn't report any status, so that Marathon cannot act upon this. After it has determined that slave is lost AND Marathon performs a reconciliation, the tasks should be reported with `TASK_LOST` and removed in Marathon. Depending on Mesos/Marathon configuration, this may take >10-20min.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4674. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
