### ISSUE TITLE
Safe-guard for migrations

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3085]
We had several problems with interrupted/failing migrations.

It would be nice
- if we created a backup of the state before the migration.
- if the migration failed and our upgrade guide is followed, an instance of the old version of Marathon takes over with the old state.
- the user could also rollback manually to a backup.

Furthermore, with this infrastructure, we should prevent old versions of Marathon working on the migrated state since there interaction might corrupt it (Marathon shouldn't start up if the the ZK state is not compatible #3004). Since this is currently the only way to recover from migration failures (other than restoring a manual ZooKeeper backup), we can't do that without another rollback mechanism in place.

**Comment by gkleiman** [comment]
Related to #3005 and #3004

**Comment by unterstein** [comment]
I started implementing this issue in https://github.com/unterstein/marathon/tree/fixes/3085_migration_safe_guard by enhancing the ```Migration``` class with the backup functionality and the indicator ```migrationInProgress```. There are some TODOs left, but hopefully you get the idea :)

**Comment by unterstein** [comment]
Hi Gastón,

like we discussed i implemented the restoreBackup functionality and solved some TODOs. I did this in a separate branch (https://github.com/unterstein/marathon/tree/fixes/3085_migration_safe_guard_2), because i did some "awaiting-madness" and i am not sure if this is correct. Maybe you could have a look and enhance this.

Same at the #startMigration functionality, where i think this check should be done in mockito, but didn`t know how to do it.
Intention: The first time store.load(migrationInProgressName) should return nothing and on the second call it should return the marker object. Is this possible?

Cheers
Johannes

**Comment by gkleiman** [comment]
@unterstein thanks for continuing working on this! I'll try to take a look at the new branch later this week.

Regarding the mocking/testing issue, it should be possible using: https://mockito.googlecode.com/hg-history/1.6/javadoc/org/mockito/InOrder.html

**Comment by unterstein** [comment]
@gkleiman i solves the mockito issue through giving a list of results during the "results" helper, see MigrationTest#addBackupToFixture

Maybe you could have a look at the "waiting-madness". At some points synchronization is needed, but i believe these are too much waitings...

I also added the restore of the backup and a cleanup of the current zookeeper state.
I believe that https://github.com/mesosphere/marathon/issues/3004 should be solved, caused by the MigrationFailedException in Migration#startMigration and therefore no starting of marathon in this incompatible state.

Missing (maybe): Some functionality to reset migrationInProgess indicator automatically. Tried to handle this through text in exception message, saying to reset the indicator manually. Maybe you want to have an automatically reset.

Hope this helps

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2981. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
