### ISSUE TITLE
More prominent error messages if backend was unreachable

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3132]
I think that the error displayed if "apps" or "tasks" cannot be retrieved are not visible enough.

See #3093 or #3131 for screenshots.

**Comment by pierlo-upitup** [comment]
cc @leemunroe

**Comment by leemunroe** [comment]
Do [these screens](https://invis.io/CV5V1HLTR) by @cleverroffey suit this scenario?

![image](https://cloud.githubusercontent.com/assets/15963/12774433/21ba06ae-ca45-11e5-9e71-3c29776e7279.png)

**Comment by kolloch** [comment]
Yeah! Thanks for your quick response.

* Can I expect the UI recover automatically when the backend becomes available again and "Refresh" is just a way to speed things up?
* I wonder if we should explain the problem more? Or differently? To clarify that it is a communication problem between UI and Backend? (But that is probably not part of this ticket)

**Comment by pierlo-upitup** [comment]
@leemunroe @kolloch 
we attempted this solution already but had to pull back and restore the "error rows" because the error messages as portrayed in the mockups did not take into account that they can coexist with non-empty lists. This:

https://cloud.githubusercontent.com/assets/859154/12237696/43c632da-b880-11e5-8fee-92316bb49a65.png
![image](https://cloud.githubusercontent.com/assets/1078545/12776399/faaa83a2-ca55-11e5-8c14-bcdbd0d3ac33.png)

Please refer to https://github.com/mesosphere/marathon-ui/pull/535 for more info.

A simple fix would be to make the error rows more visually prominent (red text?). A better fix would be to have a notification system/banner at the top of the page that persists until the error is resolved.

**Comment by kolloch** [comment]
Also "Error Fetching Applications" if you see some is confusing. It should say "Error Refreshing Applications" or something like this and that case.

**Comment by gkleiman** [comment]
What about showing a big error on top of the current view?

Example:

<img width="1440" alt="screen shot 2016-02-03 at 15 16 35" src="https://cloud.githubusercontent.com/assets/146374/12784752/45cb910e-ca89-11e5-887f-a0f540ed4f2a.png">

**Comment by pierlo-upitup** [comment]
thanks for the input guys - i know that @leemunroe is going to work on some ideas for this

**Comment by leemunroe** [comment]
Makes sense. Created a Jira to track this [MARATHON-788]. We'll explore some ideas.

I like @gkleiman's idea, although it would be nice if the user was still able to view what has already loaded.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3015. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
