### ISSUE TITLE
suspend add can not restart

### ISSUE THREAD

**Issue by fanzhiwei2015** [mesosphere/marathon#3167]
Version 0.15.0

I use Marathon to create a very simple app, and suspend it, then I can not restart it. it's always in suspend state.

**Comment by gkleiman** [comment]
"Suspending" an application from the UI scales it down to 0 instances. When you click on "restart", Marathon will try to restart all tasks, but because there are no running tasks, it will do nothing.

What you have to do is scale it up to 1 or more instances.

cc/ @pierlo-upitup @leemunroe as I think there's room for improvement in the UX

**Comment by pierlo-upitup** [comment]
Oh, good point. `suspend/restart` can definitely be cause of confusion, as the terminology suggests a `pause/play` kind of interaction.

**Comment by leemunroe** [comment]
Thanks @fanzhiwei2015 

What would be the better behavior here?

I have an app at 3 instances, I hit suspend, then I hit restart
  1. App starts up with 3 instances
  1. Modal dialog appears and asks "How many instances do you want to scale to?"

**Comment by gkleiman** [comment]
Option 3: If an app is suspended, then the "restart" button should be hidden/disabled.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2858. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
