### ISSUE TITLE
Strange flip in metrics

### ISSUE THREAD

**Issue by fengyehong** [mesosphere/marathon#3237]
I have a test cluster with constant resources, marathon with constant tasks, so I expect metrics incomingOffers to be constant(relatively). (All slaves run stably, no task fail, restart, no new task launch happen during test)
But my metrics showed on graphite is strange, incomingOffers flip periodically !!!
![2016-02-02 09-33-37](https://cloud.githubusercontent.com/assets/12654661/13042994/25061676-d400-11e5-8c91-b79e28428a7c.png)
red: incomingOffers.m1_rate,  green: incomingOffers.m5_rate,  blue: incomingOffers.m15_rate

![1](https://cloud.githubusercontent.com/assets/12654661/13042986/05bd6e22-d400-11e5-9b59-676909f03378.png)
incomingOffers.m15_rate

I don't know how to explain this. 
Anyone have the same problem? Any ideas why this happens? 

Environment: 
Marathon version: 0.11.1 with graphite reporter cherry-picked
Mesos version: 0.25.0
marathon decline_offer_duration: 120s

Thanks.

**Comment by philipnrmn** [comment]
Hi @fengyehong, thanks for the interesting question. I'll have to do some digging on how Mesos allocation cycles work to get you a full answer. 

Just to clarify, are you seeing any aberrant behaviour? Why do you regard this as a problem?

**Comment by philipnrmn** [comment]
Just had a chat with @gkleiman who kindly clarified a few things for me. Basically there are two slightly odd things about what you're seeing. One is the regularity of the shape, which you wouldn't normally expect. The other is the length of time over which the offers increase - this would normally be rather shorter. 

However without knowing more about your environment and workload, it's hard to say whether these numbers are unexpected.

**Comment by fengyehong** [comment]
Thanks, @philipnrmn 
My environment has three nodes, A, B, C
`A,B,C` construct a zk cluster, used by mesos and marathon
`A,B,C` works as mesos master
`A,B,C` works as mesos slave
`A` works as Marathon master, in ha mode

Mesos: 0.25
Marathon: I cherry-picked graphite reporter to 0.11.1, changed [report rate](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/metrics/MetricsReporterService.scala#L58) to TimeUnit.MINUTES, report interval is 60s
Graphite: retention with each point represents 60s

OS: Openstack VM Centos 7-1503, no ntpd service running

I think the workload is fairly low:
a. the cluster is untouched several days, so no manual operation
b. there are three httpd containers running in docker, with only workload from health check(with default interval 10s)

**Comment by fengyehong** [comment]
> Just to clarify, are you seeing any aberrant behaviour? Why do you regard this as a problem?

1. And i didn't notice any aberrant behavior, everything looks good : (
2. Honestly, i don't know whether this is a problem, i just noticed it and confusing~~

**Comment by jgarcia-mesosphere** [comment]
Hi!

I think this is a normal pattern for the interaction of Marathon and Mesos, so there is no cause to be concerned. Please allow me to explain:
- Mesos sends offers to Marathon in batches, and Marathon will decline unneeded offers. The first batch represents every resource in the cluster.
- When modern versions of Marathon decline offers, they apply a filter against that agent to exclude all offers from that agent for several minutes (default 120 seconds).
- When a new Deployment is detected, Marathon will revive all offers, allowing the whole batch of agents to make new offers.
- Marathon will dispatch tasks as needed against these revived offers. All unused offers are declined, and the agents which declined offers come from are filtered.
- In the event that the deployment continues (i.e. there's more tasks in the deployment than can be assigned in a single offer), more tasks will be launched on the remaining (read: not yet filtered) agents.
- This cycle continues until all tasks in the deployment are dispatched. As you can imagine, each offer round will contain fewer agents, as incrementally more agents have been declined in each previous round. This causes the "draining" effect.
- After the `decline_offer_duration` you should see a spike of new offers come in, and each offer cycle thereafter will contain fewer.
- Because Marathon is able to revive offers (meaning remove its agent filters from Mesos), it can be sure that any dormant or filtered offers can be renewed almost instantly.

Let us know if you have any other questions.

**Comment by fengyehong** [comment]
Hi, @jgarcia-mesosphere 
1. In my case, as marathon is left untouched, no revive offer happens.
2. Just a remind, the flip cycle is about 24 hours, far greater than decline_offer_duration(120s)
3. The shape is not a "draining" effect, it goes to the contrary

**Comment by jgarcia-mesosphere** [comment]
There is no expectation that this value will be consistent at this time. The graphs you've shown are consistent with a normal, healthy cluster.

1. Filters expire, even in the absence of revive offers.
2. We have no evidence that your `decline_offer_duration` is set to Marathon's default; many users set it to several hours or even days.
3. The specific direction of motion will vary depending on the way that deployments have been done in a cluster as well as the cluster size.

It's not unlike throwing a rock in a still pond - there will be ripples that bounce out in patterns, and they will rebound from the walls of the pond and make more patterns. In our pond, however, there's no natural friction to moderate these ripples, so they continue forever (or until `revive_offers` occurs, of course).

**Comment by fengyehong** [comment]
1. I just noticed `com.codahale.metrics.Meter.m##_rate` is not a simple moving average(SMA, which i expect), it is an exponential weighted moving average(EWMA), used for performance measurement

2. In my test case I expect offer receiving rate to be constant, I mean SMA. I'm now using graphite function to calculate my SMA, like: `?target=movingAverage(derivative(***.incomingOfferCpus.count), my_decline_offer_duration)`

3. By now, I'm not very sure about the `accurate` meaning of incomingOffers.m##_rate

Thanks for replying, everyone.
