### ISSUE TITLE
Task with a static port cannot be restarted

### ISSUE THREAD

**Issue by PiotrTrzpil** [mesosphere/marathon#3287]
Running mesos 0.28.0 and marathon 0.15.2

After initiating app restart (through the UI or API), the app is left in Waiting state and is not restarted (Deployment action 'RestartApplication' stays active). 

app port mappings:
```
    "portMappings": [
      {
        "containerPort": 9030,
        "hostPort": 31110,
        "servicePort": 10011,
        "protocol": "tcp"
      }
    ],
```

In the logs:
```
Feb 20 13:12:13 mesos marathon[1033]: ... INFO Offer .... Cannot find range with host port 31110 for app <app-info>
Feb 20 13:12:13 mesos marathon[1033]: ... INFO Offer .... Insufficient resources for ...
```

However when manually scaling down to 0 and then scaling up, the app is successfully restarted.
So it seems like the new task is trying to be started before the previous one is killed and frees resources (the port)

**Comment by philipnrmn** [comment]
Hi @PiotrTrzpil,

This can occur if you only have one agent with this port available. 

Marathon's standard deployment process is to create a new instance of your application, ensure that it is healthy, and then kill the old task. If a specific port is requested, you'll need more than one agent with this port available. Otherwise, Marathon will never kill the original task. 

Assuming this is the problem, you can resolve this by setting a custom upgrade strategy with a minimum health capacity of zero. You will of course encounter downtime this way. 

There's a lot more information here:
http://mesosphere.github.io/marathon/docs/deployments.html

**Comment by PiotrTrzpil** [comment]
Thanks @philipnrmn! I indeed missed that page.
Yeah, that make sense, I guess it could use a bit more feedback (e.g. Marathon diagnosing that particular repeating insufficient resources issue as being related to minimumHealthCapacity and giving some info). 
Will tinker some more, thanks;)

**Comment by philipnrmn** [comment]
Thanks for the update!
