### ISSUE TITLE
Specific role required by app is not matched by default resource role: "*"

### ISSUE THREAD

**Issue by PiotrTrzpil** [mesosphere/marathon#3290]
(using playa-mesos with latest marathon and mesos)

After installing marathon-lb using dcos cli:
`dcos package install marathon-lb` 
I noticed that marathon indicates insufficient resources error. After some investigation, the reason seems to be that marathon-lb requires role 'public_slave', but my mesos slave's resources are declared with default role: *

<img width="492" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6235999/13206010/8df6dffc-d8ed-11e5-9960-46d395865cbb.png">

After looking in the marathon code, I noticed that in that situation the resources are indeed not matched. In the following line, the role set will then contain only roles declared on app, skipping defaults: `config.defaultAcceptedResourceRolesSet` which include the default * role.
https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/mesos/TaskBuilder.scala#L30

I'm not sure if this is maybe by design? Perhaps the spefic role the app requires just has to be available in mesos (and not in the pool of unassigned resources)?

If this is indeed a bug, I would be happy to provide a PR.

**Comment by orlandohohmeier** [comment]
Hi @PiotrTrzpil thank you for your interest! The described behaviour is by design. Marathon will *only* considers resource offers with roles defined in the `acceptedResourceRoles`. "If you do not specify this [list], Marathon considers all resource offers with roles that have been configured by the `--default_accepted_resource_roles` command line flag"¹ This enables users that might want to "reserve" a share of their resources for the role "production" to ensure that other tasks do not consume all resources. 

> Example 1: "acceptedResourceRoles": [ "production", "\*" ] Tasks of this app definition are launched either on "production" or "\*" resources.

> Example 2: "acceptedResourceRoles": [ "public" ] Tasks of this app definition are launched only on "public" resources.

If you have any further questions please don't hesitate to ask! 

/source https://mesosphere.github.io/marathon/docs/rest-api.html (1,2)
