### ISSUE TITLE
how to make app not to migrate automatic?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3320]
after deployment,  how to make app not migrate automatic?

thanks!

**Comment by orlandohohmeier** [comment]
Hi @junneyang could you please explain what you mean with "migrate automatic"? Thanks!

**Comment by junneyang** [comment]
for example: if one host crash, the apps on it migrate to other host automatically.
or for other reasons(i don't know exactly) the app migrate to other host automatically.

**Comment by orlandohohmeier** [comment]
Hi! Marathon will start a new instance/task, whenever an application instance fails and will always make sure the requested number of instance is running. This is one of the key concepts. 
You can use constraints, if you want Marathon to (re)start your instances on a specific host/node instead of the next matching Mesos resource offer. The following constraint, for example, will tie an application to a specific node. 

```
$ curl -X POST -H "Content-type: application/json" localhost:8080/v2/apps -d '{
    "id": "sleep-cluster",
    "cmd": "sleep 60",
    "instances": 3,
    "constraints": [["hostname", "CLUSTER", "a.specific.node.com"]]
  }'
```

For details please refert to https://mesosphere.github.io/marathon/docs/constraints.html

**Comment by junneyang** [comment]
thanks , i see.
