### ISSUE TITLE
Port indices notation in validation errors is not consistent

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3339]
- In some cases Marathon will use parentheses to index validation failures, in other cases it will use square brackets.
- Paths sometimes have a leading slash, but they sometimes don't.
- Paths are sometimes separated by slashes, sometimes by periods.

Some examples:

```json
{
    "details": [
        {
            "errors": [
                "Constraint definition must be an array of strings in format: <key>, <operator>[, value]"
            ],
            "path": "/constraints(0)"
        }
    ],
    "message": "Invalid JSON"
}
```

```json
{
    "details": [
        {
            "errors": [
                "URI has invalid syntax."
            ],
            "path": "fetch[0]"
        }
    ],
    "message": "Object is not valid"
}
```

```json
{
    "details": [
        {
            "errors": [
                "error.path.missing"
            ],
            "path": "/fetch(0)/uri"
        }
    ],
    "message": "Invalid JSON"
}
```

```json
{
    "details": [
        {
            "errors": [
                "got -1, expected 0 or more"
            ],
            "path": "portDefinitions[0].port"
        }
    ],
    "message": "Object is not valid"
}
```

The schema should be consistent. Until v0.15.0 we were always using parentheses, I think we should go back to that.

To find the affected validations, look for usages of the `every` validator.

cc/ @aldipower @alexanderweber

**Comment by aldipower** [comment]
Thanx for describing the issue.
In the meantime I will write something workarounds in the UI to handle this. :)

**Comment by aldipower** [comment]
![nonsense](https://cloud.githubusercontent.com/assets/859154/13321446/5051edd8-dbcf-11e5-9db0-f68475529d9e.png)

Also ```path: "apps[2].container.columes[1].value"``` is confusing if I only have one app defined.

**Comment by aquamatthias** [comment]
@aldipower this problem you posted here only exists during development. This will not a problem for released versions.

**Comment by aldipower** [comment]
@aquamatthias OK, I see, easy going.

**Comment by alexanderweber** [comment]
@aldipower regarding your example - the object being validated here is probably a group, being the root object of validation. We decided not to prepend this information as described in #3255. Here the explicit error path would be:
```
/apps(2)/container/volumes(1)
```
That is why the index information 2 might be used in order to find the affected app in first place, namely being the third application in the group.

@aquamatthias I am about to change the scheme as following:

1. replace `[` `]` with `(` `)` respectively
2. replace `.` by `/`
3. prepend `/` at the root of each path. This would also replace `self` with `/` in root-only errors

cc /@pierlo-upitup point 3 is sort of conflicting with what we agreed on in #3255. Let me know if you have different thoughts on that one.

**Comment by pierlo-upitup** [comment]
@alexanderweber  btw, as I mentioned in the original PR  do you think these changes should be documented in the official docs?

**Comment by alexanderweber** [comment]
@pierlo-upitup Thanks for pointing that out. I did adjust documentation as mentioned #3387.
