### ISSUE TITLE
Marathon should always convert docker image tags to image IDs

### ISSUE THREAD

**Issue by cmaloney** [mesosphere/marathon#3364]
Lots of users go straight to docker tags (:latest) and forcePullImage to make things re-deploy when they do updates. This bypasses Marathon's ability to do things like rollback.

It would be great if Marathon would always resolve a docker tag to a Docker ImageId, and only launch Mesos tasks using the ImageId. In this way, Marathon always knows exactly what is running on every host (The ImageId is based on the contents of the docker container), and it's possible for users to keep using tags to track "channels" effectively while getting good deployment / redeployment behavior, with a simple upgrade path for getting of labels if they ever want more fine grained control.

ref: #2360, #880, #943

**Comment by kolloch** [comment]
In general, I think that users should really use image IDs or unique tags for their images. So I see where you are coming from.

Your proposal means that we would have to implement docker registry resolving. If the user uses its custom registry, that might get pretty tricky. Also one would have to define when to refresh the image ID. do you want to do it on restart? On redeploy? It is not clear.

E.g. if you do it on redeploy, this could make deployments that were really cheap before (because nothing changed), expensive. Both in terms of time that Marathon spends on resolving docker images and in total process restarts in the cluster.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4701. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4701. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
