### ISSUE TITLE
orphaned app when canceling destroy deployment in Version 0.15.3

### ISSUE THREAD

**Issue by spacejam** [mesosphere/marathon#3488]
steps:
1. create app
2. destroy it (removes it from applications view)
3. cancel its destruction before it completes (removes it from deployments view)

all un-destroyed tasks for the app are currently orphaned, still running in mesos

**Comment by kolloch** [comment]
When the periodic task reconciliation detects this, the orphaned app tasks will be killed. See [command line flags](https://github.com/mesosphere/marathon/edit/master/docs/docs/command-line-flags.md).

> * `--reconciliation_initial_delay` (Optional. Default: 15000 (15 seconds)): The
>    delay, in milliseconds, before Marathon begins to periodically perform task
>    reconciliation operations.
> * `--reconciliation_interval` (Optional. Default: 600000 (10 minutes)): The
>    period, in milliseconds, between task reconciliation operations.

I don't really see how we can do that much better in our current model except disallowing canceling deployments. Or what would you like to see happening?

**Comment by spacejam** [comment]
When I think of cancelling a destructive task, I expect that further destruction will be averted. Would it be quite complex to convert the destroy deployment into a scale-up deployment back to the pre-destroy size, if it gets canceled?

**Comment by kolloch** [comment]
Our terminology with "stop" and "rollback" is confusing and not well defined.

@aquamatthias 

"stop" is actually quite unpredictable from a user perspective since it will not change the definition of the goal state back to what was there before the deployment. It will not prevent Marathon from converging to the goal state (as expressed in the app definitions) some time later. A potential fix would be to allow all intermediate states (2 tasks with version A, 3 tasks with version B, ...) be represented as a goal state and therefore "stop" could just define the current state as the goal state. This would be quite a major change and I am not sure if it is the "right" (TM) way.

"rollback" is better defined. It will create a deployment which reverts the effects of the current deployment and therefore the new goal state is the one before the deployment for the affected applications.

I fear that there is some serious thinking necessary how to represent deployments and how to control them. Don't see any quick fixes :( Sorry.

**Comment by aquamatthias** [comment]
`stop` is a battleaxe functionality - we have removed it from the UI and we should also think about removing it from the API.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1707. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
