### ISSUE TITLE
Marathon editor sometimes corrupts container port assignments after edits (video)

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#3595]
This is an issue I've been encountering with Marathon `1.0.0RC1`; after a couple of edits, Marathon will swap the container ports for the service ports. I've caught it red handed with a 3 minute recording of a clean install of Marathon 1.0.0RC1 and Mesos 0.28.0.

It's a bit finicky and I don't know exactly how to reproduce it, but, as seen in the video, it's often enough that I can reproduce it with enough fidgeting.

http://screencast.com/t/ez8RvdcE4

**Comment by googoid** [comment]
+1, it does!

It happens after you open the configuration editor and save it without changing the port. If not from the first time, from second it does for sure.

**Comment by pierlo-upitup** [comment]
@timcharper @googoid thanks for reporting this. We're working on a fix.

**Comment by pierlo-upitup** [comment]
Adding some context FTR.

When creating a docker container with `BRIDGE` networking, Marathon will expose the `container.docker.portMappings{index}.servicePort` as  `portDefinitions{index}.port`, instead of `hostPort` as previously assumed. This means we cannot use the `portDefinitions` to re-populate the `portMappings` when editing, as it will effectively overwrite the `containerPort` with the `servicePort` value as reported in the issue.

We are going to issue a quick bugfix release shortly that – for the time being – suggests using the JSON editor when creating or editing the app definition with a docker container in  `BRIDGE` mode.

cc @aldipower
