### ISSUE TITLE
Improve documentation for persistent volumes

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#3627]
The documentation we have is not sufficient:
- how to setup mesos/marathon in order to use this feature (flags)
- explain principal
- does the example work? (should it be RELAUNCH_AFTER_TIMEOUT)

**Comment by aquamatthias** [comment]
@joerg84 can you try an example as described in the docs to see what is missing? Thanks!

**Comment by diatmpravin** [comment]
Potential Pitfalls[https://mesosphere.github.io/marathon/docs/persistent-volumes.html]
Replication and Backups

Because tasks are pinned to nodes, your data can be lost if the node is lost = What's it mean? 

Use Case: My Jenkins is running on Slave1 and it's having local persistence volume. If some how, jenkins killed and bring back by marathon on same slave then will I lost all task? Please explain..
