### ISSUE TITLE
Change storage backend to use replicated log

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#364]
Move away from Zookeeper to use the replicated log provided by the latest version of Mesos.

**Comment by brndnmtthws** [comment]
:neckbeard:

**Comment by kolloch** [comment]
@aquamatthias @gkleiman @meichstedt : I would like to close this since I do not think that this is a good idea.

Some reasons:

* Our tests have shown that the replicated log has not been faster than ZooKeeper. 
* Let's use a real database instead. Mesos core competency is not providing a database.
* Familiarity: There is a lot of experience with ZooKeeper and other databases. There isn't with the replicated log solution. How do you inspect the data in the replicated log? How do you backup the data?
* The JNI interface that we would need to use has had problems in the past. One causes Marathon to crash frequently (https://github.com/mesosphere/marathon/issues/834). Another one disallows inspecting error causes. It has been reported in May but not fixed (https://issues.apache.org/jira/browse/MESOS-2718)
* It is more complicated to set up than using ZooKeeper.
* ...
