### ISSUE TITLE
Remove the Deployment Stop Button in the UI

### ISSUE THREAD

**Issue by mohitsoni** [mesosphere/marathon#3692]
When a plan is interrupted, and user chooses `Stop` operation from Marathon UI, it cancels the current deployment and leaves the scheduler in `Waiting` state. And, at this point the Marathon UI doesn't provide any additional operation to take out the underlying service from this paused state. From Marathon's perspective the deployment is done, when it's not.

Possible solution: When a plan is in `Waiting` state, one should only be allowed to perform two operations:
1. `Continue` forward
2. `Rollback` to the previous state.

There should not be a `Stop` operation, as it leads the framework in a bad state.

**Comment by aquamatthias** [comment]
The stop operation is a battleaxe tool that should only be used, if you are absolutely sure what you are doing. It literally stops all running deployment actions. 
In that sense, what you describe is expected behavior and not a bug.

But I totally see your point, that it is too easy for users to screw things up.
My proposal would be to remove the Stop Button completely from the UI.
It is the plan for the unified UI anyways.
