### ISSUE TITLE
Confusion about mesos role and default accepted roles

### ISSUE THREAD

**Issue by hellertime** [mesosphere/marathon#3722]
I'm noticing an issue with my running installation of Marathon 0.13.0.

I have started up marathon with the following flags `--mesos_role other --default_accepted_resource_roles *`.

I created an app, with the 'acceptedResourceRoles' value set to `*`, but when it starts it appears to get a port resource assignment in the 'other' role (verified by looking at `/master/roles.json` on the mesos master  -- mesos v 0.22.2).

First. Am I seeing an issue here, or are things actually working as expected, and its my model of how things should be that is wrong?

And if it is an error, is it one of configuration or is this a known issue -- I didn't see an existing issue, but perhaps its not an obvious problem I'm encountering.

In general I'd like to ask for some clarity on the idea of `--mesos-role` and `--default_accepted_resource_roles`. If I understand correctly, without `--mesos-role` set the framework and all tasks will only accept offers of role `*`, with it set you gain the ability to also start tasks in the role passed as the argument to `--mesos-role`, but that is the limit currently -- up to two possible roles to accept offers from, right?

**Comment by meichstedt** [comment]
Hey @hellertime can you please post your AppDefinition?

**Comment by hellertime** [comment]
I'll produce a pared down version, sans env vars and the like:

```
{
                    "instances": 1,
                    "container": {
                        "docker": {
                            "network": "HOST",
                            "image": "my_app:1.0"
                        },
                        "type": "DOCKER"
                    },
                    "id": "my_app",
                    "cmd": "/run.sh",
                    "contraints": [
                        [
                            "hostname",
                            "UNIQUE"
                        ]
                    ],
                    "cpus": 2,
                    "mem": 1024
                }
```

**Comment by meichstedt** [comment]
Yeah that's fine, but to make sure we can reproduce this you should at least add the ports-section.

To answer your questions in between:

1. If you set `--mesos_role other`, Marathon will register with Mesos for this role – it will receive offers for resources that are reserved for this role, in addition to unreserved resources.
1. If you set `default_accepted_resource_roles *`, Marathon will apply this default to all AppDefinitions that do not explicitly define `acceptedResourceRoles`. Since your AppDefinition defines that option, the default will not be applied (both are equal anyways).
1. If you set `"acceptedResourceRoles": ["*"]` in an AppDefinition (or the AppDefinition _inherits_ a default of `"*"`), Marathon will only consider unreserved resources for launching of this app.
1. In fact, the current limit is **one** role – a Mesos Framework can only register for one role, and will always receive offers for unreserved resources (I figure it feels like two roles, but unreserved resources are actually not reserved, so not associated with a role).

As far as I can tell, Marathon should not launch your app on a `"other"` resource – and the code of 0.13 looks correct to me at a first glance. @gkleiman pointed out that a Mesos agent does not complain if you declare ports bot both `*` and `other`. Can you look for line like
```
slave.cpp:463] Slave resources: ports(*):[500-505]; ports(foo):[500-505]; cpus(*):8; mem(*):15360; disk(*):470816
```

So there our agent will offer ports `[500-505]` both as unreserved as well as statically reserved for `foo`. Haven't tested how that turns out in practice, but please provide your Mesos master and agent configuration as well.

**Comment by hellertime** [comment]
I'm not sure what you mean to "add the ports-section". I'm not actually asking for ports with this app config, marathon is just grabbing a port anyway. The more interesting issue isn't that the port gets associated with the 'other' role, but that the cpu get allocated from there. Thats more problematic.

Here is the master config for roles:

`export MESOS_ROLES="*,other"`

Here is the slave config:

`export MESOS_RESOURCES="ports(*):[10000-20000,31000-32000];cpus(*):2;mem(*):3072;cpus(rum-collector):4;mem(other):1024;ports(other):[25000-26000]"`

**Comment by hellertime** [comment]
I just discovered that, at least in mesos 0.22.2, if a framework registers with mesos with a specific role, and it accepts offers from the * role those resources get reported under the role which the framework registered, not under *. Which is very likely what I'm seeing here.

**Comment by meichstedt** [comment]
@hellertime I wasn't aware that your CPU gets allocated from the `other` share, you didn't say so in your initial issue description and was assuming that your AppDefinition actually requests a port (you can Marathon prevent from doing that by defining `"ports": []` btw ...)

Now I realized that you rely on information as queried via `/master/roles.json`. I've checked back with the Mesos team re: this. This endpoint only serves information from a `roles -> framework` perspective. That means, what you see there is a listing of known roles, the frameworks registered with these roles, and _the total allocated resources for each **framework**_ disregarding the role. The docs on this endpoint are a little unclear.

So, yes, you understood the matter correctly, but you cannot read the actual resource allocation from the roles endpoint. Does that cover all your questions?

**Comment by meichstedt** [comment]
Oh I just saw your message from Saturday – exactly, this is still the case. Feel free to open a docs issue in Mesos so they may document this better …
