### ISSUE TITLE
Support for arbitrary resource types

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#375]
Apache Mesos allows user-defined resource types via the  
`--resources=name(role):value;name(role):value...`  
argument to the `mesos-slave` program.  It would be great if there were a way to require these as part of an app's definition in the Marathon API, in addition to the standard resource types (`cpus`, `mem`, `disk`, `ports`) already supported.

**Comment by syogesh** [comment]
Is anyone working on this? If not I would like to take this up. Is there anything I need to know before I start?

**Comment by ConnorDoyle** [comment]
That's great!  Nobody is currently working on this (so far as I know).  You might save some time by posting your plan and some proposed API examples before you begin hacking.

**Comment by syogesh** [comment]
I might only have time to add support for scalar custom resources is that alright? 

*Basic Plan*
AppDefinition will get a customResources map that maps from resourceName to value. ResourceMatcher will check that the app's custom resources exist in the offer.

*API Example*
The API change will be minimal. Like cpus and mem, there will be an additional key "customResources" on the create /v2/apps POST request that maps from resource name to value. Ex:

{
    ...,
    "cpus": 2.0,
    "customResources": { "bandwidth": 100, "foo": 2 },
    ...
}

**Comment by syogesh** [comment]
Here's an alternate format which is much more extensible and supports the other resource types:

```
"customResources": [
                    {
                        "name": "foo",
                        "type": "scalar",
                        "value": 100.0
                    },
                    {
                        "name": "bar",
                        "type": "range",
                        "value": [100, 200]
                    }
]
```

**Comment by kolloch** [comment]
That looks pretty good. The range resources can specify multiple ranges, though.

**Comment by syogesh** [comment]
Ah, okay. Also I want to change the format to make it more concise, have a structure similar to Resources, and not have to deal with the same key having multiple possible types. How about this: 
```
"customResources": [
                    {
                        "name": "foo",
                        "scalar": 100.0
                    },
                    {
                        "name": "bar",
                        "range": [[100, 200], [300, 400]]
                    },
                    {
                        "name": "foobar",
                        "set": ["a", "b"]
                    }
                   ]
```

**Comment by kolloch** [comment]
Ranges are difficult. What are the use cases besides ports? Maybe IPs?

Anyways, I stick with the port use case for now, even though I am not sure that it generalizes to other use cases.

In the port use case, you want to be able to choose specific ports (e.g. 8000) or  you want to be able to just get some ports with any values (you basically view the ranges as a set from which you take some items).

Furthermore, you might even want something like "take any port from the range 31000:32000" to not take ports that are reserved for specific applications.

In the notation I am torn between conciseness and clarity. You could write specific ranges with a colon `"31000:32000"`, with arrays `[31000, 32000]` or very verbose `{"from": 31000, "upTo": 32000}`.

**Comment by ConnorDoyle** [comment]
@kolloch -- let's be explicit!

What do you guys think about this format?

```json
{
  "id": "arbitrary-resource-example",
  "cmd": "./run.sh",
  "cpus": 2.0,
  "mem": 2048.0,
  "urls": ["http://files.my.org/program.tar.gz"],
  "otherResources": {
    "foo": {
      "scalar": {
        "value": 100.0
      }
    },
    "bar": {
      "set": {
        "value": ["a", "b", "c"],
        "acquire": "any|all"
      }
    },
    "baz": {
      "range": {
        "value": [
          {
            "begin": 100,
            "end": 200,
            "numberToAcquire": 5
          },
          {
            "numberToAcquire": 3
          }
        ]
      }
    }
  }
}
```

**Comment by syogesh** [comment]
Looks good to me

**Comment by syogesh** [comment]
I was planning on adding this to the marathon.proto file. I tried to avoid it to keep it simple but seems necessary. Is this alright?
```
message CustomResource {
    required string name = 1;

    message CustomScalar {
        required double value = 1;
    }
    optional CustomScalar scalar = 2;

    message CustomRanges {
        message CustomRange {
            required uint64 numberRequired = 1;
            optional uint64 begin = 2;
            optional uint64 end = 3;
        }
        repeated CustomRange value = 1;
    }
    optional CustomRanges range = 3;

    message CustomSet {
        repeated string value = 1;
        required uint32 numberRequired = 2;
    }
    optional CustomSet set = 4;
}

message CustomResourceDefinition {
    required string name = 1;
    required CustomResource resource = 2;
}
```

**Comment by kolloch** [comment]
There is one concrete use case that I know of: GPUs. These can be modeled with a scalar custom resource. I am not aware of other use cases yet and I would love to hear about them!

I think we should aim for integration support for custom scalar resources first but keep the format extensible.

# Example for Scalar Custom Resources

```json
{
  "id": "arbitrary-resource-example",
  "cmd": "./run.sh",
  "cpus": 2.0,
  "mem": 2048.0,
  "requiredCustomResources": [
    {
      "name": "gpus",
      "type": "scalar", // not strictly necessary, we could also just look at the offer
      "amount": 16
    },
    {
      "name": "specialCpus",
      "type": "scalar", // not strictly necessary, we could also just look at the offer
      "amount": 16
    }
  ]
}
```

This feels nicer for me rather than using the resource name as object key. It allows us to have multiple requirements for the same resource which I like but I guess that subjective because it can be modeled differently. If everybody else likes the object keys, I am fine with them.

# Sets

This syntax could also be used for sets. @joerg84 came up first with this generalization.

Consider modeling GPUs by a set of GPU IDs: `["0", "1", "2", "3"]`

```json
{
  "id": "arbitrary-resource-example",
  "cmd": "./run.sh",
  "cpus": 2.0,
  "mem": 2048.0,
  "requiredCustomResources": [
    {
      "name": "gpus",
      "type": "set", // not strictly necessary, we could also just look at the offer
      "amount": 2
    }
  ]
}
```

In this case should also supply the actually assigned GPU IDs to the process as environment variables.

```bash
MARATHON_RESOURCE_GPUS="2 3" # do we want this? could lead to quoting problems
MARATHON_RESOURCE_GPUS0="2"
MARATHON_RESOURCE_GPUS1="3"
```

(I prefer the `MARATHON_` prefix over the `MESOS_` prefix because the variables are set by Marathon.)

You could extend the syntax for requiring specific GPUs:

```json
{
  "id": "arbitrary-resource-example",
  "cmd": "./run.sh",
  "cpus": 2.0,
  "mem": 2048.0,
  "requiredCustomResources": [
    {
      "name": "gpus",
      "type": "set", // not strictly necessary, we could also just look at the offer
      "value": "2"
    },
    {
      "name": "gpus",
      "type": "set", // not strictly necessary, we could also just look at the offer
      "value": "3"
    }
  ]
}
```

The environment variables would be the same in this example.

# Set-like Ranges

 Ranges as they are used as ports are basically used as a set with an efficient representation.

The type of the value attribute must be representable as `Long` otherwise we can start with the same syntax as for Sets. We can extend that as soon as we have identified concreted use cases.

Example:

```json
{
  "id": "arbitrary-resource-example",
  "cmd": "./run.sh",
  "cpus": 2.0,
  "mem": 2048.0,
  "requiredCustomResources": [
    {
      "name": "customPorts",
      "type": "range", // not strictly necessary, we could also just look at the offer
      "value": 80
    },
    {
      "name": "customPorts",
      "type": "range", // not strictly necessary, we could also just look at the offer
      "value": 443
    },
    {
      "name": "customPorts",
      "type": "range", // not strictly necessary, we could also just look at the offer
      "amount": 1
    }
  ]
}
```

That would result in the following environment variables:

```bash
MARATHON_RESOURCE_CUSTOMPORTS="80 443 12345" # do we want this?
MARATHON_RESOURCE_CUSTOMPORTS0="80"
MARATHON_RESOURCE_CUSTOMPORTS1="443"
MARATHON_RESOURCE_CUSTOMPORTS2="12345" # randomly assigned
```

Please not that our port assignment code contains logic which randomizes which port is taken for security. It leads to higher range fragmentation, though. (See https://issues.apache.org/jira/browse/MESOS-2802) Without looking at concrete use cases, it is hard to say if we want this for custom range resources or not. We could make it a flag.

**Comment by kolloch** [comment]
https://github.com/mesosphere/marathon/pull/1506 of @cinsk hints at a further use case for sets, :

```
// "ephermeral" refers to the local storage, for ephemeal purpose.
SetResource("ephemeral", Set("sdd-10", "hdd-100", "sdd-100", "hdd-80"))
```

I am not sure that I understand it. Is such an "emphemeral" resource really fully consumed by a task?

**Comment by kolloch** [comment]
There are two PRs currently which want to provide this functionality:

* https://github.com/mesosphere/marathon/pull/1506 by @cinsk
* https://github.com/mesosphere/marathon/pull/1759 by @syogesh

Both are rather big and include support for all types of resources. To repeat myself: I am not ready to have an opinion about this until I hear about use cases. Maybe @iahmedkaseb, @cinsk, @syogesh can elaborate? 

So let's restrict ourselves to scalar resources for now. What is the preferred syntax of everyone? After we decided that I would love a PR which implements exactly that syntax for scalar resources and nothing else and which consists of one commit with documentation (in the docs directory) and tests. 

We can then continue our discussion for other custom resource types.

**Comment by syogesh** [comment]
I actually only really wanted support for custom scalar resources specifically a network bandwidth scalar resource. In the discussion on how to implement it seemed like the maintainers wanted all the custom resources in one request so I implemented it. As for syntax I prefer something like this but I'm pretty flexible.
```
"requiredCustomResources": [
    {
          "name": "gpus",
          "type": "scalar",
          "amount": 16
    }
]
```

**Comment by kolloch** [comment]
Hi @syogesh, sorry for the confusion. We actually disagreed on the best first step: whether to support all custom resources or only scalar at first. If @ConnorDoyle is fine with the API format, I would love to get a PR with this (scalar resources in this format only).

Also thanks for letting us know about the use case (network bandwidth)!

**Comment by cinsk** [comment]
Sorry for late reply, I wasn't able to review this until now.

Resource matching mechanism can be tricky.  For scala resource type, it is easy,  the framework only need to subtract the requested value from the offered resource vaue.   For set or range resource types, however it need some serious matching mechanism.

For our company's purpose, we need to provide GPUs of the slaves to the application.  Each GPU is solely allocated for one task, and it is not shared among other tasks.   Due to the diversity of the GPUs, some GPUs are faster than others, and some GPU has more memory than others.

If we use scala resource type to represent GPU types, there is no way to put the speed or memory size, so that users are not able to specify them;  Users may only specify the number of GPUs.

Thus, we named each GPU with following syntax:

    gpu-xxxx-yyyy-zzzz  # xxxx for the name of the device, yyyy is the speed, and zzzz is the size of ram.

For example,

    gpu-nvidia0-1400-16   # /dev/nvidia0, 1400mhz, 16GB
    gpu-nvidia1-1200-4   # /dev/nvidia0, 1200mhz, 4GB
    gpu-nvidia2-1400-8   # /dev/nvidia0, 1400mhz, 8GB
    gpu-nvidia3-1200-12   # /dev/nvidia0, 1200mhz, 12GB

Now, we want to provide the users the ability to choose whatever GPU they wants;  some users prefer to use fastest GPU, some users may want to use GPU with huge amount of memory, etc.

To solve this requirements, we represents GPU resources using set types with above naming rule.   
The only thing must be designed is, how the user can specify their preference.  To solve this, we decided to tweak the resource requests.  Normally, if the offered resources are like:

    GPU: [ "gpu-nvidia0-1400-16",  "gpu-nvidia1-1200-4", "gpu-nvidia2-1400-8", "gpu-nvidia3-1200-12" ]

We need to handle following use cases:
- a user may want to get more than 1 GPU,
- a user may want to specify the minimum clock speed of the GPU,
- a user may want to specify the minimum amount of RAM that GPU has, etc.

The detailed formats are described in #1506.  In short,  the request may have some formatted string:

    #rN;CONSTRAINT#PATTERN

Where N represents the number of resources that the user wants, CONSTRAINTs are the condition that the user want to put (e.g. minimum clock speed, etc.), and PATTERN is the regular expression that describes the naming of the resource. 

For example, if the user want to have 2 GPU which have minimum 1400 mhz speed and the minimum 4GM rams, the user may request with following string:

    #r2;m[1]>=1400;m[2]>=4#[^-]+-[^-]+-([^-]+)-([^-]+)

`m[1]` and `m[2]` represents the subgroups of the PATTERN, `[^-]+-[^-]+-([^-]+)-([^-]+)`.

Not only considering GPUs, the concept I explained above can be used in other type of resoruces;  For example, we have customers who want to use the local disk as a whole.  Thus, each mesos-slave got attached with 8 local disks, (which we call ephermeral disks), and each disk has the type (e.g. SSD or HDD), rpms, size in the resource names.   Using above concept, the user may request with the minimum number of RPMS or types in rich ways.

**Comment by kolloch** [comment]
Hey @cinsk, thanks for the awesome explanation! Now that I understand your problem and solution better, unfortunately, I still have to think about this.

**Comment by kolloch** [comment]
Ok. It would make sense to include functionality like this in Marathon. Basically, we want to have a set of things with attributes, e.g. GPUs with mem/GHz/..., and want to match against that. Since sets in Mesos only support strings, you encode these attributes into a string and extract them with a regular expression.

In my opinion, we should at least break down the match string into JSON objects. So instead of `"#rN;CONSTRAINT#PATTERN"` we would use 

```javascript
"requiredCustomResources": [
    {
          "name": "gpus",
          "type": "set",
          "amount": 16, // corresponds to rN
          "regex": "[^-]+-[^-]+-([^-]+)-([^-]+)", // corresponds to PATTERN
          "regexMatchConstraints": { // corresponds to CONSTRAINT
             "1": {">=": 1400},
             "2": {">=": 4}
          }
    }
]
```

or better use named groups in the regular expression:

```javascript
"requiredCustomResources": [
    {
          "name": "gpus",
          "type": "set",
          "amount": 16, // corresponds to rN
          "regex": "[^-]+-[^-]+-(?<clock>[^-]+)-(?<memgb>[^-]+)", // corresponds to PATTERN
          "regexMatchConstraints": { // corresponds to CONSTRAINT
             "clock": {">=": 1400},
             "memgb": {">=": 4}
          }
    }
]
```

I am happy with the syntax for `"amount"` and `"regex"`, I am not so happy with the syntax of `"regexMatchConstraints"`, yet.

A complete alternative would be to actually use JSON-encoded data as the values of the resource set. We could then match against attributes in the JSON. I like that the attribute names are explicit if we use the approach. I dislike that the resource description is not compact anymore but pretty verbose.

**Comment by cinsk** [comment]
> I am happy with the syntax for "amount" and "regex", 
     > I am not so happy with the syntax of "regexMatchConstraints", yet.
I'm totally agree with you.   I'm also not satisfied with the ugly constraints in a string but at that time, I was unable to provide better implementation.  If you can come up with the better specification, it will be great.

BTW, there may be a requirement that need multiple contraints for 1 subgroup.  I like your JSON structure, since, it would be possible to specify more than one constraint per subgroup.  For example:

    "requiredCustomResources": [
        {
              "regex": "[^-]+-[^-]+-(?<clock>[^-]+)-(?<memgb>[^-]+)", // corresponds to PATTERN
              "regexMatchConstraints": { // corresponds to CONSTRAINT
                 "clock": {">=": 1400, "<": 2000 },  // multiple contraints are also possible.
                 "memgb": {">=": 4}
              }
        }
    ]

**Comment by ConnorDoyle** [comment]
Couple of points:

1. I prefer the more deeply nested structure I initially proposed to the flatter one in @kolloch's examples because it hews more closely to the underlying structure from the Mesos protobuf definitions.  I think it's also easier to parse and validate since the possible data for each kind of resource is namespaced.  Otherwise we'll  end up with consusing rules like "`value` is a valid key _only if_ `type` is one of `["range", "set"]`".
1. Adding this special logic to do constraint matching on strings feels like a huge hack.  Let's explore alternatives!  For example, we could add labels to resources and repurpose / augment the existing constraint machinery to do more advanced matching.

**Comment by kolloch** [comment]
@ConnorDoyle about 1.): 

I feel that having different constraints for custom resources depending on their type is a hack disregarding of the structure (deeply nested vs. flat). If we really want to include this functionality, we deviate from the path were we just logically sum up all resource requirements. We could make this work for both the nested and the flat structure though if we really want to.

about 2.)

Yes, as I mentioned above, resource sets of things with attributes would be great for this use case. But we don't have them (yet?).

So we have to balance enabling a particular use case now vs finding a better solution in the future.

Since this is the only use case that has been mentioned for set resources in this issue yet, I would either implement this solution or delay supporting resource sets until we can come up with a better solution.

**Comment by kolloch** [comment]
Another thing about 1) flat vs nested:

Food for though: The flat approach easily allows us to specify multiple constraints for the same custom resource. This would probably only make sense if we had some more complicated resource matching expressions. In the nested case, we would need a "sum" operator with further nesting.

I am not saying that one is better than we other and might be futile to talk about this without use cases but that's a difference between the approaches I can come up with.

**Comment by ConnorDoyle** [comment]
I get your point about multiple constraints per named resource.

With that in mind, how about the following?  Perhaps I under-communicated the specific nesting I like.  The motivating factor behind namespacing the constraints for each type of resource is maintaining compatibility going forward.

```
{
  "id": "arbitrary-resource-example",
  "cmd": "./run.sh",
  "cpus": 2.0,
  "mem": 2048.0,
  "urls": ["http://files.my.org/program.tar.gz"],
  "customResourceRequirements": [
    {
      "name": "foo",
      "scalar": {
        "amount": 100.0
      }
    },
    {
      "name": "bar",
      "set": {
        // TBD
      }
    },
    {
      "name": "baz",
      "range": {
        // TBD
      }
    }
  }
}
```

**Comment by ConnorDoyle** [comment]
Regarding range resources, multiple instances of this structure (as shown above) could represent any possible requirement:

```javascript
"range": {
  "amount": 3,
  "values": [
    { "begin": 100, "end": 200 },
    { "begin": 300, "end": 400 }
  ]
}
```

_Example: Acquire three items, each an element of `[100, 200] UNION [300, 400]`._

**Comment by ConnorDoyle** [comment]
Finally, I think I can live with the `regex` + `regexMatchConstraints` combo, for resources of type `set`. :+1: as long as they are introduced incrementally (as separate patches).

**Comment by kolloch** [comment]
Hey @ConnorDoyle , what are the semantics of your format? You hinted at maintaining compatibility. Can you elaborate?

BTW, I am all for separating this functionality into multiple PRs.

**Comment by ConnorDoyle** [comment]
I'm thinking specifically about representing these types in JSON:

```scala
class CustomResourceSpec(requirements: Seq[ValueSpec])
trait ValueSpec
case class ScalarSpec(...) extends ValueSpec
case class RangeSpec(...) extends ValueSpec
case class SetSpec(...) extends ValueSpec
```

This is the same reasoning that led to the structure of newer parts of the app definition (best example: `container`, `container.docker`, `container.docker.portMappings`).  In my opinion, this is one part of the API that has stood the test of usage and remained flexible enough over many months of heavy use by many organizations.

As a more concrete example, in the structure below it's unclear to me how to cleanly add support for range resources.  The main idea is that flattening / conflating concepts usually yields structures with confusing semantics that involve multiple keys.  This complicates validation, documentation, and to me, usage.

```javascript
"requiredCustomResources": [
    {
          "name": "gpus",
          "type": "set",
          "amount": 16,
          "...": [], // <= some new key to say something about the acceptable range values,
                     //    only valid if "type" is "set"
          "regex": "[^-]+-[^-]+-(?<clock>[^-]+)-(?<memgb>[^-]+)", // but this is only valid for sets
          "regexMatchConstraints": {
             "clock": {">=": 1400},
             "memgb": {">=": 4}
          }
    }
]
```

These are just the initial cross-key interactions.  What happens when we inevitably add more capabilities?

**Comment by kolloch** [comment]
Hi @ConnorDoyle, 

we are talking about two semantically equivalent syntaxes. Syntax A)

```javascript
"set": {
  // attributes valid for set
}
```

vs. B)

```javascript
{
  "type": "set",
  // attributes valid for set
}
```

Your argument is that in syntax B) it can be surprising that the semantics of the following attributes depend on the `"type"` attribute whereas syntax B) makes that more clear. It might also be easier to write JSON schemas or similar for syntax A). Thanks for explaining that. I finally got your point and I agree with you. 

I am happy with the resulting meta-structure that you proposed above:

```javascript
{
  "id": "arbitrary-resource-example",
  "cmd": "./run.sh",
  "cpus": 2.0,
  "mem": 2048.0,
  "urls": ["http://files.my.org/program.tar.gz"],
  "customResourceRequirements": [
    {
      "name": "foo",
      "scalar": {
        "amount": 100.0
      }
    },
    {
      "name": "bar",
      "set": {
        // TBD
      }
    },
    {
      "name": "baz",
      "range": {
        // TBD
      }
    }
  ]
}
```

I hope that we never feel the need to evolve this structure to accommodate "I need either this resource or that". That would probably need something like: http://docs.mongodb.org/manual/tutorial/query-documents/

**Comment by ConnorDoyle** [comment]
Awesome!  Now to write the code... :+1:

**Comment by thefourtheye** [comment]
I appreciate the effort people. Thanks for taking it up. Till it lands and gets released, is there any workaround?

**Comment by frosenberg** [comment]
Is anyone actively working on that? We have an internal need for such resource requirements in particular for GPUs and would like to avoid duplicate efforts :)

**Comment by SuperVesselExamples** [comment]
What is the working progress now?

**Comment by wrouesnel** [comment]
+1 We have a use-case where we want to manage disk resources outside of Mesos directly but be able to have tasks assigned to nodes on that basis.

**Comment by collinmsn** [comment]
What's the progress of customResourceRequirements?
We want allocation for bandwidth resource.

**Comment by jdef** [comment]
we're considering it for the v3 API. the plan to resume the design phase of
the v3 API around the end of the month/early Nov.

**Comment by duffqiu** [comment]
+1 we want to use it to limit the network resource

**Comment by andrewortman** [comment]
@jdef is there an update on API v3? Is there a draft proposal somewhere or a timeline of some sort?

**Comment by brat002** [comment]
Also interested this feature.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4572. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
