### ISSUE TITLE
Election consistency check preventing election from succeeding.

### ISSUE THREAD

**Issue by papog** [mesosphere/marathon#3798]
On a small cluster of 4 machines using 1.0RC1, the election seems to find a leader but that leader prints messages indicating it doesn't consider the result consistent.
```
Apr 18 11:01:06 traap01 marathon[55349]: [2016-04-18 11:01:06,142] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(traap01:8080) (mesosphere.marathon
.api.LeaderProxyFilter$:qtp114105\
Apr 18 11:01:06 traap01 marathon[55349]: [2016-04-18 11:01:06,398] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(traap01:8080) (mesosphere.marathon
.api.LeaderProxyFilter$:qtp114105\
Apr 18 11:01:06 traap01 marathon[55349]: [2016-04-18 11:01:06,653] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(traap01:8080) (mesosphere.marathon

```
The above message is very confusing as the leader is the machine where the check is failing and it prints its own name as the leader.

I don't see any reason why marathon would be confused by the hostname (the hostname returns the same name that marathon is using for the election and it resolves to the IP address used to communicate with the rest of the cluster.)

**Comment by pierlo-upitup** [comment]
See https://github.com/mesosphere/marathon/pull/3777

**Comment by aquamatthias** [comment]
@sttts can you look into this one?

**Comment by papog** [comment]
I have just managed to rebuild Marathon from Git. Should I try with that version instead?

**Comment by sttts** [comment]
@papog the message you are seeing (usually) means that the leadership election is not yet finished. Because Marathon usually proxies requests to the current leader, it will hold back any API requests until the leadership looks "consistent" in order to avoid forwarding in an unstable leadership state. 

Can you confirm that this message appears only for 2 or 3 seconds maximum?

**Comment by papog** [comment]
I am not managing to get any leader election to succeed. My impression is that after a number of attempts where the election is not consistent the election is stuck (everybody thinks traap01 is the leader but traap01 thinks the result is inconsistent).
When I check with the web browser I see an error message:
HTTP ERROR: 503
Problem accessing /. Reason:

    Could not determine the current leader

I am going to try again with the --hostname option.

**Comment by sttts** [comment]
@papog can you post a Marathon log of that node as a gist?

**Comment by papog** [comment]
I bounced everything, checked Mesos at port 5051 and it looks healthy.
Marathon is still refusing to serve the web page (which is not convenient, it would be nicer to have a page with the latest info on the election that is failing).
I added a log as a gist:
 [https://gist.github.com/papog/b6307408e10ea6dfb78f39658abfc0b1.js]

**Comment by willgorman** [comment]
I’ve also seen something very similar to this just recently.  We have a Mesos cluster with 3 masters running Chronos and Marathon.  (Mesos 0.28.0, Marathon 0.15.3) There was a network outage lasting about an hour and afterward Mesos and Chronos had recovered but Marathon wasn’t showing up as a framework in Mesos any longer.  Trying to load the Marathon UI on any of the nodes resulted in that same 503 error with same messages in the logs showing one of the nodes as the leader but that node didn’t consider itself the leader.    I noticed that in Zookeeper under `/marathon/leader` there were 4 entries instead of just 3.  The one node that didn’t recognize itself as the leader was duplicated there.

![](https://www.evernote.com/l/AAGVh9LglTJOSpo8j-wR7b09sJskts8h7LsB/image.png)

This wasn’t a production system so just to see what would happen I deleted both entries for the duplicate node and Marathon recovered. It showed up in Mesos again and still had the tasks that it had been running before the issue.  I haven’t been able to figure out from the logs how it ended up with that duplicate node there in the first place.

**Comment by papog** [comment]
I see the expected number of members on my machine (using zkCli.sh, I wonder what tool you got the screenshot from):
[zk: localhost:2181(CONNECTED) 2] ls /marathon/leader
[member_0000000064, member_0000000065, member_0000000066, member_0000000067]

I grepped in the logs and I find all 4 member items in the expected logs (i.e. each on one of the 4 machines).

**Comment by willgorman** [comment]
The screenshot is from [netflix/exhibitor](https://github.com/Netflix/exhibitor), which we're using to manage our Zookeeper.

**Comment by gkleiman** [comment]
This sounds like #2751

**Comment by papog** [comment]
Actually, this made me look back at the exception I had overlooked and it looks like some configuration issue related to Mesos (I am betting on the shared library).
I expect @gkleiman's fix for #2751 would have been helpful as the unusable marathon instances would simply have stopped.

**Comment by gkleiman** [comment]
Closing this, as it apparently was a configuration issue. Please re-open if you think there's something else we can do to help you.

**Comment by papog** [comment]
It works now. I was using a mesos library that had been compiled without Java support and was not aware of that.
This was causing a failure when the marathon instance was becoming leader (which is a bit late for a configuration issue) and marathon kept running in spite of this fatal error.
#2751 would most likely have made it really clear that the exception was fatal and thus I believe the issue is completely addressed.
