### ISSUE TITLE
Upgrade doesn't wait for readiness check

### ISSUE THREAD

**Issue by andrebeat** [mesosphere/marathon#3899]
Currently an app upgrade doesn't wait for readiness checks to pass. As soon as the app is healthy the old version is taken down, even though the readiness checks haven't succeeded yet.

**Comment by iverberk** [comment]
This really is a crucial issue for us. Right now, we have to work around it with a custom deployment script because we need the readiness checks to be accounted for, even if it's just a config update. Any comments on the status of this issue? Is it a bug or merely something that needs to be implemented?

**Comment by meichstedt** [comment]
I don't exactly remember the semantics, but the docs say
> * A deployment will only finish when all new tasks are ready
> * Depending on the application's upgradeStrategy, old tasks will only be killed if a new task has become ready.

Which sounds like the current behavior is not correct. From what I can see by (only quickly) looking into the implementation: using the ReadinessBehavior, the TaskReplaceActor will react to a `HealthStatusChanged` by calling `taskStatusChanged` which will kill the next old task, eventually _before_ the task reported as healthy is also _ready_. Seems like a bug to me.

**Comment by iverberk** [comment]
Any news on this? Would love to get rid of the custom script and solely use Marathon for my deployments.

**Comment by meichstedt** [comment]
@iverberk not really, sorry. So far, it seems like fixing the reported issue would break the original use case (readiness checks have been introduced to enable running schedulers via Marathon). I haven't had time to look deeper into this. If the conflict is given, we'd need to add a config option that allows to chain readiness and health checks, so that we can keep the old functionality while enabling users to combine these as requested.

We haven't prioritized this yet but I sense a certain strain on this. I can't promise anything, so if anyone is willing to provide a PR …

**Comment by andrebeat** [comment]
Can you please explain the original use case for readiness checks? I don't understand how it makes sense for something called a **readiness** check to not wait for the app to be declared as ready. This is what the documentation says about it:

> During deployments and runtime configuration updates, however, you might want a temporary monitor that waits for your application to be ready. A temporary monitor can be useful for cache-warming, JIT warming, or a migration. Marathon offers a readiness check for these situations.

There's no mention of schedulers so I don't understand the use case that you mention users are relying on.
