### ISSUE TITLE
error message for containerPath is difficult to parse

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#3910]
https://www.dropbox.com/s/j76sollcsw02i8y/Screenshot%202016-05-18%2014.26.56.png?dl=0

We should shoot for human-readable error messages. That one is not great, especially given that that regex literally means, ​_anything but no leading slash_​. So we could have said, ​_the containerPath must be a relative path with no leading slash_​.

**Comment by jdef** [comment]
actually the regex means: "zero or more non-slash characters". we don't allow any subdirectories, it's just a single-level relative path. local persistent volumes uses the same validation rule. we did the same w/ external volumes for (A) consistency, and (B) because the Mesos team asked us to (not sure what the underlying reasons were... perhaps related to additional error checking req's for more complex paths?)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1896. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
