### ISSUE TITLE
Tasks declared as Lost will be killed when reported running again

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#3924]
When mesos agent registration uses non strict registry, TASK_LOST is not a terminal state.
A task that is reported as lost can be running again.

**Comment by meichstedt** [comment]
Marathons general behavior is to expunge tasks from state for which it receives a TASK_LOST status update. It will then scale the app to make sure enough instances are running. If there are constraints or insufficient resources, it might not be able to launch a new task.

With this fix applied, Marathon will still scale the app and try to launch a new task for every​ received TASK_LOST ​immediately​. However, it will not generally expunge lost tasks from state if there is reason to believe that it might come back RUNNING (which can happen if Mesos is run with a non-strict registry and has a Master failover - the agent is then allowed to re-register without having all its tasks killed).

If Marathon receives a TASK_LOST with REASON_SLAVE_DISCONNECTED, REASON_SLAVE_REMOVED or REASON_RECONCILIATION, the task will now ​*not*​ be removed from state, because it might come back. If Marathon receives a TASK_LOST with any other reason, the task will be expunged from state (and killed if it unexpectedly reappears) like before this change was introduced.

This means Marathon will now effectively consider lost tasks as ​_possibly_ not running. If a lost task reappears, resulting in an instance count over the desired capacity, Marathon will kill running or staged tasks to scale down to the desired instance count. It will kill staged tasks with precedence, and continue with the youngest running tasks, so that the old, reappeared tasks stay running.
