### ISSUE TITLE
Anyway to dynamically attach labels to apps without restart containers.

### ISSUE THREAD

**Issue by oilbeater** [mesosphere/marathon#3945]
Seems like updating labels will cause container redeploy. 

I just  want to attach some labels to a set of app so that I can do some advance deployment in load balancer level like blue-green or traffic distribution, the strategy may change  so I want to change the labels time after time. However if container redeploy there will be a period of down time.

What I need is some dynamic changed attribute for an app without redeploy it, if labels can not do that, is there any other way to do that?

**Comment by gkleiman** [comment]
@oilbeater I'm afraid that this is currently not possible.

**Comment by oilbeater** [comment]
Will this be supported in later version? Label now will not affect running container, no deploy is needed and dynamic label can add much flexibility for other tools to interact with marathon.

**Comment by Multiply** [comment]
We're interested in the same kind of feature.

It would be amazing if we could update the app configuration, and have it as a switch if we want to trigger a redeploy.

**Comment by jdef** [comment]
Mesos doesn't currently provide a way to dynamically update executor or
task labels. The labels are set at launch time and fixed for the lifetime
of the executor/task.

**Comment by xyalan** [comment]
We're also interested in the same kind of feature.

**Comment by jdef** [comment]
If you want the labels to be passed down through to Mesos (likely) then you
really need to file a specific Mesos JIRA ticket for it. There's already
ticket filed for a related feature, to dynamically update discoveryInfo (
https://issues.apache.org/jira/browse/MESOS-4120). If you do decide to file
a ticket, please link it to MESOS-4120 since there will likely be similar
challenges to implement such.

When filing your ticket, please include the use case that you're trying to
solve (as was done here, originally).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2289. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
