### ISSUE TITLE
Deployments should be able to fail

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#3954]
Right now, it's not possible for a deployment to fail. If an application is failing to start successfully, it's possible for the deployment to continue forever. Users work around this by monitoring the deployment (for example: https://github.com/mesosphere/jenkins-marathon-plugin/issues/16#event-676309484) and if it hasn't happened within a known "good" time limit, they roll it back by applying a new deployment back to the original application state - except this time it needs to be "forced".

The deployments API should ideally have the concept of a timeout - after which the deployment is automatically rolled back.

**Comment by kamilchm** [comment]
Related to https://github.com/mesosphere/marathon-ui/pull/739

**Comment by meichstedt** [comment]
I understand the need for better behavior here, but I'm not sure your suggested solution fits the problem, @ssk2. To me this feels like adding a new feature instead of providing the information needed to react with a sensible action.

In order to rollback a deployment, Marathon creates a new deployment with the previous version. There is no extra state or relation between deployments. If Marathon was to automatically rollback in case it's running into a (configurable) timeout, this new deployment could also timeout (because of resource limitations or other constraints). In that case, the second deployment would also fail – and what then?

If someone tries to deploy 10 tasks and the cluster is only capable of running 9 tasks with the given configuration, the notion of a timeout and a rollback is rather painful because it would kill all the tasks and start all over again with the previous configuration (which probably tried to launch 20 instances and will fail as well). Deployments can fail for a variety of reasons. In case of a network partition a rollback wouldn't even make sense: the deployment might fail because Marathon didn't get offers from disconnected nodes. Additionally, I'd not want Marathon to ever rollback to a version that was never deployed successfully.

As long as we keep the current deployment functionality, I'd rather let the deployment fail after a timeout, keep the possibly running tasks, publish an event DEPLOYMENT_FAILED and let the user work with that.

Could you please provide more information on what your exact pain is or why you'd need an automatic rollback?

**Comment by kamilchm** [comment]
> As long as we keep the current deployment functionality, I'd rather let the deployment fail after a timeout, keep the possibly running tasks, publish an event DEPLOYMENT_FAILED and let the user work with that.

@meichstedt you could do that before Marathon 1.1 using `Stop` deployment button but you can't do that now because `Stop` was removed :-1:

**Comment by meichstedt** [comment]
@kamilchm sure, while the underlying api functionality still exists. Stopping a deployment leaves the app and its instances in a somewhat unclear state, as Marathon might end up with both new and old instances depending on the app's deployment strategy. If the deployment affects several apps with dependencies via a group upgrade, it's even more obscured what the resulting state is. It's not something we recommend doing, that's why the button was removed.

My point is: I'd rather have Marathon telling me that a deployment failed than doing some magic to hide the failure from me. In the end, if _a_ deployment was successful, how could I see that my actual target, the new version, has been deployed? If Marathon would silently rollback to a previous version, I'd want to see that somewhere. Imho indicating a failure would be a) simpler and b) leaves the resulting action up to the user instead of anticipating that the user wants to rollback to the previous version while adding complexity to the api and the deployment logic.

**Comment by ssk2** [comment]
@meichstedt -  certainly, this was just a suggestion. I agree that better status reporting would be a significant improvement. 

The reason I filed this issue was to enable better automated / continuous deployment using the Marathon API. Currently, without a failed state, the application will continue to deploy indefinitely. For a continuous deployment pipeline to act in an automated fashion, it's necessary to add logic to track this state (as in the case of the ticket I linked). In order to "fix" the deployment that is still ongoing, it's necessary to then create a new deployment with force set to true which we'd like to avoid (ideally requiring human intervention when force is necessary). 

More expressive deployment state will be useful in the future too, especially if we have support for canary deploys and other advanced deployment strategies which have multiple stages.

**Comment by kamilchm** [comment]
Current UI with only one **Rollback** buton that can kill all running apps as described in https://github.com/mesosphere/marathon/issues/4046 can be much more dangerous than previous **Stop** button. In fact it lead us to an outage today by killing all our task that were doing fine before calling **Rollback** :(

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2502. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
