### ISSUE TITLE
API call for moving a task/instance into and out of draining state.

### ISSUE THREAD

**Issue by ajays20078** [mesosphere/marathon#4033]
Is there a API call to move individual task/instance into draining state, this is required to wait for connection drianing before deleting the instance. Similarly is there a API call to move a individual task out of the draining state into UP/DOWN state?

**Comment by marcomonaco** [comment]
If you call the API with 'POST /v2/tasks/delete` or `DELETE /v2/apps/<appId>/tasks/<taskId>' there is a fixed time of 3 seconds before a task get killed by the executor.

Beginning with Marathon 1.2 we will have the possibility to set the time individually with 'taskKillGracePeriod'. See here: https://github.com/mesosphere/marathon/commit/4a6cd7afe66c91741d835a55933da67b72c331de
If you enable the Mesos’ TASK_KILLING capability via the Marathon flag 'enable_features task_killing`, a killed task will be reported with state TASK_KILLING (until it exits or is killed by the executor), which should be used by your load balancer in order to exclude the task when routing requests.

To your second question: there is no API call to do that. 

If you need further information please let me know.

**Comment by brndnmtthws** [comment]
`TASK_KILLING` really doesn't solve this problem. The issue is: as a user I need to drain a task before killing it. Task killing simply sets a timer, and then kills it. There's still no way to mark a task as being drained.

[MLB can, however, do this](https://github.com/mesosphere/marathon-lb#zero-downtime-deployments), but Marathon should really have an API (see #2766, #2724, and #712).

**Comment by gkleiman** [comment]
@brndnmtthws `TASK_KILLING` does more than just setting a timer. When enabled, Mesos will:

1. Send a signal to the task.
2. Send a task status update to the framework with the status `TASK_KILLING`. This will also be reflected in the Master/Agent `state.json` endpoints. This can be seen as marking the task as beeing drained.
3. Wait until the task exits or until the timer times out.
4. Send a `TASK_KILLED` status update.

**Comment by brndnmtthws** [comment]
@gkleiman yes but the fundamental problem remains: this is a probabilistic solution, as opposed to a deterministic one. What if the task is killed before it completes draining?
