### ISSUE TITLE
403 Forbidden with Gradle

### ISSUE THREAD

**Issue by niclash** [mesosphere/marathon#4084]
I am using Gradle 2.13 and trying to build a Marathon plugin. So I need to declare a dependency on 

    provided "mesosphere.marathon:plugin-interface:0.15.5"

But Gradle reports;

 Could not resolve mesosphere.marathon:plugin-interface:0.15.5.
      > Could not get resource 'http://downloads.mesosphere.io/maven/mesosphere/marathon/plugin-interface/0.15.5/plugin-interface-0.15.5.pom'.
         > Could not GET 'http://downloads.mesosphere.io/maven/mesosphere/marathon/plugin-interface/0.15.5/plugin-interface-0.15.5.pom'. Received status code 403 from server: Forbidden

Likewise, if I try to fetch it from my browser, I will get an Error (XML) back;
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>2934955A90A4212F</RequestId><HostId>fbLukNcKuM0hpz2bOST9FV+47HsG82bnJrfvFN1PfzcZrwGon6oloDC8nv6r+KfTTDrwwt1Fb2g=</HostId></Error>

Version 0.13.0 gives the same result.

**Comment by unterstein** [comment]
Hi @niclash,

unfortunately you are receiving a 403 instead of a 404, which would be semantically correct.

You are depending on a scala compiled artifact, therefore this artifact has a suffix related to the scala version which compiled it. So, if you are not using scala, you need to add this suffix manually, in your case ```plugin-interface_2.11```.

In your case, the line should look like:

```
provided "mesosphere.marathon:plugin-interface_2.11:0.15.5"
```

Hope this fixes your issue and I will close this task now. If you have any further questions or this solution is not working for you, feel free comment on this task and/or e-open the task.

Kind regards
Johannes
