### ISSUE TITLE
[improvement] Tell marathon that application links should be http not https

### ISSUE THREAD

**Issue by kopax** [mesosphere/marathon#4125]
I use marathon behind a HTTPs proxy.
Because of that, all the URL(s) for each ports in the service list are in HTTPS.
Is there a way to force it to be "http'"?
It would be nice to add this feature. Also, it would be nice to be able to choose the protocol to use.

**Comment by unterstein** [comment]
Hi @kopax,

unfortunately there is currently no feature to do this, but maybe you have seen this issue https://github.com/mesosphere/marathon/issues/2974. The problem is at this point, that marathon do not know if the service uses http or https, unless the protocol is also configured in the AppDefinition. I`ll add this issue as enhancement to the backlog.

If you have any further questions, ideas or enhancements, feel free to ask further questions.

Kind regards
Johannes

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1957. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1957. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
