### ISSUE TITLE
portDefinitions should be optional

### ISSUE THREAD

**Issue by vixns** [mesosphere/marathon#4189]
When updating an app with `ipAddress` and without `portDefinitions`, it raise a validation error.
Workaround: add an empty `portDefinitions` to pass the validator.

Use a curl/rest call to reproduce, the UI tends to silently add an empty `portDefinitions`

**Comment by unterstein** [comment]
Hi @vixns,

thanks for reporting this.

You are receiving probably something like `IP address (something) and ports (something) are not allowed at the same time`, right?

This is because portDefinitions are set to a random port definition by default https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L63 and there is a validation in https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L101 which checks if ipAddress and portDefinitions are used in combination. By declaring empty portDefinitions, this default behavior is not taken.


Unfortunately I think this not so easy to change because of backwards compatibility ... Maybe @gkleiman can add his opinion to this issue :)

Cheers
Johannes

**Comment by vixns** [comment]
Yes, to reproduce, put this minimal json to marathon: 
```json
{
  "id": "/test",
  "cpus": 0.01,
  "mem": 32,
  "instances": 1,
  "container": {
    "type": "MESOS",
    "docker": {
      "image": "nginx"
    }
  },
  "healthChecks": [
    {
      "path": "/",
      "protocol": "HTTP",
      "port": 80
    }
  ],
  "ipAddress": {
    "discovery": {
      "ports": [
        {
          "number": 80,
          "name": "http",
          "protocol": "tcp"
        }
      ]
    }
  }
}
```

response:

```json
{"message":"requirement failed: IP address (Some(IpAddress(List(),Map(),DiscoveryInfo(List(Port(80,http,tcp,Map()))),None))) and ports (List(PortDefinition(0,tcp,None,Map()))) are not allowed at the same time"}
```

workaround: add `"portDefinitions": []`

**Comment by aaronjwood** [comment]
One thing I found that worked was to set the ports inside of the `ipAddress` section like so:

```
"ipAddress": {
    "discovery": {
        "ports": [
            {
                "number": 31052,
                "name": "api",
                "protocol": "tcp"
            }
        ]
    },
    "networkName": "dcos"
}
```

My case might be a bit different though. I had a framework that I wanted to launch in the overlay network which had originally defined `portDefinitions`. I found that I couldn't use this because of the validation issue. The framework uses a `readinessCheck` which relies on a `portName` being used. Thanks to @karlkfi for pointing me to the latest Swagger docs which show you can do this. The docs here don't show anything about configuring ports http://mesosphere.github.io/marathon/docs/rest-api.html

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2608. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2608. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
