### ISSUE TITLE
Kill task of app in deployment does not work when scale=false

### ISSUE THREAD

**Issue by fengyehong** [mesosphere/marathon#4191]
### Reproduce Steps
1. Make an app stay in deployment, in my case I have a cluster with 3 mesos slaves, I set constraint [hostname, UNIQUE], and scale to 5, so it has 3 tasks running and stays in "Waiting"
2. Kill one of the running task by `DELETE /v2/apps/tasks/<taskid>` with scale=false
### Expected Result
1. the task get killed or error returned
### Real Result
1. the API returned 200 and the task to 'killed'
2. but the task is not killed in fact
3. setting parameter force=true or force=false not make a difference

I think the scheduler actor just failed to acquire the lock and didn't not check the result:
https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/MarathonSchedulerActor.scala#L162

**Comment by unterstein** [comment]
Hi @fengyehong ,

which version of marathon are you using? Can you post the relevant marathon logs?

Thanks
Johannes

**Comment by fengyehong** [comment]
I'm using 1.1.1

When setting logging level to info, I got only one line log indicating receiving the kill request :(
```
2016-08-23 10:57:34,969  INFO 10.1.243.147 - - [23/Aug/2016:10:57:34 +0000] "DELETE //mesos-master-dev042-cqdx.qiyi.virtual:8080/v2/apps/tt/tasks/tt.d573304c-691e-11e6-b254-525400fd9fbc HTTP/1.1" 200 349 "-" "HTTPie/0.9.2" 5 [mesosphere.chaos.http.ChaosRequestLog:16]
```
All other logs are offer processing related.

**Comment by unterstein** [comment]
I retested this locally and the API behave in a non expected way. This is because the TaskKillActor told to kill the tasks instead of being asked and the result is not used to calculate the HTTP result, see https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala#L154.

The reason the deletion is failing, because the task is currently locked through the other deployment (see https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/MarathonSchedulerActor.scala#L168).

The correct status code in this situation would be something like ```423 Locked (WebDAV; RFC 4918)```.

Thanks for reporting this issue! I`ll move this to backlog, but maybe someone wants to provide a PR :)

Cheers
Johannes

**Comment by jeschkies** [comment]
We don't report when the App is locked. We haven't agreed yet how we will handle this case.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1686. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1686. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
