### ISSUE TITLE
Cluster fails to deploy after ZooKeeper connectivity loss

### ISSUE THREAD

**Issue by apognu** [mesosphere/marathon#4227]
Hi !

I'm having an issue where in case of connectivity loss with the ZooKeeper servers, the Marathon cluster would be inoperable without manual intervention.

Here's some details about the issue:
- Restart a ZooKeeper instance
- Marathon's leader is automatically killed (and restarted) and another assumes the role of master
- I do have access to Marathon's UI but any task operations stays in Waiting/Deploying forever
- If I restart the two remaining Marathon services, everything is back to normal, I can deploy and scale my apps

I get that the leader might be killed if ZK connectivity is lost, but I thought the cluster would survive without my having to restart all Marathon instances.

I am running ZooKeeper 3.4.5, Mesos 1.0.0 and Marathon 1.1.2.

Regards,
Antoine.

**Comment by apognu** [comment]
Apparently, when this happens, forcing a new election through ```DELETE /v2/leader``` fixes the issue.

Right now, I have a cronjob that checks ```/v2/info``` for the issue and triggers the leader abdication. But somehow, I think Marathon should do it itself.

**Comment by nekonyuu** [comment]
Unfortunately, this fix doesn't seems to always work, as the cluster can sometimes get into a fully blocked state without leader, making the API answer with a 500 `Could not determine the current leader`...

So, no workaround :(

**Comment by apognu** [comment]
I can second that. In that case, only a full rolling-reboot of the master cluster works on my side.

**Comment by drewrobb** [comment]
We have seen a very similar issue, both on marathon 1.1.x and now on marathon 1.3.0 with the new curator based leader election. We were hoping 1.3.0 fixed the issue but it has not. 

We have seen the current leader (10.0.16.226) get a message like "ZooKeeper access failed - Committing suicide to avoid invalidating ZooKeeper state",  it just a second later it reelected itself "Defeated (LeaderLatchListener Interface). New leader: 10.0.16.226:8080". After this, it appears to keep leadership but wasn't actually doing anything and manual intervention was needed (stop all marathons, then start them). I will try to reproduce this issue in a sandbox so that I can have some better logs.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2161. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
