### ISSUE TITLE
macvlan network for docker containers in marathon 

### ISSUE THREAD

**Issue by butterflyinfly** [mesosphere/marathon#4243]
Hi All,

Could you please help me how to configure docker network in marathon to use macvlan? 

Container
{
  "type": "DOCKER",
  "volumes": [],
  "docker": {
    "image": "",
    "network": "HOST",
    "privileged": false,
    "parameters": []
 }
}

So the question is - how could I change network to MACVLAN if only HOST and BRIDGE options are available?
docker version  1.12.1
MarathonVersion 1.1.1

Thanks!

**Comment by samek** [comment]
On mesos or over docker? 
And as far as i know docker 1.12.1 doesn't support global scope of macvlan..

**Comment by butterflyinfly** [comment]
@samek cluster is build on mesos, applications are running in docker
macvlan is  in experimental mode in docker 1.12.1 so I suppose that we can use it

**Comment by samek** [comment]
I’ve asked since in mesos 1.0 there CNI support http://mesos.apache.org/documentation/latest/cni/ <http://mesos.apache.org/documentation/latest/cni/>

Ok. 

So I was trying macvlan on raspberry pi’s and it did not work on global scope so I had to re-compile it. 

Anyways on 1.1.1 (which i have) I did it like this:


{
 "id": "/macvlantest",
 "cmd": null,
 "cpus": 0.1,
 "mem": 32,
 "disk": 0,
 "instances": 1,
 "constraints": [],
 "ipAddress": {
             "networkName": "poponline"
       },
 "container": {
   "type": "DOCKER",
   "volumes": [],
   "docker": {
     "image": "hypriot/rpi-nano-httpd",
     "network": "BRIDGE",
     "privileged": false,
     "parameters": [
       {
         "key": "net",
         "value": "poponline"
       }
     ],
     "forcePullImage": false
   }
 }
}

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4441. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
