### ISSUE TITLE
Support using MESOS_TASK_ID in app definitions

### ISSUE THREAD

**Issue by aseppala** [mesosphere/marathon#4258]
It would be very useful to be able to use mesos task IDs in context of docker labels. This would enable users to query containers by mesos task id and find the container they are looking for:

```
$ docker ps --filter label=mesos_task_id="myapp.d07b42e2-6b85-11e6-8aec-fa163ed2b060"
```

Docker labels can also be utilized to map logs to mesos tasks:

When shipping container logs with filebeat, container labels are used to tag loglines. To have mesos task id as a container label would allow one-to-one mapping between log lines and mesos tasks. This way searching logs of a specific mesos task would be a breeze.

Application definition file to illustrate the idea:

```
{
    "id": "myapp",
    "cpus": 0.2,
    "mem": 128,
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "myapp",
            "parameters": [
                { "key": "label", "value": "mesos_task_id=$MESOS_TASK_ID"}
            ]
        }
    }
}
```

**Comment by jdef** [comment]
Perhaps a better place to ask for this feature would be in Mesos? So that
all frameworks that launch docker containers are appropriately labeled.

**Comment by wu8685** [comment]
hi @jdef I have had a try at this on marathon v1.1.1. But there is a unexpected result. I get the mesos task id from [here](https://github.com/mesosphere/marathon/blob/v1.1.1/src/main/scala/mesosphere/mesos/TaskBuilder.scala#L113)  and insert this task id as a label in `container parameter` by hard code.

But it turns out the task id I get from the marathon code I mentioned is not the same as the id of the task actually running later on mesos. (for example, the id I get from code is `paas_staging_echo.e5381f76-7d68-11e6-952c-525400fb32fd`, but the real id is `paas_staging_echo.e5378334-7d68-11e6-952c-525400fb32fd`. They are a little different)

Is the task id passed to `builder` [here](https://github.com/mesosphere/marathon/blob/v1.1.1/src/main/scala/mesosphere/mesos/TaskBuilder.scala#L113) is just a suggestion? Or is there any way to get the real mesos task id from marathon before it starts the container?

Thx

**Comment by jdef** [comment]
I would expect that the task IDs match. Mind sending a link to the code
change that introduces this feature?

**Comment by wu8685** [comment]
oops~ I deleted my comment because it worked after fixing a problem in my code. 
thanks for your reply :)

**Comment by aseppala** [comment]
While this feature would help me in a lot of cases, I'm not sure if adding labels by default to all running containers is something what all Mesos users want? After all naming labels needs to be done in a controlled manned to avoid any conflicts.

**Comment by wu8685** [comment]
I think it would be a convenient way to relate a marathon task with its running container. If it's ok, I volunteer to work on this issue

**Comment by wu8685** [comment]
I create a PR to fix this issue. Please take a look, thx.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2220. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
