### ISSUE TITLE
Pass Non-Extractable URIs through Marathon

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#436]
we need the ability to pass to mesos extract = false flag for URIs.  There are multiple reasons for this, however the ability to use private repos with the latest version of mesos with docker support is one of them.  In this case, there is a desire to pass the .dockercfg file to be loaded in the sandbox.

There is value IMO in at least allowing this in a json post to the REST API and following up later with UI changes to support.

**Comment by drewkerrigan** [comment]
I'm not sure if this qualifies as a different problem than the one originally stated in this issue, but I'd like to bring up this discussion again. If a scheduler is expected to serve its own artifacts (such as an executor), doesn't it make sense to add support for an explicit `extract=false` for some but not all of the values in the `uris` list?

For example, if I specify:

```
...
"uris": ["myscheduler.tar.gz", "myexecutor.tar.gz"],
...
```

I may want the `myexecutor.tar.gz` to remain compressed, so that the scheduler can serve it from its own HTTP API when launching tasks. The current behavior would cause both `myscheduler.tar.gz` and `myexecutor.tar.gz` to get expanded into the scheduler's container even though an expanded `myexecutor.tar.gz` is useless to the scheduler.

I don't have an ideal solution for the implementation of this, but maybe something like `"uris": ["myscheduler.tar.gz", "myexecutor.tar.gz#expand=false"],` would introduce minimal impact to existing functionality?
