### ISSUE TITLE
Do not log sensitive information on startup

### ISSUE THREAD

**Issue by pierrecdn** [mesosphere/marathon#4647]
During Marathon startup, the first log to be written contains all credentials and sensitive information.
When system logs are forwarded and centralized, it could be an issue.

The log is written by https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/Main.scala#L51

And could be probably fixed using filtering on sensitive arguments like what follows `--master`, `--zk` and `--http_credentials`.

**Comment by ror6ax** [comment]
Hi there, just FYI - I'd like to take this one as my first Marathon issue.

**Comment by allquantor** [comment]
Hello,
to solve this straight forward we could just filter args on given values in [Main.scala line:65](https://github.com/mesosphere/marathon/blob/ca9e12641e637d46c622e8549a734d98030c2d6a/src/main/scala/mesosphere/marathon/Main.scala#L65)

However, I do not like this approach because it causes arg parsing boilerplate (e.g distinguish between args provided as `key value` and `key=value` ...) that is already done by `scallop` library used in Marathon. Scallop provides `ScallopConf.summary` we could replace the logging statement with it. Unfortunately, `scallop` does not filter the arguments. 

I made a [PR with filtered summary in scallop](https://github.com/scallop/scallop/pull/131). It could be used in marathon after it is merged.

**Comment by jdef** [comment]
I left a comment on the scallop commit regarding subbuilders and invoking
filteredSummary there too

**Comment by allquantor** [comment]
@jdef done and merged. To used would mean to upgrade marathon scallop version any objections on that?

**Comment by jdef** [comment]
@allquantor I'm guessing we pull in our scallop dependency from chaos here: https://github.com/mesosphere/chaos/blob/master/project/build.scala#L130

I think we've recently added an item to the roadmap for eliminating the dependency on chaos. Scallop may be on the chopping block too. If Marathon 1.5 will continue to use Scallop then it's probably worth an upgrade.

@jasongilanfarr care to chime in here?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2071. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
