### ISSUE TITLE
Kill and Scale may throw an error if task-id's provided are bigger then instances

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#4897]
If currently a application is in deployment but the healthchecks did not pass yet. Then I will have a overcapacity of `instances * 2` for example. If I then kill and scale all the tasks I will end up with `instances = instances * -1` Which will end up with an error.

What actually is supposed to happen is that in that case the instances are at least 0. Or filter out the tasks with the old version and only subtract the new ones. 

This is the output I do get.
```JSON
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/apps(0)/instances",
      "errors": [
        "got -1, expected 0 or more"
      ]
    }
  ]
}
```

Here is a short gif which hopefully explains the issue:

![killandscale-tasks mov](https://cloud.githubusercontent.com/assets/156010/21391245/1ced1d0c-c78b-11e6-81ce-53a3854fbe36.gif)

**Comment by zen-dog** [comment]
The problem: you're trying to update an already old app version (2 old tasks). This fails the validation with:
`ERROR Failed validation because Set(GroupViolation(MapLike(AppDefinition(/webserver,Some(./web-server.py $PORT0),List(),None,Map(),-2,Resources(1.0,128.0,0.0,0),,Set(),List(FetchUri(file:///Users/adukhovniy/scripts/util/web-server.py,false,false,false,None)),List(),List(PortDefinition(10000,tcp,None,Map())),false,BackoffStrategy(1 second,3600 seconds,1.15),None,Set(MarathonHttpHealthCheck(300 seconds,10 seconds,20 seconds,3,Some(ByIndex(0)),None,Some(/test),HTTP,false)),List(),None,Set(),UpgradeStrategy(1.0,1.0),Map(),Set(),None,FullVersionInfo(2016-12-22T13:17:45.801Z,2016-12-22T13:17:45.801Z,2016-12-22T13:17:39.785Z),None,Map(),UnreachableStrategy(15 minutes,7 days),YoungestFirst)),Seq contains elements, which are not valid.,Some(apps),Set(GroupViolation(AppDefinition(/webserver,Some(./web-server.py $PORT0),List(),None,Map(),-2,Resources(1.0,128.0,0.0,0),,Set(),List(FetchUri(file:///Users/adukhovniy/scripts/util/web-server.py,false,false,false,None)),List(),List(PortDefinition(10000,tcp,None,Map())),false,BackoffStrategy(1 second,3600 seconds,1.15),None,Set(MarathonHttpHealthCheck(300 seconds,10 seconds,20 seconds,3,Some(ByIndex(0)),None,Some(/test),HTTP,false)),List(),None,Set(),UpgradeStrategy(1.0,1.0),Map(),Set(),None,FullVersionInfo(2016-12-22T13:17:45.801Z,2016-12-22T13:17:45.801Z,2016-12-22T13:17:39.785Z),None,Map(),UnreachableStrategy(15 minutes,7 days),YoungestFirst),not valid,Some((0)),Set(RuleViolation(-2,got -2, expected 0 or more,Some(instances)))))))`
One solution could be for UI to forbid "Scale and kill" for "old" tasks. Or we might provide a better response error message?

**Comment by aquamatthias** [comment]
https://phabricator.mesosphere.com/D383
