### ISSUE TITLE
Environment variables keys change to Upper case when editing through the UI

### ISSUE THREAD

**Issue by Yanivro** [mesosphere/marathon#4911]
When you attempt to edit the application through DCOS UI, every environment variable key you had will automatically turn to lower case, you can switch to json mode to see it.

example:
foo:bar
will turn into
FOO:bar

**Comment by orlandohohmeier** [comment]
Hey @Yanivro, thanks for reporting this! The upper casing was implemented based on IEEE 1003.1-2001 standard which declares that environment variable names should consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in *Portable Character Set* and should not begin with a digit.
We've changed the implementation in DC/OS UI 1.9 as you wern't the only one running into issues with the current behavior, as the standard further reads that other characters may be permitted by an implementation and that applications shall tolerate the presence of such names.

Closing this issue as it's not a Marathon UI issue in fixed with the latest DC/OS UI 1.9 release.

*PS: Please use the DC/OS Jira (https://dcosjira.atlassian.net) to file DC/OS related issues so that we can properly assign the issue.*
