### ISSUE TITLE
[Scope Doc] Jobs in Marathon

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4955]

**Comment by kamilchm** [comment]
Is it something related to Chronos/Metronome?

**Comment by meichstedt** [comment]
@kamilchm @janisz Yes, it is related.

Long story short: Metronome was already built on top of the Marathon core, but back then we didn't want to introduce all the complexity that Jobs would bring into a scheduler for long running services.

We've since abstracted lots more of the code base and are confident to do this now, meaning that the next version of Metronome is actually going to be built into Marathon 😎

I'll put up a design document in the next 1-2 weeks and am happy for any input by then and afterwards.

**Comment by jasongilanfarr** [comment]
@meichstedt Generally looks good to me, I left one remaining question.

**Comment by janisz** [comment]
Where it can be reviewed?

**Comment by meichstedt** [comment]
@janisz thanks for your interest. The scope doc is something we use internally to plan for the upcoming release. I'll see if I'm able to share it.

Definitely meant for gathering input from the community is the _design doc_ – I'll update #5009 once the initial draft is there this will yet take a few days.
