### ISSUE TITLE
Unique host constraint is not enforced during rolling upgrade of app

### ISSUE THREAD

**Issue by albertcsm** [mesosphere/marathon#4990]
I have web servers that listen on a fixed port. I used marathon to launch these servers, and set a "hostname:UNIQUE" constraint to ensure that theses servers don't run on the same host and end up with port collision.

I had been using Marathon's rolling upgrade feature to upgrade these servers. It was working very smooth. Servers of the newer version are started in nodes that have no existing servers.

However, in recent Marathon versions, I found that such unique-host constraint is no longer enforced during rolling upgrade. New servers are being started side-by-side to old servers and failed with port collision.

This issue can be reproduced with following App JSON:
```
{
  "id": "/test-server",
  "cmd": "python -m SimpleHTTPServer 10101",
  "cpus": 0.1,
  "mem": 32,
  "disk": 0,
  "instances": 6,
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "portDefinitions": [],
  "upgradeStrategy": {
    "minimumHealthCapacity": 0.8,
    "maximumOverCapacity": 0
  }
}
```

Try triggering an upgrade, e.g. by increasing the CPU share, then likely some Marathon tasks would fail.

Marathon shows that multiple tasks are are running on the same host
![image](https://cloud.githubusercontent.com/assets/2263504/22104841/1a6c293a-de7c-11e6-91e5-288c0fc7c085.png)

The Marathon app's DEBUG page shows "TASK_FAILED", and the Mesos task's stderr shows that the task failure is due to multiple servers running on same host:
```
I0119 10:56:06.241583 68112 exec.cpp:162] Version: 1.1.0
I0119 10:56:06.243521 68122 exec.cpp:237] Executor registered on agent 367af7e4-ea29-470a-9b13-e7c5e9e9a768-S3
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 220, in <module>
    test()
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 216, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 595, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

I am running Marathon 1.3.6. Did a brief searching, and found that the issue may be related to the fix in 
https://github.com/mesosphere/marathon/issues/3624
which removes that constraint checking against tasks of an earlier version.

I think the constraint should be maintained throughout the rolling upgrade if it is not changed.

**Comment by janisz** [comment]
Interesting edge case. Probably the change should be done [here](https://github.com/janisz/marathon/blob/d644692bbeab8a55ed2c9b52ce59a05f8caeb67c/src/main/scala/mesosphere/mesos/ResourceMatcher.scala#L179) to include all running instances with different version if constraints are equal. Can you think about any case that could break after this change?

**Comment by albertcsm** [comment]
I think it would suit most cases, but further improvement would be:
* apply new constraints to the set of new tasks
* apply unchanged constraints to the set of all tasks

**Comment by janisz** [comment]
The real solution for your issue you described (port collision) is to required static port in the app definition (`"requirePorts":true`) or to use network containerize.

Applying only unchanged constraints to deployment will cause a situation when you can't deploy application because it can't meet it's constraints e.g. UNIQUE HOST for 3 instances of application while you have only 3 nodes.

**Comment by albertcsm** [comment]
I am aware of network containerization. However, if I map the container port to the same host port, then I end up with the same problem. On the other hand, if I map to an assigned host port, I can use Marathon-lb to forward requests. But Marathon-lb/haproxy may forward requests from one server to another, which may waste significant network bandwidth.

**Comment by janisz** [comment]
Why you can't use `"requirePorts":true`?

**Comment by meichstedt** [comment]
Indeed related to #3624 where the current behavior was introduced, which sounds correct to me. If Marathon would consider old instances for matching constraints during upgrades, it would likely end up in situations where it cannot launch new instances. See the example @janisz described with N instances on N nodes and a `hostame:UNIQUE` constraint – if the upgradeStrategy doesn't allow taking down running instances before launching new ones, it could never finish a deployment.

@albertcsm Your app definition **must** make sure that the ports used are declared so that Marathon can consume those resources when launching an instance. If you define the app with no information about used ports, Marathon cannot consume them when launching an instance, and cannot make sure that new instances are launched on agents that actually offer that port.
