### ISSUE TITLE
Plot Scale Test Results

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5134]
As a Marathon developer I would like to get insights into the test results to judge them.

Details:
Each Jenkins Job plots the results in a Python script. The plotting is not done with a Jenkins plugin because that requires action by the Velocity which might delay progress. The plot image file is archived for each Jenkins job.

The plots should look like these: 
![screen shot 2017-02-08 at 13 46 32](https://cloud.githubusercontent.com/assets/19775099/22737801/082faa2e-ee05-11e6-93f0-516030014f0f.png)

(src: https://docs.google.com/spreadsheets/d/1JY2QeVLMSCPy5CDDXtx2mQe_KI9jEDRQaoJ0fpMcYOw/edit#gid=0)
It plots number of instances vs elapsed time and number of apps vs elapsed time.

**Comment by kensipe** [comment]
The graphs now will be for root marathon and will not have a baseline.   just 1 plotted graph.
There are a couple of graphing options as well:
1. Gnuplot
2. python
3. alternative graphing package:
http://www.statmethods.net/advgraphs/ggplot2.html
4. https://wiki.jenkins-ci.org/display/JENKINS/Plot+Plugin

in order to get a plugin added to our internal jenkins we need to:
tested on our own jenkins cluster
file a jira for velocity
https://mesosphere.slack.com/archives/velocity/p1486426538004862

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1740. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
