### ISSUE TITLE
Updating fields like 'upgradeStrategy' triggers an application restart

### ISSUE THREAD

**Issue by pierrecdn** [mesosphere/marathon#5221]
All fields that belong only to the scheduler job and are not part of the app itself or linked to Mesos features should be available **without triggering a restart**.

This is especially useful when you scale up/down your app AND there is a 'rolling restart' upgrade strategy set to:
* `maximumOverCapacity: 0`
* `minimumHealthCapacity: 1-(1/N)`

Now by doing that you'll restart ALL the instances and not just add or remove one.

[NOTE: to me having to set the minimumHealthCapacity is also an issue in that case (the user would maybe prefer to set the number of instances), but this is for another ticket].

**Comment by janisz** [comment]
Duplicates: https://github.com/mesosphere/marathon/issues/4987

**Comment by meichstedt** [comment]
@pierrecdn agreed as well. We'll move towards a better structure and allowing for better control over deployments; as mentioned in #5225, this will take time. In general, one might question whether the upgradeStrategy should actually be part of a runSpec (app/pod model) – every upgrade is likely to be different. Consider

a) _I fixed the timeout by adjusting something in the command and just want instances to be restarted_
vs
b) _I'm not too confident in the new docker image and would like to watch one instance over the course of a few hours before migrating other instances to that new version_

So, instead of not restarting all instances in case you've only adjusted the upgradeStrategy, we're reasoning about things beyond that. I can see your point though that this hurts – feel free to get in touch if you're willing to contribute.

(closing in favor of #4987)
