### ISSUE TITLE
UpgradeStrategy should not adopt a default strategy when fields are conflicting

### ISSUE THREAD

**Issue by pierrecdn** [mesosphere/marathon#5224]
We noticed that setting `upgradeStrategy` values like:
```
minimumHealthCapacity: 1
maximumOverCapacity: 0
```
Should produce a deadlock, but in reality a 'rolling upgrade with overcapacity' policy is applied.

This seems dangerous to me, since some sensitive apps could ask for explicit acknowledgement from a dedicated webui/API whatever to pursue their migration.

This seems more or less related to #4416, feel free to eventually close as duplicate.

**Comment by meichstedt** [comment]
@pierrecdn I assume the reason for implementing it as it is now was probably to not deadlock deployments – I agree, this is very confusing and not what I'd expect.

The problem here is that this behavior has been like that for ages and we cannot safely change it because it'd likely break other people's tooling. As you've realized, there are other drawback to the way upgradeStrategy is implemented and evaluated, and it seems we'd best fix this by introducing a new thing alltogether.

(One thing that bothers me in the current approach explicitly is that, when an old instance terminates unexpectedly, Marathon will schedule a new one although the old one just died by incident and was not torn down on purpose.)

**Comment by pierrecdn** [comment]
> we'd best fix this by introducing a new thing

I understand your point, but is it really an issue to deprecate things as long as they are widely advertised as 'breaking' ? "Building a new thing" will make Marathon API quite confusing (except if we speak about a /v3 here ...).

> although the old one just died by incident and was not torn down on purpose.

I don't see that point in my case... As long as it respect the `upgradeStrategy` constraints ;) .

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1744. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
