### ISSUE TITLE
Endpoint environment variables aren't in the docs

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#5240]
@jdef Can give some context, but I couldn't find docs for how pod endpoint environment variables are set:

ENDPOINT_{NAME} = ....
EP_CONTAINER_{NAME} = ...
EP_HOST_{NAME} = ...

**Comment by jasongilanfarr** [comment]
should get docs on releases/1.4 and master.

**Comment by jdef** [comment]
Three vars:


ENDPOINT_{name}: when in `host` networking mode, this is the endpoint's
hostPort; in `container` mode this is the endpoint's `containerPort`
.. this should always be present, because `hostPort` is required for `host`
networking mode, and `containerPort` is required for `container` networking
mode.

EP_HOST_{name}: reflects the value of the endpoint's `hostPort` (if defined)
EP_CONTAINER_{name}: reflects the value of the endpoint's `containerPort`
(if defined)
.. the presence of the above two variables depends on the declaration of
the endpoint named `{name}`

**Comment by jasongilanfarr** [comment]
We also always capitalize the name.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2441. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
