### ISSUE TITLE
Hash Sum mismatch when trying to install ubuntu package

### ISSUE THREAD

**Issue by gucki** [mesosphere/marathon#661]
Tried to install it several times, always the same error:

```
sudo apt-get -y install marathon
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  marathon
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 61.5 MB of archives.
After this operation, 69.0 MB of additional disk space will be used.
Get:1 http://repos.mesosphere.io/ubuntu/ precise/main marathon amd64 0.7.1-1.1 [61.5 MB]
Fetched 61.5 MB in 12s (4,906 kB/s)
Failed to fetch http://repos.mesosphere.io/ubuntu/pool/main/m/marathon/marathon_0.7.1-1.1_amd64.deb  Hash Sum mismatch
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Is the archive broken or has your server been compromised?

**Comment by roachmd** [comment]
Having this issue. Dot sure what the issue is. I can install mesos, chronos. But, Marathon seem broken.

Get:1 http://repos.mesosphere.io trusty InRelease [3,136 B]       
Get:2 http://repos.mesosphere.io trusty/main amd64 Packages [5,219 B]
Ign http://repos.mesosphere.io trusty/main Translation-en_US              
Ign http://repos.mesosphere.io trusty/main Translation-en
Fetched 8,355 B in 1s (4,225 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mesosphere : Depends: marathon but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by ssk2** [comment]
@roachmd, the newest version of Marathon has a dependency on Java 8 - you'll need to install that first before trying to install/update the package. See the changelog for more information: https://github.com/mesosphere/marathon/releases/tag/v0.11.0

**Comment by roachmd** [comment]
Okay, that worked.

$ sudo add-apt-repository ppa:webupd8team/java
$ sudo apt-get update
$ sudo apt-get install oracle-java8-installer

**Comment by ssk2** [comment]
Great!

**Comment by nirmalpatel** [comment]
Thanks ssk2. Solved my problem also.
