### ISSUE TITLE
Marathon not using nameservice information from Hadoop configuration

### ISSUE THREAD

**Issue by aleksa** [mesosphere/marathon#819]
Marathon's `--artifact_store` option is not using nameservice information from Hadoop configuration. E.g. passing `--artifact_store "hdfs://nameservice1/foo"` results in an error as it expects to see only hostname and port. Marathon should have a command line argument for specifying Hadoop's path and use nameservice information.

**Comment by travishegner** [comment]
Another note, if you use a host name that is not resolvable, marathon fails to start completely. I would expect it to carry on and run as if --artifact_store had never been specified, and re-try the back end periodically. Once the back end becomes available, the artifact store API calls should begin to function normally.

In my case, trying to use a hostname that points to an HDFS instance, which is discovered through mesos-dns, and started by marathon creates a circular dependency. HDFS is never started because marathon is never started because HDFS is never started.

**Comment by isaacd9** [comment]
I feel like Marathon should accept a path to a Hadoop configuration as a command line flag and then use that to connect to the HDFS instance.
