### ISSUE TITLE
Docker private registry with mesosphere marathon

### ISSUE THREAD

**Issue by sourav82** [mesosphere/marathon#926]
Not able to use private docker registry with Mesos.
Below is the json with private docker registry -
{
 "container": {
  "type": "DOCKER",
  "docker": {
   "image": "10.227.125.10:5000/myimage",
   "network": "BRIDGE",
   "portMappings": [
     { "containerPort": 8080, "hostPort": 0, "servicePort": 68080, "protocol": "tcp" }
    ]
   }
 },
 "id": "mesos-myimage",
 "instances": 1,
 "cpus": 0.25,
 "mem": 256,
 "uris": []
}
It is not able to connect to private registry and download the image. From marathon it is showing deployment stage forever but it failed actually to download from private repository.

**Comment by cmluciano** [comment]
What was the resolution for this?

**Comment by IanSaunders** [comment]
Recently came across a similar issue the following solved the issue of not being able to pull from a private report:

https://www.mail-archive.com/search?l=user@mesos.apache.org&q=subject:%22Re%5C%3A+Docker+Registry+2.0+%5C%2B+Mesos+%5C%2B+Marathon%22&o=newest&f=1

**Comment by kolloch** [comment]
Hi @IanSaunders , it would be great if you could write up a sample on how to use a private registry with possible pit falls and add it to our docker documentation. What do you think?

**Comment by IanSaunders** [comment]
@kolloch sure, I have actually written something up internally [1] and happy to share.
I had a look at the docs [2] and wasn't certain how to contribute directly, do you have a link to contribution guide?

[1] https://gist.github.com/IanSaunders/17be1506e19a3723cdd0
[2] https://github.com/mesosphere/marathon/blob/master/docs/docs/native-docker.md

**Comment by kolloch** [comment]
Hey Ian,

great to hear that! That looks great. Since that is quite a bit of text, it
probably makes sense to add it as a separate file and link it from the
native-docker.md document. What do you think?

There is a contribution guide but that actually concerns itself more with
code:

https://mesosphere.github.io/marathon/docs/contributing.html

If you want to propose an update to the documentation, you can just create
a pull request against the current master. The documentation is located in
the docs/docs sub directory. The docs/README.md mentions how to locally
start jekyll to check how the rendered documentation will look like.

I just created a PR to add information about how to contribute
documentation. If you want, have a look and see if what I wrote makes sense:

https://github.com/mesosphere/marathon/pull/1896

Thanks! & Best regards,
Peter

**Comment by IanSaunders** [comment]
Great, thanks for feedback. I'm just working my way through the refactoring. Will let you know once I am done :)

**Comment by IanSaunders** [comment]
Should be good to merge now. Please see pull request for comments

**Comment by upccup** [comment]
@IanSaunders What should we do if want to download docker.tar.gz form http file website
