### ISSUE TITLE
No error feedback on undeployable tasks

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#951]
1. Click `+New App`
1. Enter
  - ID: test
  - Command: echo hello
  - URI: http://google.com
1. Click `+ Create`
1. Observe task enters `Deploying` state indefinitely.

If a task is completely misconfigured and unrunnable, I would expect Marathon to give up and show an error condition to the user.

**Comment by mlunoe** [comment]
So here the problem seems to be that the URI doesn't resolve to anything meaningful - a zip or tarball (can't remember what the backend accepts).

@aldipower Could you make sure that the frontend reflects the requirements of the backend in terms of existing 'create app' field?

@drexin It looks like the API doesn't check that the URI resolves to anything meaningful before it tries to deploy it. Would that make sense to introduce that check? This way the frontend could display the error it gets from the backend.

What are your thoughts?

**Comment by ConnorDoyle** [comment]
See the description of #686.  The frontend can inspect the last failure state.  In Mesos, the semantics of TASK_ERROR versus TASK_LOST is that tasks that terminate with state TASK_ERROR should not be expected to succeed if rescheduled.

Probably, Marathon could stop trying to reschedule these tasks as well but that can be handled as a separate issue.

**Comment by ConnorDoyle** [comment]
Filed #965 for the backend issue.

**Comment by mlunoe** [comment]
Thanks @ConnorDoyle !

**Comment by aquamatthias** [comment]
If a task fails (for whatever reason) we show that in App.lastTaskFailure.
If Marathon should give up starting that app over and over again can be controlled via backoff.
The specific problem here: URI can not be resolved is a mesos bug and reported here: https://issues.apache.org/jira/browse/MESOS-3816.
