### ISSUE TITLE
Show all groups in the web ui.

### ISSUE THREAD

**Issue by samccone** [mesosphere/marathon#959]
Currently there is no dedicated tab for seeing all of the groups (empty or not) in the web ui. This would be a nice addition to the web ui.

More than willing to PR this if you are interested.

**Comment by mlunoe** [comment]
Hi @samccone!

Thank you for creating this suggestion.
We've wanted groups in the UI for a while. We thought it could look something like this:
![Quick mockup of what it could look like](https://s3.amazonaws.com/f.cl.ly/items/3w3K0U0w310l2j2V1z1u/2015-01-08%2011.31.59.jpg "Quick mockup of what it could look like")

You will need an icon for the folder as well (it is white, so it's not visible in the browser - click the URL and hit cmd+s to save): https://s3.amazonaws.com/f.cl.ly/items/122e0A340l1z031O1c2g/icon-folder-40x40.png

We would be more than happy to look at your code!

Thank you again!

**Comment by samccone** [comment]
Nav like this correct?

![screen shot 2015-01-08 at 3 13 30 pm](https://cloud.githubusercontent.com/assets/883126/5669836/ec7c1188-9748-11e4-8cfa-9aef43cb0221.png)

**Comment by mlunoe** [comment]
Yes! :D

**Comment by aatumanova** [comment]
Hi @samccone and @mlunoe!

Here's a visual design for the groups tab:
![image](https://cloud.githubusercontent.com/assets/1326416/5674633/c58c4484-9762-11e4-89a0-d066a945ec1c.png)

And here are two folder icons, one is for an open folder and the other is a closed folder. Please scale down 50%, because they are retina size. Sizes are in the file name, slightly different than what Michael posted above.

![folder-closed-35x30](https://cloud.githubusercontent.com/assets/1326416/5674638/df9aebe6-9762-11e4-8f16-c78cf5e70a0e.png)
![folder-open-40x30](https://cloud.githubusercontent.com/assets/1326416/5674639/dfac2fd2-9762-11e4-9db7-d336068cedef.png)

Note that the closed folder is 5px less wide than the open folder. In the design, make sure to align these icons so they align flush on their left side, like this:

![image](https://cloud.githubusercontent.com/assets/1326416/5674667/a3500774-9763-11e4-919e-b8f237462006.png)

Cheers!

**Comment by samccone** [comment]
Oh thanks @aatumanova 
I am so used to working on non sponsored OS work, so this is amazing! going to pick away soon!

Thanks again for being awesome!

**Comment by ConnorDoyle** [comment]
Don't forget that groups can be nested arbitrarily.  The UI should accommodate several levels of nested groups comfortably... somehow.

**Comment by mlunoe** [comment]
The design choice is to keep them with the same left alignment - their name will make the visual difference:
"We are displaying all groups in the same level no matter the hierarchy - meaning that sub-groups are displayed with same left alignment as groups"

**Comment by bobrik** [comment]
Any update on this? Either this or #1204 should be implemented somehow.

Having 2+ screens of apps is not very convenient right now.

**Comment by mlunoe** [comment]
The short answer is that we will look into this as soon as we get some more time/hands. You are more than welcome to put up a pull request for this, if you have time to help!

**Comment by pierlo-upitup** [comment]
@bobrik : https://github.com/mesosphere/marathon/issues/1204 will be part of the upcoming 0.11 release. 
We are currently in the process of re-imagining the application overview page, and groups are definitely going to be a huge focus, although I can't tell much about the ETA for that feature yet.

**Comment by philipnrmn** [comment]
Bumped to 0.14.0 as it does not block 0.13.0

**Comment by mwasn** [comment]
Groups have been implemented with 0.13.0. Please open a new issues for improvements if you like.
