### ISSUE TITLE
Destroy App in web ui does not work consistently 

### ISSUE THREAD

**Issue by samccone** [mesosphere/marathon#961]
I have encountered a situation where clicking on the destroy button within an app has no result, there is no reaction in the UI just a silent failure.

I can successfully destroy the app after I scale it to 0 and then click destroy.

A fix for this might be to at least show a message in the UI that the destroy has failed.

Again more than willing to PR a fix for this, just let me know if you are interested.

**Comment by mlunoe** [comment]
@aldipower Could you take a look at this?

**Comment by drexin** [comment]
@mlunoe Not sure this is a frontend issue.

**Comment by samccone** [comment]
just a side bar, I do not have an exact series of steps to reproduce this bug, it is most likely due to an issue on marathon with one of the apps, however the front end is not handling this "odd" case in a clear way.

I have seen it multiple times

**Comment by drexin** [comment]
What's the log output of Marathon? Does it start a deployment?

**Comment by samccone** [comment]
That is a great question, next time I get it into this state I will dump the logs here, sorry I should have grabbed this the first time I saw it

**Comment by drexin** [comment]
No worries, thanks for your help!

**Comment by Guojian** [comment]
I have the same problem when I destroy the app in group, but not every time. Not frontend issue since I destroy it through api.

Here is the log I found:
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,755] INFO Upgrade id:/group5 version:2015-03-12T07:36:23.755Z with force:true (mesosphere.marathon.state.GroupManager:123)
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,759] INFO Compute DeploymentPlan from Group(/,Set(),Set(Group(/group2,Set(),Set(),Set(),2015-03-12T07:35:50.461Z), Group(/group4,Set(),Set(),Set(),2015-03-12T07:35:50.461Z), Group(/group3,Set(),Set(),Set(),2015-03-12T07:35:50.461Z), Group(/group5,Set(),Set(),Set(),2015-03-12T07:35:50.461Z)),Set(),2015-03-12T07:35:50.461Z) to Group(/,Set(),Set(Group(/group2,Set(),Set(),Set(),2015-03-12T07:36:23.755Z), Group(/group4,Set(),Set(),Set(),2015-03-12T07:36:23.755Z), Group(/group3,Set(),Set(),Set(),2015-03-12T07:36:23.755Z), Group(/group5,Set(),Set(),Set(),2015-03-12T07:36:23.755Z)),Set(),2015-03-12T07:36:23.755Z) (mesosphere.marathon.upgrade.DeploymentPlan$:192)
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,760] INFO Computed new deployment plan: DeploymentPlan(2015-03-12T07:36:23.755Z, ()) (mesosphere.marathon.upgrade.DeploymentPlan$:246)
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,760] INFO Deploy plan:DeploymentPlan(2015-03-12T07:36:23.755Z, ()) with force:true (mesosphere.marathon.MarathonSchedulerService:92)
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [INFO] [03/12/2015 07:36:23.777] [marathon-akka.actor.default-dispatcher-326] [akka://marathon/user/MarathonScheduler/$a] Conflicting deployments for deployment 1d97c6f9-5957-4235-af13-74b1ae237ee0 have been canceled
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,780] INFO Compute DeploymentPlan from Group(/,Set(),Set(Group(/group2,Set(),Set(),Set(),2015-03-12T07:35:50.461Z), Group(/group4,Set(),Set(),Set(),2015-03-12T07:35:50.461Z), Group(/group3,Set(),Set(),Set(),2015-03-12T07:35:50.461Z), Group(/group5,Set(),Set(),Set(),2015-03-12T07:35:50.461Z)),Set(),2015-03-12T07:35:50.461Z) to Group(/,Set(),Set(Group(/group2,Set(),Set(),Set(),2015-03-12T07:36:23.755Z), Group(/group4,Set(),Set(),Set(),2015-03-12T07:36:23.755Z), Group(/group3,Set(),Set(),Set(),2015-03-12T07:36:23.755Z), Group(/group5,Set(),Set(),Set(),2015-03-12T07:36:23.755Z)),Set(),2015-03-12T07:36:23.755Z) (mesosphere.marathon.upgrade.DeploymentPlan$:192)
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,785] INFO Computed new deployment plan: DeploymentPlan(2015-03-12T07:36:23.755Z, ()) (mesosphere.marathon.upgrade.DeploymentPlan$:246)
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,790] INFO 10.0.3.4 -  -  [12/Mar/2015:07:36:23 +0000] "DELETE /v2/apps//group5/nginx3 HTTP/1.1" 200 92 "http://54.173.239.107:8080/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36" (mesosphere.chaos.http.ChaosRequestLog:15)
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,791] INFO Deployment acknowledged. Waiting to get processed: DeploymentPlan(2015-03-12T07:36:23.755Z, ()) (mesosphere.marathon.state.GroupManager:142)
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,800] INFO Compute DeploymentPlan from Group(/,Set(),Set(Group(/group2,Set(),Set(),Set(),2015-03-12T07:35:50.461Z), Group(/group4,Set(),Set(),Set(),2015-03-12T07:35:50.461Z), Group(/group3,Set(),Set(),Set(),2015-03-12T07:35:50.461Z), Group(/group5,Set(),Set(),Set(),2015-03-12T07:35:50.461Z)),Set(),2015-03-12T07:35:50.461Z) to Group(/,Set(),Set(Group(/group2,Set(),Set(),Set(),2015-03-12T07:36:23.755Z), Group(/group4,Set(),Set(),Set(),2015-03-12T07:36:23.755Z), Group(/group3,Set(),Set(),Set(),2015-03-12T07:36:23.755Z), Group(/group5,Set(),Set(),Set(),2015-03-12T07:36:23.755Z)),Set(),2015-03-12T07:36:23.755Z) (mesosphere.marathon.upgrade.DeploymentPlan$:192)
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,800] INFO Computed new deployment plan: DeploymentPlan(2015-03-12T07:36:23.755Z, ()) (mesosphere.marathon.upgrade.DeploymentPlan$:246)
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [INFO] [03/12/2015 07:36:23.801] [marathon-akka.actor.default-dispatcher-331] [akka://marathon/user/MarathonScheduler/$a/UpgradeManager] Removing 1d97c6f9-5957-4235-af13-74b1ae237ee0 from list of running deployments
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [INFO] [03/12/2015 07:36:23.801] [marathon-akka.actor.default-dispatcher-331] [akka://marathon/user/MarathonScheduler/$a] Deployment of / successful
Mar 12 07:36:23 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:23,818] INFO 10.0.3.4 -  -  [12/Mar/2015:07:36:23 +0000] "GET /v2/apps HTTP/1.1" 200 702 "http://54.173.239.107:8080/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36" (mesosphere.chaos.http.ChaosRequestLog:15)
Mar 12 07:36:24 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:24,150] INFO 10.0.3.4 -  -  [12/Mar/2015:07:36:24 +0000] "GET /v2/deployments HTTP/1.1" 200 2 "http://54.173.239.107:8080/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36" (mesosphere.chaos.http.ChaosRequestLog:15)
Mar 12 07:36:24 ip-10-0-2-4 marathon[6424]: [2015-03-12 07:36:24,537] INFO 10.0.3.4 -  -  [12/Mar/2015:07:36:24 +0000] "GET /v2/apps HTTP/1.1" 200 702 "-" "visual-marathon-client" (mesosphere.chaos.http.ChaosRequestLog:15)

**Comment by kolloch** [comment]
I might be related to #1215. It seems to be an inconsistency between the stored apps and the group definitions.

Do you encounter this problem with a recent Marathon (= the release candidate)? Please reopen if it persists.

**Comment by samccone** [comment]
:+1: this was a few version past, but it seems like newer versions have not exhibited this behavior. We have recently switched to a slightly different local dev flow so I have less direct exposure to the management UI. 

Thanks for the response :+1:
