### ISSUE TITLE
Override default `source` in ExecutorInfo

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#991]
See [mesos.proto](https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L287)

**Comment by drexin** [comment]
@ConnorDoyle What would be a reasonable default here? I don't really understand why this would be beneficial for Marathon.

**Comment by janisz** [comment]
Is this still valid? Source is deprecated now.
>   // 'source' is an identifier style string used by frameworks to
  // track the source of an executor. This is useful when it's
  // possible for different executor ids to be related semantically.
  //
  // NOTE: 'source' is exposed alongside the resource usage of the
  // executor via JSON on the slave. This allows users to import usage
  // information into a time series database for monitoring.
  //
  // This field is deprecated since 1.0. Please use labels for
  // free-form metadata instead.
  optional string source = 10 [deprecated = true]; // Since 1.0.
https://github.com/apache/mesos/blob/1.0.0/include/mesos/mesos.proto#L497

**Comment by jdef** [comment]
`source` doesn't seem relevant anymore, closing out.
